### ISSUE TITLE
[XCUITest] Connection to WDA timed out [iProxy] recv failed: Operation not permitted

### ISSUE THREAD

**Issue by aryalakshmi** [appium/appium#10815]
## The problem

I am getting issue while opening application in iphone using robot framework

## Environment

* Appium version (or git revision) that exhibits the issue: v1.8.0 (GUI)
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MAC 10.13.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Iphone 6 / 11.1.2 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium exe
* Xcode 9.4

## Details
Open Application	http://localhost:4723/wd/hub	platformName=${platform}	platformVersion=11.1.2	deviceName='iPhone'	autoWebview=true	newCommandTimeout=1200	udid=xxxxxxxxxxxxxxxxxxxxxxxxxc1e30f	bundleId=com.x.x	noReset=true	xcodeOrgId=xxxxxxxxxx	xcodeSigningId=iPhone Developer	automationName=Appium	clearSystemFiles=True	wdaStartupRetryInterval=1000	useNewWDA=true	waitForQuiescence=false	shouldUseSingletonTestManager=false	webkitResponseTimeout=180000

## Link to Appium logs
https://gist.github.com/aryalakshmi/6edc84b86c8326234c9a66b17b496c88

Snippet of error:
[RemoteDebugger] Receiving WebKit data: '{"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"error","text":"ERROR","type":"log","line":1328,"column":24,"url":"http://localhost:8080/var/containers/Bundle/A...'
[RemoteDebugger] Did not find handler for message
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted
[XCUITest] TimeoutError: operation timed out
[XCUITest]     at afterTimeout (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:46:19)
[XCUITest]     at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Appium.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:76:13)
[XCUITest]     at ontimeout (timers.js:475:11)
[XCUITest]     at tryOnTimeout (timers.js:310:5)
[XCUITest]     at Timer.listOnTimeout (timers.js:270:5)
[JSONWP Proxy] Proxying [DELETE /session/4434395e-aebc-4130-bab3-17d27c02f91c] to [DELETE http://localhost:8100/session/7BC38FE6-35F3-4857-9391-57489183897A] with no body

**Comment by mykola-mokhnach** [comment]
This issue is resolved in appium@beta

**Comment by aryalakshmi** [comment]
This issue still exists in beta version.
https://gist.github.com/aryalakshmi/5b497a9d1150779150d05bbd4fefd96b

**Comment by mykola-mokhnach** [comment]
@imurchie Is it some new message type that we don't know about? Is it possible to just ignore unknown message types instead of throwing exceptions?

**Comment by mykola-mokhnach** [comment]
can you attach the device log?

**Comment by mykola-mokhnach** [comment]
No logs - no luck

**Comment by deepikashekar37** [comment]
I am also facing same issue.

Environment
Appium - 1.8.1
xcode - 9.4
real iOS device version - 11.4

**Appium logs **

Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_1"]
[HTTP] <-- GET /wd/hub/session/eee59416-4df8-4cd9-8986-41571c960409/contexts 200 9 ms - 36
[HTTP]
[HTTP] --> POST /wd/hub/session/eee59416-4df8-4cd9-8986-41571c960409/context
[HTTP] {"name":"WEBVIEW_1"}
[debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","eee59416-4df8-4cd9-8986-41571c960409"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 50000
[debug] [RemoteDebugger] Receiving WebKit data: '{"result":{},"id":1}'
[debug] [RemoteDebugger] Found handler for message '1'
[debug] [RemoteDebugger] WebKit debugger got a message for 'Console.enable' and have no handler, doing nothing.
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted
[W3C] Encountered internal error running command: TimeoutError: operation timed out
[W3C] at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:46:19)
[W3C] at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/release/timers.js:76:13)
[W3C] at ontimeout (timers.js:466:11)
[W3C] at tryOnTimeout (timers.js:304:5)
[W3C] at Timer.listOnTimeout (timers.js:267:5)

Can anyone please help on this ?

**Comment by stefan-spajic** [comment]
I have same issue in Appium logs. Running Selenium Java test on iPhone 6. 
When test is ran, on the device Safari is started, **but instead of navigating to URL from the test, test navigate to 'appium.io'**. When page is loaded _TimeoutError: operation timed out at afterTimeout_  error is thrown.

**Environment**

- MacOS High Sierra 10.13.6
- Appium 1.6.2
- iPhone 6 / 11.4 / Real device
- Xcode 9.4

**Comment by dusanpanic92** [comment]
Try to clear Safari data on the iPhone and reset device. 

If that won't help:
- Delete currently installed WebDriverAgentRunner
- On the PC install Appium 1.8.1 desktop install
- Run test with 1.8.1 Appium, it will install you new WebDriverAgentRunner
- Now try to run test again with Appium 1.8.2 beta

I hope it will help, it's worked for me. Good luck :)

**Comment by vegh1010** [comment]
@dusanpanic92 thanks for the solution. It does help with reducing the chance of having that issue coming up but doesn't fully resolve the issue. It's better than nothing. Thanks :)

**Comment by danishS** [comment]
> Try to clear Safari data on the iPhone and reset device.
> 
> If that won't help:
> 
> * Delete currently installed WebDriverAgentRunner
> * On the PC install Appium 1.8.1 desktop install
> * Run test with 1.8.1 Appium, it will install you new WebDriverAgentRunner
> * Now try to run test again with Appium 1.8.2 beta
> 
> I hope it will help, it's worked for me. Good luck :)

I'm having this same issue and I tried your suggestion but to no avail, the problem persists. Has there been any solution to this?

**Comment by testingxpertshyd** [comment]
Hi @mykola-mokhnach
I have this error too with Appium 1.13.0, Xcode 10.2.1 and iOS 12.2 on Mac 10.14.4.
Anyone have any solution. Please update...
