### ISSUE TITLE
iOS Safari Appium 1.8 beta and java-client 6.1.0 : Switch to window not working in safari real ios(9.3+ ) device

### ISSUE THREAD

**Issue by ashoksqa** [appium/appium#10931]
Switch to window not working after updating to appium and java-client latest versions.
Getting below issue :
 
[debug] [W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["name"]} and you sent ["handle"]

## Details

used method  : 

ArrayList<String> window = new ArrayList<String>(driver.getWindowHandles());
		((AppiumDriver<WebElement>) driver).switchTo().window(window.get(1));

## Link to Appium logs
[HTTP] {"using":"name","value":"Allow"}
[debug] [W3C] Calling AppiumDriver.findElement() with args: ["name","Allow","23fada6d-ae35-4cc4-92f1-841af1cde70f"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:3595/session/F47FAF3B-07F9-4CBA-A4AA-86D4B3494204/element] with body: {"using":"name","value":"Allow"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"54000000-0000-0000-A401-000000000000"},"sessionId":"F47FAF3B-07F9-4CBA-A4AA-86D4B3494204","status":0}
[debug] [W3C] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"54000000-0000-0000-A401-000000000000"}
[HTTP] <-- POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/element 200 15791 ms - 88
[HTTP] 
[HTTP] --> POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/element/54000000-0000-0000-A401-000000000000/click
[HTTP] {"id":"54000000-0000-0000-A401-000000000000"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/element/54000000-0000-0000-A401-000000000000/click] to [POST http://localhost:3595/session/F47FAF3B-07F9-4CBA-A4AA-86D4B3494204/element/54000000-0000-0000-A401-000000000000/click] with body: {"id":"54000000-0000-0000-A401-000000000000"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"54000000-0000-0000-A401-000000000000","value":"","sessionId":"F47FAF3B-07F9-4CBA-A4AA-86D4B3494204"}
[JSONWP Proxy] Replacing sessionId F47FAF3B-07F9-4CBA-A4AA-86D4B3494204 with 23fada6d-ae35-4cc4-92f1-841af1cde70f
[HTTP] <-- POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/element/54000000-0000-0000-A401-000000000000/click 200 26455 ms - 118
[HTTP] 
1 end time :3 :: 22-Jun-2018__05_37_34PM
[HTTP] --> GET /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/contexts
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getContexts() with args: ["23fada6d-ae35-4cc4-92f1-841af1cde70f"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 34772
[debug] [RemoteDebugger] Sending request to: http://localhost:34772/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:34772/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/https://demosite01-lcec.lrn.com/app/courseinfo/41802","title":"LCEC: ZQA504 - tile menu - lessons and kc DO NOT DELETE","url":"https://demosite01-lcec.lrn.com/app/courseinfo/41802","webSocketDebuggerUrl":"ws://localhost:34772/devtools/page/1","appId":"PID:422"},{"devtoolsFrontendUrl":"/devtools/devtools.html3 :: Mobile Web View found :WEBVIEW_1
?ws=localhost:34772/devtools/page/2","faviconUrl":"","thumbnailUrl":"/thumb/about:blank","title":"","url":"about:blank","webSocketDebuggerUrl":"ws://localhost:34772/devtools/page/2","appId":"PID:422"}]
[debug] [W3C] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_1","WEBVIEW_2"]
[HTTP] <-- GET /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/contexts 200 10 ms - 48
[HTTP] 
[HTTP] --> POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/context
[HTTP] {"name":"WEBVIEW_1"}
[debug] [W3C] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","23fada6d-ae35-4cc4-92f1-841af1cde70f"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:34772/devtools/page/1
[debug] [RemoteDebugger] Starting to listen for JavaScript console
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Console.enable","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true}}
[debug] [RemoteDebugger] Webkit response timeout: 5000
[debug] [RemoteDebugger] Received WebKit data: '{"result":{},"id":1}'
[debug] [RemoteDebugger] Found method 'Console.enable' for message '1'
[debug] [W3C] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/context 200 16 ms - 14
[HTTP] 
[HTTP] --> GET /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/window/handles
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getWindowHandles() with args: ["23fada6d-ae35-4cc4-92f1-841af1cde70f"]
[debug] [XCUITest] Executing command 'getWindowHandles'
[debug] [iOS] Selecting by url: true (expected url: 'https://demosite01-lcec.lrn.com/app/courseinfo/41802')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 34772
[debug] [RemoteDebugger] Sending request to: http://localhost:34772/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"","faviconUrl":"","thumbnailUrl":"/thumb/https://demosite01-lcec.lrn.com/app/courseinfo/41802","title":"LCEC: ZQA504 - tile menu - lessons and kc DO NOT DELETE","url":"https://demosite01-lcec.lrn.com/app/courseinfo/41802","webSocketDebuggerUrl":"ws://localhost:34772/devtools/page/1","appId":"PID:422"},{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:34772/devtools/page/2","faviconUrl":"","thumbnailUrl":"/thumb/https://demosite01-lcec.course.lrn.com/rev2018062100/course/templates/ajax/FluidX/FluidX2.0/app_min/index.html?aicc_sid=190bba66351c0d2cf671ad57f50669d7&aicc_url=/app/aicc/track2a&sid=41802&lang=en&cpath=ZQA504/en/ZQA504-a80en/&course_xml=/app/coursexml/custom_xml/283890&page_config=/app/coursexml/custom_page_config/283890&media=off","title":"","url":"https://demosite01-lcec.course.lrn.com/rev2018062100/course/templates/ajax/FluidX/FluidX2.0/app_min/index.html?aicc_sid=190bba66351c0d2cf671ad57f50669d7&aicc_url=/app/aicc/track2a&sid=41802&lang=en&cpath=ZQA504/en/ZQA504-a80en/&course_xml=/app/coursexml/custom_xml/283890&page_config=/app/coursexml/custom_page_config/283890&media=off","webSocketDebuggerUrl":"ws://localhost:34772/devtools/page/2","appId":"PID:422"}]
[debug] [W3C] Responding to client with driver.getWindowHandles() result: ["1","2"]
[HTTP] <-- GET /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/window/handles 200 10 ms - 19
[HTTP] 
[HTTP] --> POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/window
[HTTP] {"handle":"2"}
[debug] [W3C] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["name"]} and you sent ["handle"]
[HTTP] <-- POST /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/window 400 37 ms - 4162
[HTTP] 
[HTTP] --> GET /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/screenshot
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getScreenshot() with args: ["23fada6d-ae35-4cc4-92f1-841af1cde70f"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [XCUITest] Taking screenshot with WDA
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:3595/session/F47FAF3B-07F9-4CBA-A4AA-86D4B3494204/screenshot] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAABNoAAAigCAYAAADpkk+ZAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAARQAAAAKAAABFAAAARQAATyhofR\\/b0AAEAASURBVHgB\\r\\n7N0JuK9VVT\\/wCwg4VVaWmiFZ5pRDppVWhgOIzCCgIAkIAoo4zyOlaZal5lRWhpZZ\\r\\nirOWQypqTqmlKfNlckAQELjzPfde2P\\/9een78+V2zwDnnMs9\\/tc5z372fvew9lpr\\r\\nf9+197t++93vsvXr17cKpYPCQGGgMFAYKAwUBgoDhYHCQGGgMFAYKAwUBgoDhYHC\\r\\nwPwwsKwUOD8Flv5Kf4WBwkBhoDBQGCgMFAYKA4WBwkBhoDBQGCgMFAYKAzBQjrba\\r\\n0Vc7GgsDhYHCQGGgMFAYKAwUBgoDhYHCQGGgMFAYKAwUBhYAA+VoWwAllte6vNaF\\r\\ngcJAYaAwUBgoDBQGCgOFgcJAYaAwUBgoDBQGCgPlaCtHW3msCwOFgcJAYaAwUBgo\\r\\nDBQGCgOFgcJAYaAwUBgoDBQGFgAD5WhbACWWx7o81oWBwkBhoDBQGCgMFAYKA4WB\\r\\nwkBhoDBQGCgMFAYKA+VoK0dbeawLA4WBwkBhoDBQGCgMFAYKA4WBwkBhoDBQGCgM\\r\\nFAYWAAPlaFsAJZbHujzWhYHCQGGgMFAYKAwUBgoDhYHCQGGgMFAYKAwUBgoD5Wgr\\r\\nR1t5rAsDhYHCQGGgMFAYKAwUBgoDhYHCQGFgG8DAunXr2saNG9vU1FRbs2bNEEvL\\r\\nF8b56slbu3Zt27Bhw9CunDzl5CkMTI8B98+qVasm95V7zH3k\\/hEWSnflaNsGjOlC\\r\\nDWbRmf6GKt2UbgoDhYHCQGGgMFAYKAwUBgoDhYFtHQOrV68eHvbz4J+YgwDvHGuc\\r\\nA9IcBGKONoE...
[debug] [W3C] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABNoAAAigCAYAAADpkk+ZAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAARQAAAAKAAABFAAAARQAATyhofR/b0AAEAASURBVHgB\r\n7N0JuK9VVT/wCwg4VVaWmiFZ5pRDppVWhgOIzCCgIAkIAoo4zyOlaZal5lRWhpZZ\r\nirOWQypqTqmlKfNlckAQELjzPfde2P/9een78+V2zwDnnMs9/tc5z372fvew9lpr\r\nf9+197t++93vsvXr17cKpYPCQGGgMFAYKAwUBgoDhYHCQGGgMFAYKAwUBgoDhYHC\r\nwPwwsKwUOD8Flv5Kf4WBwkBhoDBQGCgMFAYKA4WBwkBhoDBQGCgMFAYKAzBQjrba\r\n0Vc7GgsDhYHCQGGgMFAYKAwUBgoDhYHCQGGgMFAYKAwUBhYAA+VoWwAllte6vNaF\r\ngcJAYaAwUBgoDBQGCgOFgcJAYaAwUBgoDBQGCgPlaCtHW3msCwOFgcJAYaAwUBgo\r\nDBQGCgOFgcJAYaAwUBgoDBQGFgAD5WhbACWWx7o81oWBwkBhoDBQGCgMFAYKA4WB\r\nwkBhoDBQGCgMFAYKA+VoK0dbeawLA4WBwkBhoDBQGCgMFAYKA4WBwkBhoDBQGCgM\r\nFAYWAAPlaFsAJZbHujzWhYHCQGGgMFAYKAwUBgoDhYHCQGGgMFAYKAwUBgoD5Wgr\r\nR1t5rAsDhYHCQGGgMFAYKAwUBgoDhYHCQGFgG8DAunXr2saNG9vU1FRbs2bNEEvL\r\nF8b56slbu3Zt27Bhw9CunDzl5CkMTI8B98+qVasm95V7zH3k/hEWSnflaNsGjOlC\r\nDWbRmf6GKt2UbgoDhYHCQGGgMFAYKAwUBgoDhYFtHQOrV68eHvbz4J+YgwDvHGuc\r\nA9IcBGKONoEDYVuXr/ire/CmxID7JI7s3Gvy8JTrheCvHG1doQuhyKJReiwMFAYK\r\n...
[HTTP] <-- GET /wd/hub/session/23fada6d-ae35-4cc4-92f1-841af1cde70f/screenshot 200 432 ms - 932924
[HTTP]

**Comment by ashoksqa** [comment]
@mykola-mokhnach  and @imurchie  : Please please help me on this.

**Comment by imurchie** [comment]
@ashoksqa Please upgrade to the latest Appium beta (`npm uninstall -g appium && npm install -g appium@beta`)

**Comment by ashoksqa** [comment]
@imurchie Thanks for the responce. verified in "npm install -g appium@beta" version only

**Comment by ashoksqa** [comment]
@imurchie  : This issue is only in latest java-client only. In 5.0.4 it`s working properly.

**Comment by rupesh-a** [comment]
Is this issue same as https://github.com/appium/appium/issues/8280?

**Comment by mykola-mokhnach** [comment]
Fixed in appium@beta

**Comment by milesHero** [comment]
@mykola-mokhnach, What is the equivalent of appium@beta to appium desktop server? I am testing in IOS simulator with appium version 1.7.0 and java client 6.1.0 and still getting this error. Tried also with appium desktop version 1.6.2 and 1.6,3. Thank you.
