### ISSUE TITLE
Appium implicit wait error {"message":"unknown error: 'ms' must be a double\n

### ISSUE THREAD

**Issue by sumanguduru** [appium/appium#11016]
## The problem
unable to set implicitwait

## Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: mac sierra
* Node.js version (unless using Appium.app|exe): v10.5.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details
Getting below error when i set implicitwait
driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);

http://127.0.0.1:8004/wd/hub/session/467c86d1f3c0b0ad44326e22e9ac1559/timeouts] with body: {"implicit":20000}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"467c86d1f3c0b0ad44326e22e9ac1559","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=67.0.3396.87)\n  

## Link to Appium logs
https://gist.github.com/sumanguduru/499cec84e39820bdb1fbaacd602add0f

## Code To Reproduce Issue [ Good To Have ]
driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);

**Comment by mykola-mokhnach** [comment]
@dpgraham I assume we should properly modify the payload in such case (the main driver operates in W3C mode and Chromedriver in JSONWP) or switch Chromedriver to W3C as well

**Comment by dpgraham** [comment]
We have logic in place so that you can proxy from W3C to JSONWP and it works. It's probably a bug. I'll have a look at this.

**Comment by mykola-mokhnach** [comment]
I know. I assume the problem with this particular endpoint is that the actual url is the same for W3C and JSONWP, but expected payloads are different

**Comment by dpgraham** [comment]
Right, yeah this is one of the few URL's that had a breaking change. Should be fixable.

**Comment by sumanguduru** [comment]
Can you please give me some example how can i proxy W3C to JSONWP ?

**Comment by mykola-mokhnach** [comment]
@sumanguduru You cannot. Try to set MobileCapabilityType.FORCE_MJSONWP capability in order to enforce JSONWP protocol as a temporary workaround.

**Comment by sumanguduru** [comment]
It worked Thanks!

**Comment by mykola-mokhnach** [comment]
the fix is published in beta

**Comment by FilipWennerdahlSopraSteria** [comment]
I am still having this issue with the latest appium 1.8.2-beta and as mentioned setting MobileCapabilityType.FORCE_MJSONWP is a working workaround.

### Environment

* Appium version (or git revision) that exhibits the issue: 1.8.2-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.8.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v8.0.0
* Mobile platform/version under test: Android 8.0
* Real device or emulator/simulator: real device, hybrid webview app
* Appium CLI or Appium.app|exe: Appium CLI

### Details

```
[HTTP] --> POST /wd/hub/session/b3056362-517b-471b-90ad-0af15de0ac68/timeouts
[HTTP] {"implicit":1000}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Matched '/wd/hub/session/b3056362-517b-471b-90ad-0af15de0ac68/timeouts' to command name 'timeouts'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/b3056362-517b-471b-90ad-0af15de0ac68/timeouts] to [POST http://127.0.0.1:8000/wd/hub/session/9e5b0cdf806dece794beb49548a9c081/timeouts] with body: {"implicit":1000}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"9e5b0cdf806dece794beb49548a9c081","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=67.0.3396.87)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)"}}
[W3C] Encountered internal error running command:  {"w3cStatus":400,"jsonwp":{"sessionId":"9e5b0cdf806dece794beb49548a9c081","status":13,"value":{"message":"unknown error: 'ms' must be a double\n  (Session info: chrome=67.0.3396.87)\n  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.17134 x86_64)"}}} ProxyRequestError: Could not proxy command to remote server. Original error: The request to /wd/hub/session/b3056362-517b-471b-90ad-0af15de0ac68/timeouts has failed
```

**Comment by sumanguduru** [comment]
You can set mobile capability as true for MobileCapabilityType.FORCE_MJSONWP

This bug fixed in latest beta version

**Comment by FilipWennerdahlSopraSteria** [comment]
@sumanguduru Yes i am currently using the force mjsonwp capability with success but i just wanted to report that the bug is still occurring in the latest beta version even though the fix is merged and published.

**Comment by mykola-mokhnach** [comment]
@FilipWennerdahlSopraSteria it would be more effective if you create a new issue rather that commenting to the closed one.

@dpgraham FYI
