### ISSUE TITLE
Unable to start Espresso session with latest beta

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#11525]
## The problem

After installing the latest beta, unable to start espresso driver session. fails with error 

uncaughtException: Cannot read property 'includes' of undefined

## Environment

* Appium version (or git revision) that exhibits the issue: Latest beta
* Last Appium version that did not exhibit the issue (if applicable): last beta version or may be before that
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/saikrishna321/a88fd256d03e9c6ce865c632dc24b3fd

**Comment by mykola-mokhnach** [comment]
I've pushed https://github.com/appium/appium-base-driver/pull/269, which should address the logged error

**Comment by mykola-mokhnach** [comment]
Try on the other machine or with different nodejs version. Somehow the current setup swallows exception data

**Comment by saikrishna321** [comment]
@mykola-mokhnach i tried the latest beta over node v8.9.X and it still fails. Are you able to create a Espresso session in your machine ?

**Comment by mykola-mokhnach** [comment]
Maybe @dpgraham has some more ideas on that

**Comment by dpgraham** [comment]
Can you assign this issue to me.

**Comment by vsadineni1** [comment]
I tried this test. I am able to create the session successfully. However I am on the below appium version. Not sure if that is playing a role.

$ appium --version
1.8.0

$ node --version
v9.3.0

Here are my appium server logs in the gist: https://gist.github.com/vsadineni1/5ea7691e6a00be15a9dac8f3fbf2cca9

Am I using the wrong way to get the element?
However when I try to click on the login button, it does not find the element.
----
  //login
    **WebElement login = driver.findElementByClassName("android.widget.TextView"");**
    if(login != null) {
        System.out.println("Found the login button");
    }
    wait.until(elementToBeClickable(login));
    System.out.println("Clicking on the element");
    login.click();
-------
<img width="868" alt="image" src="https://user-images.githubusercontent.com/24640164/47196516-85189980-d326-11e8-89ce-2db16fcdd723.png">

Appium server does not give any response back to the below POST element command:
[HTTP] --> POST /wd/hub/session/8f3fd0f9-bcbb-45f4-a91b-405f711bf3d8/element
[HTTP] {"using":"class name","value":"android.widget.Button"}
[W3C] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/8f3fd0f9-bcbb-45f4-a91b-405f711bf3d8/element] to [POST http://localhost:8080/session/021bc71b-7697-40a8-beb8-45fe67ae6248/element] with body: {"using":"class name","value":"android.widget.Button"}

**Comment by saikrishna321** [comment]
@vsadineni1 u have old appium server version which we don't support anymore. This issue is regarding the latest beta.2

**Comment by vsadineni1** [comment]
@mykola-mokhnach @saikrishna321 
I have tried it on the latest appium beta: 1.9.2-beta.2.
Session creation request failed. Please find the logs below.

Appium Server Log: https://gist.github.com/vsadineni1/9e7ee6f0fd9c676e59dc79c4fa3a4c96
Test exception Log: https://gist.github.com/vsadineni1/a1a36fe1e942ba5f703b11f51068c11b

**Comment by dpgraham** [comment]
Can one of you post the logcat for when this error happened?

Also, can you try setting `forceMjsonwp=true` in your caps and see if the error is different?

I'm not able to reproduce this on my side.

**Comment by KazuCocoa** [comment]
## with MJSONWP
https://gist.github.com/KazuCocoa/3d3fb111550c18225318fab4d4422237

## with W3C
https://gist.github.com/KazuCocoa/de51a424e3470f674039f968626308cb

Mine was below

```
$ npm ls appium-base-driver
appium@1.9.2-beta.2 /Users/kazuaki/GitHub/appium
├─┬ appium-android-driver@4.4.0
│ ├── appium-base-driver@3.9.1  deduped
│ └─┬ appium-chromedriver@4.6.0
│   └── appium-base-driver@3.9.1  deduped
├── appium-base-driver@3.9.1
├─┬ appium-espresso-driver@1.0.0-beta.18
│ └── appium-base-driver@3.9.1  deduped
├─┬ appium-fake-driver@0.6.2
│ └── appium-base-driver@3.9.1  deduped
├─┬ appium-ios-driver@2.12.0
│ ├── appium-base-driver@3.9.1  deduped
│ └─┬ appium-remote-debugger@3.22.1
│   └── appium-base-driver@3.9.1  deduped
├─┬ appium-mac-driver@1.4.1
│ └── appium-base-driver@3.9.1  deduped
├─┬ appium-selendroid-driver@1.13.1
│ └── appium-base-driver@3.9.1  deduped
├─┬ appium-tizen-driver@1.1.1-beta.2
│ └── appium-base-driver@3.9.1  deduped
├─┬ appium-uiautomator2-driver@1.22.0
│ └── appium-base-driver@3.9.1  deduped
├─┬ appium-windows-driver@1.5.1
│ └── appium-base-driver@3.9.1  deduped
├─┬ appium-xcuitest-driver@2.98.0
│ └── appium-base-driver@3.9.1  deduped
└─┬ appium-youiengine-driver@1.0.20
  ├─┬ appium-android-driver@2.7.0
  │ ├─┬ appium-android-bootstrap@2.13.1
  │ │ └── appium-base-driver@3.9.1  deduped
  │ └── appium-base-driver@2.33.0  deduped
  └── appium-base-driver@2.33.0
```

let me investigame further (uiautomator2 worked fine.)

The test target was https://github.com/appium/ruby_lib_core/tree/master/test with `espresso`

**Comment by KazuCocoa** [comment]
```
[debug] [AndroidDriver] Performed fast reset on the installed 'io.appium.android.apis' application (stop and clear)
[Espresso] Repackaging espresso server for: 'io.appium.android.apis'
[Espresso] Creating new manifest: '/var/folders/y6/524wp8fx0xj5q1rf6fktjrb00000gn/T/AndroidManifest.xml'
[debug] [Espresso] Deleting espresso session
```

After `Creating new manifest:`, `logger.info(`Repackaged espresso server ready: '${this.modServerPath}'`);` didn't appear. It probably happened something beftween them.

https://github.com/appium/appium-espresso-driver/blob/3cb07de3fe5f702764395a1609a5a01d436d9ddd/lib/espresso-runner.js#L56-L61

**Comment by KazuCocoa** [comment]
Except for `app` directory, all of files in https://github.com/appium/appium-espresso-driver/tree/master/espresso-server/ haven't been packaged in npm module.

```
$ ls /Users/kazuaki/GitHub/appium/node_modules/appium-espresso-driver/espresso-server/
app
```

**Comment by KazuCocoa** [comment]
After adding espresso-server/AndroidManifest-test.xml by manual in my local, creating session has been succeeded.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa It might be some internal bug in the ncp module, which is used internally by appium-support for `copyFile` call. I think it makes sense to try replacing it with some other alternative (for example file streams)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-support/blob/a7fe1a4589ea6c5de14063792749e41b39cd0608/lib/fs.js#L36
