### ISSUE TITLE
appium 1.13.0 cannot launch webdriveragent with Xcode version below 10.2

### ISSUE THREAD

**Issue by waynema** [appium/appium#12586]
## The problem

After upgrade to latest appium version 1.13.0 using "npm install -g appium",  test is not not launching on iOS simulator and there are errors in log:
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'Scripts/bootstrap.sh -d' exited with code 1
[XCUITest]     at quitAndUninstall (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:501:15)
[XCUITest]     at <anonymous>

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13.0
* Last Appium version that did not exhibit the issue (if applicable): 1.12.1
* Desktop OS/version used to run Appium: MacOS High Sierra version 10.13.6
* Node.js version (unless using Appium.app|exe): v9.3.0
* Npm or Yarn package manager: 6.8.0
* Mobile platform/version under test: iOS 12
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium CLI

**Comment by imurchie** [comment]
You probably need to upgrade Carthage. Can you try:
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WedDriverAgent

./Scripts/bootstrap.sh -d
```
And see what the output is?

**Comment by waynema** [comment]
$ ./Scripts/bootstrap.sh -d
Fetching dependencies
Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by imurchie** [comment]
Ah. I think the problem is that you don't have any tvOS devices available, and the script is breaking. This has been fixed (https://github.com/appium/WebDriverAgent/commit/d1098a72cdfe86224a6cbff835010a5729cacd2e) but that fix is not in the release. :(

For now, can you create a tvOS device in Xcode?

**Comment by waynema** [comment]
ok,  will try that.  Thanks for the quick reply.

**Comment by waynema** [comment]
@imurchie ,  not sure how to create a tvOS device in Xcode.  It seems I can call a deviceName called "Apple TV" as my simulator but test is still failing the same.

**Comment by imurchie** [comment]
I apologize. The fix seems to be there in the latest release anyway. I'm looking a little.

**Comment by imurchie** [comment]
In fact, it seems that it is in the fix itself that the error is being thrown! What happens when you run `xcrun simctl list -j devices available` on your machine?

**Comment by waynema** [comment]
```
$ xcrun simctl list -j devices available
Usage: simctl list [-j | --json] [devices|devicetypes|runtimes|pairs]
$ xcrun simctl list -j devices
gives me a list of devices though
```

**Comment by imurchie** [comment]
Interesting. I guess `available` was recently added? What version of the command line tools do you have?

**Comment by waynema** [comment]
`$ xcrun -version
xcrun version 43.`

**Comment by waynema** [comment]
```
$ xcodebuild -version
Xcode 10.1
Build version 10B61
```

**Comment by imurchie** [comment]
@mykola-mokhnach It seems there is some variance in support for `available` in listing devices in `simctl`. I guess the Python ought to do the filtering for availability, too?

**Comment by mykola-mokhnach** [comment]
What is the output of `xcrun simctl list -j devices` ?

**Comment by KazuCocoa** [comment]
Ah... The lower command line tool had different arguments.. Thanks.

**Comment by VladimirSeleznov** [comment]
I'm facing the same issue with XCode 10.2.1

**Comment by mykola-mokhnach** [comment]
A temporary workaround would be to comment out the https://github.com/appium/WebDriverAgent/blob/7f5dfede5e4fdf341bf830163dbd01516158adf4/Scripts/bootstrap.sh#L53 string

**Comment by mykola-mokhnach** [comment]
The fix is published in beta

**Comment by mrk-han** [comment]
Can you confirm that this is related to command-line tool version, and not the version of xcode 10.2?

**Comment by KazuCocoa** [comment]
Yes. CLI bundled in Xcode 10.2.

**Comment by rkn411** [comment]
> You probably need to upgrade Carthage. Can you try:
> 
> ```
> cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WedDriverAgent
> 
> ./Scripts/bootstrap.sh -d
> ```
> 
> And see what the output is
@imurchie can we download app from appstore and automate ?
if we have bundle id?
is it possible
