### ISSUE TITLE
Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by isuroo** [appium/appium#12848]
## The problem
I get socket hang up error whenever I tried to run the scrolling script.
Tried with deference scripts but the result was the same.
So far this issue occurs only when I use scroll/ swipe options. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.13
* Last Appium version that did not exhibit the issue (if applicable): 1.13
* Desktop OS/version used to run Appium: macOS Mojave v10.14.5
* Node.js version (unless using Appium.app|exe): v12.4.0
* Npm or Yarn package manager: 
* Mobile platform/version under test: iPhone 8 (v12.1)
* Real device or emulator/simulator: Real device 
* Appium CLI or Appium.app|exe: applium

## Details
Full error description:
[iProxy] recv failed: Connection reset by peer
[iProxy] recv failed: Operation not permitted
[iProxy] recv failed: Operation timed out
[iProxy] recv failed: Operation timed out
[WD Proxy] Got an unexpected response: {"code":"ECONNRESET"}
[W3C (8ef780ab)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

The script I use for the scrolling:

	public static void topToBottomSwipe() {
		// Scroll top to bottom
		JavascriptExecutor js = (JavascriptExecutor) driver;
		HashMap<String, String> swipeObject = new HashMap<String, String>();
		swipeObject.put("direction", "down");

		js.executeScript("mobile:scroll", swipeObject);

	}

**Comment by mykola-mokhnach** [comment]
Possible duplicate of https://github.com/appium/appium/issues/12794

Please attach the device log as well.

**Comment by RonKalian** [comment]
Has this issue been fixed in latest `libimobiledevice/usbmuxd`?
The only resolution in #12794 is a usbmuxd.zip which seems to come from an unknown fork of `libimobiledevice/usbmuxd`.

**Comment by umutuzgur** [comment]
@RonKalian We are removing libimobiledevice from the repo and in master, iproxy is already removed. I would suggest giving a shot with the beta. You can install that with `npm install appium@beta`

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by jonathan-tan-viki** [comment]
> Has this issue been fixed in latest `libimobiledevice/usbmuxd`?
> The only resolution in #12794 is a usbmuxd.zip which seems to come from an unknown fork of `libimobiledevice/usbmuxd`.

It's actually based on `libimobiledevice/libusbmuxd` and yea it's been fixed in the latest commit

Reference: https://github.com/flutter/flutter/issues/35102

**Comment by pacchan** [comment]
Hi @umutuzgur 

Did you experience the Xcode 65 signing issue when you implement Appium beta on your end

**Comment by coolvasanth** [comment]
It's Feb 2020, I'm still facing the same issue. 

`Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 302 - undefined Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.`

I have completed all the setup required to run webdriver agent on real device. Still no help. 

My system info:
Xcode : 11
iOS : 12.4
Appium : 1.13 

Stuck with this since 2 weeks, please help.

**Comment by coolvasanth** [comment]
It's been 11 days since I posted this question, I have been stuck with it since 2 sprints, kindly someone help me....

**Comment by imurchie** [comment]
@coolvasanth  I think it has languished because there is little overlap with the original issue.

My first thing would be: try the most recent Appium version, to see if the problem has been fixed. 1.13 was released 10 months ago, which is also about 5 months _after_ Xcode 11 was released, so there is little chance that it will be supported.

**Comment by muralitallapudi** [comment]
my system Info :

MAC Book Pro ,  iOS - 10.15.7
XCode Version : 12.0.1 
Appium Version : 1.18.3 
iPhone 11 - iOS 14

i am getting below error while  opening up my App in iPhone11  

[debug] [35m[W3C (819d70be)][39m Calling AppiumDriver.getSession() with args: ["819d70be-6f5d-4c93-90a8-9b3cd9176690"]
[debug] [35m[XCUITest][39m Executing command 'getSession'
[debug] [35m[WD Proxy][39m Matched '/' to command name 'getSession'
[debug] [35m[WD Proxy][39m Proxying [GET /] to [GET http://127.0.0.1:8100/session/4358E020-9EF0-4F4A-B6CB-E955B21EB212] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"sessionId":"4358E020-9EF0-4F4A-B6CB-E955B21EB212","capabilities":{"device":"iphone","browserName":"NetSfere","sdkVersion":"14.0","CFBundleIdentifier":"com.infinite.netsfere-ios"}},"sessionId":"4358E020-9EF0-4F4A-B6CB-E955B21EB212"}
[debug] [35m[WD Proxy][39m Proxying [GET /wda/screen] to [GET http://127.0.0.1:8100/session/4358E020-9EF0-4F4A-B6CB-E955B21EB212/wda/screen] with no body
[35m[WD Proxy][39m Error: timeout of 240000ms exceeded
[35m[WD Proxy][39m     at createError (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/core/createError.js:16:15)
[35m[WD Proxy][39m     at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/node_modules/axios/lib/adapters/http.js:264:16)
[35m[WD Proxy][39m     at Object.onceWrapper (events.js:421:26)
[35m[WD Proxy][39m     at RedirectableRequest.emit (events.js:314:20)
[35m[WD Proxy][39m     at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/follow-redirects/index.js:13:24)
[35m[WD Proxy][39m     at ClientRequest.emit (events.js:314:20)
[35m[WD Proxy][39m     at Socket.emitRequestTimeout (_http_client.js:774:9)
[35m[WD Proxy][39m     at Object.onceWrapper (events.js:420:28)
[35m[WD Proxy][39m     at Socket.emit (events.js:326:22)
[35m[WD Proxy][39m     at Socket._onTimeout (net.js:482:8)
[35m[WD Proxy][39m     at listOnTimeout (internal/timers.js:554:17)
[35m[WD Proxy][39m     at processTimers (internal/timers.js:497:7)
[debug] [35m[W3C (819d70be)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[debug] [35m[W3C (819d70be)][39m     at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:275:13)
[debug] [35m[W3C (819d70be)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C (819d70be)][39m     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[debug] [35m[W3C (819d70be)][39m     at XCUITestDriver.proxyCommand (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:96:12)
[debug] [35m[W3C (819d70be)][39m     at XCUITestDriver.getScreenInfo (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:240:10)
[debug] [35m[W3C (819d70be)][39m     at XCUITestDriver.getSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:1224:38)
[35m[HTTP][39m [37m<-- GET /wd/hub/session/819d70be-6f5d-4c93-90a8-9b3cd9176690 [39m[31m500[39m [90m60162 ms - 1110[39m

**Comment by Annie-Samba** [comment]
Also getting "Original error: Could not proxy command to the remote server. Original error: socket hang up" issue on most recent appium 1.20.2 App keeps reopening back and forth in real device with Appium webdriveragent session error being displayed. Any way to fix this?
