### ISSUE TITLE
Unable to switchToFrame in Android Chrome using W3C format

### ISSUE THREAD

**Issue by mgrybyk** [appium/appium#12989]
## The problem

Command https://github.com/appium/appium-base-driver/blob/e0f442f391806f10cc173906df1ffcbab71a9a26/lib/protocol/routes.js#L101 doesn't support W3C format

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.0
* Mobile platform/version under test: Android, hybrid app, Chrome 45, Chromedriver 45

## Details

when passing body
```
{
    id: { 
        "element-6066-11e4-a52e-4f735466cecf": "ELEMENT-57"
    }
}
```
https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L101 command fails with error: `ELEMENT is missing`

## Code To Reproduce Issue [ Good To Have ]

it depends on language, with webdriverio it is `browser.switchToFrame('iframe')`

original issue: https://github.com/webdriverio/webdriverio/issues/4265

**Comment by imurchie** [comment]
Can you provide the _full_ Appium server logs, as a link to a https://gist.github.com?

There is no Chromedriver 45, so it is hard to say what is going on and how you might fix it.

**Comment by mgrybyk** [comment]
I'll provide the logs tomorrow but there is nothing special there, it works as expected. 

To workaround it I'm adding ELEMENT to id. To fix it on appium side we should get element not only by ELEMENT property but also by `element-6066-11e4-a52e-4f735466cecf`.

This is common w3c compliance issue.

**Comment by mykola-mokhnach** [comment]
@mgrybyk Try appium@beta. I assume the issue should be fixed by https://github.com/appium/appium-base-driver/commit/ed16a689d341d8f436b167bcd3270518eb9f6ea2

**Comment by mgrybyk** [comment]
@imurchie @mykola-mokhnach still doesn't work with appium1.14.beta2, see logs here https://gist.github.com/mgrybyk/a6cc50cc3db76fc501adb823c8730333

`"invalid argument: missing 'ELEMENT'`

**Comment by mykola-mokhnach** [comment]
Thanks for trying this @mgrybyk 
I'll do some tunings

**Comment by mykola-mokhnach** [comment]
Published the fix to appium@beta

**Comment by mgrybyk** [comment]
Thank you!

**Comment by christian-bromann** [comment]
Good job on this quick turnaround 👏

**Comment by ishanm120** [comment]
I am using Chrome browser 76 on Android Mobile.
switchTo().window(newWindow) is not working.

Chromedriver used: 76.0.3809.68
Chrome Browser: 76
Appium version: v1.14.0



Now which Appium version will support this??
