### ISSUE TITLE
No targets found, when switching from app to browser on iOS

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium#13171]
## The problem

Sometimes you need to automate the following flow

1. login to a native app
2. after login you need to pay something and a link in the app opens a browser
3. the browser needs to be used to pay
4. after payment the browser is opening the app again
5. the payment in the app is processed

This is currently failing at step 3 with the following error `Encountered internal error running command: Error: No targets found, unable to communicate with device`

## Environment

* Appium version (or git revision) that exhibits the issue: `1.14.0`
* ~Last Appium version that did not exhibit the issue (if applicable):~
* Desktop OS/version used to run Appium: OSX Mojave
* Node.js version (unless using Appium.app|exe): `v10.15.2`
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 12.2
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

The logs can be found [here](https://gist.github.com/wswebcreation/5b22664a459b28b6693ee14c0d5e67f1)

## Code To Reproduce Issue [ Good To Have ]

I'm using WebdriverIO and the Sauce Labs sample app to execute the test, the test executes the following steps:

```js
// config
config.capabilities = [
    {
        // The defaults you need to have in your config
        deviceName: 'iPhone X',
        platformName: 'iOS',
        platformVersion: '12.2',
        orientation: 'PORTRAIT',
        // The path to the app, see https://github.com/saucelabs/sample-app-mobile/releases
        app: join(process.cwd(), './apps/iOS.Simulator.SauceLabs.Mobile.Sample.app.2.1.0.app.zip'),
        // Read the reset strategies very well, they differ per platform, see
        // http://appium.io/docs/en/writing-running-appium/other/reset-strategies/
        noReset: true,
        newCommandTimeout: 240,
        maxInstances: 1,
        fullContextList: true,
    },
];
```

```js
describe('Appium', () => {
    it('should be able to work with the browser that is opened with the app', () => {
        // Login to the app and verify that it succeeded
        LoginScreen.waitForIsShown();
        LoginScreen.signIn(LOGIN_USERS.STANDARD);
        InventoryListScreen.waitForIsShown();

        expect(InventoryListScreen.isShown()).toEqual(true);

        // Open the menu and click on the about screen
        Menu.open();
        Menu.openAbout();

        let webviewID = {};

        driver.waitUntil(() => {
            const contexts = Context.getCurrentContexts();
            webviewID = contexts
                .filter(context => {
                    console.log('filter context = ', context)
                    return !context.id.includes('NATIVE_APP')
                })
                .find(context => {
                    console.log('some context = ', context)
                    return context.url.includes('https://saucelabs.com/')
                });
            return webviewID || false;
        }, DEFAULT_TIMEOUT);

        driver.switchContext(webviewID.id);

        expect(browser.getTitle()).toEqual('Cross Browser Testing, Selenium Testing, Mobile Testing | Sauce Labs');
    })
})
```

**Comment by umutuzgur** [comment]
@wswebcreation Could you try with appium@beta?

**Comment by mykola-mokhnach** [comment]
This probably happens because Safari browser itself is not really a web view. Maybe, if you quit the session when browser is onscreen and start a new one targeted for the browser with noReset cap set to true then it is going to work as expected.

**Comment by mykola-mokhnach** [comment]
Or maybe this is just a bug, which has been already fixed in appium@beta like @umutuzgur said ;)

**Comment by wswebcreation** [comment]
@mykola-mokhnach and @umutuzgur 

Tried to run it with the latest beta (`1.14.0-beta.2`), but it is still not working.

@mykola-mokhnach 
Regarding your remark, do you mean this flow will not work, and we first need switch sessions to be able to automate it in 1 flow?

**Comment by imurchie** [comment]
@wswebcreation Is this app available to us somewhere?

**Comment by mykola-mokhnach** [comment]
> Tried to run it with the latest beta (1.14.0-beta.2), but it is still not working.

Please provide the new log

>  to be able to automate it in 1 flow

I don't think we could automate this scenario in a single flow with such approach

**Comment by wswebcreation** [comment]
@imurchie 

The app can be downloaded here, take this version, that's the one I'm using

https://github.com/saucelabs/sample-app-mobile/releases/download/2.1.0/iOS.Simulator.SauceLabs.Mobile.Sample.app.2.1.0.zip

@mykola-mokhnach 
You can find the logs [here](https://gist.github.com/wswebcreation/5b22664a459b28b6693ee14c0d5e67f1#file-appium-no-device-attached-L1452)

**Comment by imurchie** [comment]
@wswebcreation Can you try the latest beta of Appium, and add the `includeSafariInWebviews` capability (set to `true`) to your desired caps for the test?

**Comment by wswebcreation** [comment]
Retested this with Appium `1.15.0`-stable and it works like a charm, thanks for this!!
