### ISSUE TITLE
 NoSuchDriverError: A session is either terminated or not started

### ISSUE THREAD

**Issue by ania-s** [appium/appium#13217]
## The problem

When running tests with webdriverio & appium (appium-espresso-driver) on android I get the error: " NoSuchDriverError: A session is either terminated or not started" usually after the test execution is finished. It fails my test execution and no report is generated in case this error is seen.
Tests might pass but I still get the error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.14.2
* Desktop OS/version used to run Appium: MacOS Mojave
* Node.js version (unless using Appium.app|exe): v10.15.3
* Npm:  6.4.1
* Mobile platform/version under test: android 7
* Real device or emulator/simulator: Galaxy Tab S2

## Link to Appium logs

https://gist.github.com/ania-s/75b65e485db38e1db819bb9a91c1d7e7

**Comment by mykola-mokhnach** [comment]
> [35m[BaseDriver][39m Shutting down because we waited 60 seconds for a command

It looks like the session is deleted automatically due to timeout. All the next commands with the same session id fail with the error above, which is expected.

**Comment by ania-s** [comment]
> > �[35m[BaseDriver]�[39m Shutting down because we waited 60 seconds for a command
> 
> It looks like the session is deleted automatically due to timeout. All the next commands with the same session id fail with the error above, which is expected.

@mykola-mokhnach ok I see now that it comes from the log command that is somehow executed automatically after the tests are finished. How do I fix it or disable those logs? I see there are ["logcat","bugreport","server"] log types and I guess by default it tried to take them all. But I cannot find anywhere how to disable this or why it would fail/fix it.

**Comment by ania-s** [comment]
It looks that increasing newCommandTimeout fixes the issue for me. However, I would still like to know if there is a way to disable specific/all types of logs or maybe there is a better way to fix this issue I have?

**Comment by mykola-mokhnach** [comment]
Please use Appium Forum to ask questions. Here we discuss issues.

Closed as not an issue

**Comment by daipn1859** [comment]
@ania-s 
Could you find any way to disable them?

**Comment by ania-s** [comment]
@daipn1859 No, I didn't. I asked in the Appium Forum but no one replied.
@mykola-mokhnach Any hint on how to disable those logs?

**Comment by shivani-rana** [comment]
Hi,
I am still facing this issue : org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started

Dec 16, 2019 6:24:20 PM io.appium.java_client.remote.AppiumCommandExecutor$1 lambda$0
INFO: Detected dialect: W3C
org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'AMAC02X25KWJG5M', ip: 'fe80:0:0:0:141b:246c:c57c:f3ac%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_211'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {app: /Users/shivani.rana/eclipse..., autoGrantPermissions: true, automationName: XCUITest, browserName: , databaseEnabled: false, deviceName: iPad, fullReset: false, javascriptEnabled: true, locationContextEnabled: false, locationServicesAuthorized: true, networkConnectionEnabled: false, newCommandTimeout: 240000000, noReset: true, platform: MAC, platformName: MAC, platformVersion: 13.3, takesScreenshot: true, udid: XXX..., webStorageEnabled: false, xcodeOrgId: XXX, xcodeSigningId: iPhone Developer}
Session ID: a0e411cb-da8f-481b-90ee-d58df0f108b7

**Comment by distante** [comment]
I am having the exact same problem in my Ionic/Angular based project while testing in Android. My only test pass and after that an error happens:

log:
```
JSONWP (ae5c87f6)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[MJSONWP (ae5c87f6)]     at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:252:15)
[MJSONWP (ae5c87f6)]     at asyncHandler (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:432:15)
[MJSONWP (ae5c87f6)]     at Layer.handle [as handle_request] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[MJSONWP (ae5c87f6)]     at next (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:137:13)
[MJSONWP (ae5c87f6)]     at Route.dispatch (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\route.js:112:3)
[MJSONWP (ae5c87f6)]     at Layer.handle [as handle_request] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[MJSONWP (ae5c87f6)]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:281:22
[MJSONWP (ae5c87f6)]     at param (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:354:14)
[MJSONWP (ae5c87f6)]     at param (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[MJSONWP (ae5c87f6)]     at Function.process_params (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:410:3)
[MJSONWP (ae5c87f6)]     at next (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[MJSONWP (ae5c87f6)]     at logger (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\morgan\index.js:144:5)
[MJSONWP (ae5c87f6)]     at Layer.handle [as handle_request] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[MJSONWP (ae5c87f6)]     at trim_prefix (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:317:13)
[MJSONWP (ae5c87f6)]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:284:7
[MJSONWP (ae5c87f6)]     at Function.process_params (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:335:12)
[MJSONWP (ae5c87f6)]     at next (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\express\lib\router\index.js:275:10)
[MJSONWP (ae5c87f6)]     at C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\body-parser\lib\read.js:130:5
[MJSONWP (ae5c87f6)]     at invokeCallback (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\raw-body\index.js:224:16)
[MJSONWP (ae5c87f6)]     at done (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\raw-body\index.js:213:7)
[MJSONWP (ae5c87f6)]     at IncomingMessage.onEnd (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\raw-body\index.js:273:7)
[MJSONWP (ae5c87f6)]     at IncomingMessage.emit (events.js:182:13)
[MJSONWP (ae5c87f6)]     at endReadableNT (_stream_readable.js:1090:12)
[MJSONWP (ae5c87f6)]     at process._tickCallback (internal/process/next_tick.js:63:19)
[HTTP] <-- POST /wd/hub/session/ae5c87f6-fa49-4ab9-a141-5a1bf8d2baea/elements 404 3 ms - 131
[HTTP] 
[Chromedriver] Changed state to 'stopped'
[UiAutomator2] Deleting UiAutomator2 server session
[WD Proxy] Matched '/' to command name 'deleteSession'
[WD Proxy] Proxying [DELETE /] to [DELETE http://localhost:8200/wd/hub/session/465cfaa0-d5d4-4797-bf10-534a288fba1a] with no body
[WD Proxy] 404 - undefined
[WD Proxy] StatusCodeError: 404 - undefined
[WD Proxy]     at new StatusCodeError (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\request-promise-core\lib\errors.js:32:15)
[WD Proxy]     at Request.plumbing.callback (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:104:33)
[WD Proxy]     at Request.RP$callback [as _callback] (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:46:31)
[WD Proxy]     at Request.self.callback (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\request\request.js:185:22)
[WD Proxy]     at Request.emit (events.js:182:13)
[WD Proxy]     at Request. (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\request\request.js:1161:10)
[WD Proxy]     at Request.emit (events.js:182:13)
[WD Proxy]     at IncomingMessage. (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\request\request.js:1083:12)
[WD Proxy]     at Object.onceWrapper (events.js:273:13)
[WD Proxy]     at IncomingMessage.emit (events.js:187:15)
[WD Proxy]     at endReadableNT (_stream_readable.js:1090:12)
[WD Proxy]     at process._tickCallback (internal/process/next_tick.js:63:19)
[MJSONWP (ae5c87f6)] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
[MJSONWP (ae5c87f6)]     at doJwpProxy (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:490:13)
[HTTP] <-- POST /wd/hub/session/ae5c87f6-fa49-4ab9-a141-5a1bf8d2baea/url 500 919 ms - 274
```

npm output:

```
 new App
    √ should have the app name in the title




1 spec, 0 failures
Finished in 0.014 seconds

Executed 1 of 1 spec SUCCESS in 0.014 sec.
(node:15048) UnhandledPromiseRejectionWarning: WebDriverError: A session is either terminated or not started
    at Object.checkLegacyResponse (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
    at ElementArrayFinder.applyAction_ (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.<computed> [as getText] (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.<computed> [as getText] (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\protractor\built\element.js:831:22)
    at AppPage.getParagraphText (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\e2e\src\app.po.ts:51:32)
    at UserContext.<anonymous> (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\e2e\src\app.e2e-spec.ts:11:21)
    at C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\jasminewd2\index.js:112:25
    at new Promise (<anonymous>)
    at SimpleScheduler.promise (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\promise.js:2242:12)
    at schedulerExecute (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\jasminewd2\index.js:95:18)
    at C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\promise.js:2232:22
(node:15048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)   
(node:15048) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15048) UnhandledPromiseRejectionWarning: WebDriverError: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined 
    at Object.checkLegacyResponse (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\_SSD_DEV\ionic\ionic4_audiotrainer_update\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:15048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)   
[20:55:22] I/launcher - 0 instance(s) of WebDriver still running
[20:55:22] I/launcher -  #01 passed
```

**Comment by livisRepo** [comment]
I have faced the same issue. If anybody got a solution, please suggest to me.

**Comment by mraphael2101** [comment]
Same here. I am using appium version 1.20.2

**Comment by vsan6545** [comment]
Same here, i am getting same error. 

`[debug] [W3C (aff8acba)] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[debug] [W3C (aff8acba)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:243:15)
[debug] [W3C (aff8acba)]     at /usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
[debug] [W3C (aff8acba)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (aff8acba)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [W3C (aff8acba)]     at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [W3C (aff8acba)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (aff8acba)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [W3C (aff8acba)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
[debug] [W3C (aff8acba)]     at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
[debug] [W3C (aff8acba)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
[debug] [W3C (aff8acba)]     at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [W3C (aff8acba)]     at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [W3C (aff8acba)]     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [W3C (aff8acba)]     at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [W3C (aff8acba)]     at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [W3C (aff8acba)]     at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[HTTP] <-- POST /wd/hub/session/aff8acba-0edc-47c1-b03a-4e132a46d5c3/element 404 6 ms - 1886
[HTTP] `

**Comment by baselalali** [comment]
I have the same issue. Please reopen the ticket 
GET /wd/hub/session/b390c107-22ea-4dc6-bf57-b221d5bcb6d1/timeouts 404

**Comment by andvalsol** [comment]
I'm having the same issue.

**Comment by shinobi01** [comment]
Please increase the newCommandTimeout capability and try again. It solved my problem.

**Comment by kirans0406** [comment]
I am having the same issue please help me

**Comment by saravanan060694** [comment]
same issue to me also

**Comment by Karan-QA** [comment]
I am also facing same issue with appium 1.22.3-4 with webdriverIO. I also tried **newCommandTimeout: '100',** capability but issue still persists. If anyone got any solution please suggest. my email address is **karan51180@gmail.com** and whatapp no - +971-504280505

**Comment by synioe** [comment]
Same issue with me. I even can't run test script, please give me a hand.

**Comment by natanlbispo** [comment]
i have the same erro!

**Comment by Karan-QA** [comment]
> I am also facing same issue with appium 1.22.3-4 with webdriverIO. I also tried **newCommandTimeout: '100',** capability but issue still persists. If anyone got any solution please suggest. my email address is **[karan51180@gmail.com](mailto:karan51180@gmail.com)** and whatapp no - +971-504280505

Finally In my case, I found that while app launch thr was some restrictions implemented at backend by security team to block few calls if in a particular time frame these many requests are coming so i requested them to bypass my public ip and issue got resolved.

**Comment by rajeshbg-kr** [comment]
I am seeing this error as part of running regression tests in Github actions.

**Comment by norellanac** [comment]
Check your driver session timeout.
I faced a similar issue using `WebdriverIO`
so I fixed increasing `waitforTimeout` in WebdriverIO settings.

**Comment by DevBinogi** [comment]
[AppiumDriver@55a7] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started

**Comment by phatle1** [comment]
faced the issue, up/downgrade Appium and UIAutomator2 version was fixed the issue

Appium v2.0.0
uiautomator2@3.0.3

**Comment by jumaantony** [comment]
I am still getting the error when I start the appium server: Would you please reopen the Issue. This is a huge blocker

I am using Appium v2.11.

`
Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:309:15)
    at /usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:512:15
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
    at logger (/usr/local/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/usr/local/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:113:7)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12)`

**Comment by jumaantony** [comment]
A Quick Fix for this, Seems like I had stopped a test that was already running and appium must have cached the given test. I therefore had to clear my cache and restart my machine. This solved the issue.

**Comment by ziguiway** [comment]
> 对此的快速修复，似乎我已经停止了已经在运行的测试，并且 appium 必须缓存了给定的测试。因此，我不得不清除缓存并重新启动我的机器。这解决了问题。

在哪里清除缓存

**Comment by Sampson-2016** [comment]
> > 对此的快速修复，似乎我已经停止了已经在运行的测试，并且 appium 必须缓存了给定的测试。因此，我不得不清除缓存并重新启动我的机器。这解决了问题。
> 
> 在哪里清除缓存

how do you solve it
