### ISSUE TITLE
WebDriverAgent directory is not created after installing appium server 1.15

### ISSUE THREAD

**Issue by dbr13** [appium/appium#13297]
## The problem

After installing appium server 1.15 WebDriverAgent directory is not created at the /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/

## Environment

* Appium version (or git revision) that exhibits the issue: 1.15
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.14.6
* Node.js version (unless using Appium.app|exe): 12.10
* Npm or Yarn package manager: 6.11.3
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `sample-code` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Does this cause any problems? WDA has been moved to a separate npm module a while ago.

**Comment by imurchie** [comment]
If you run `npm ls -g appium-webdriver` you should be able to find where it is installed.

**Comment by dbr13** [comment]
$ npm ls -g appium-webdriver
/usr/local/lib
└── (empty)

**Comment by imurchie** [comment]
Ach! Sorry. It's `appium-webdriveragent`.
```
$ npm ls -g appium-webdriveragent                                                                ✔  10.16.0 ⬢  10:39:52
/Users/isaac/.nvm/versions/node/v10.16.0/lib
└─┬ appium@1.15.0
  ├── appium-webdriveragent@1.3.5
  └─┬ appium-xcuitest-driver@2.133.1
    └── appium-webdriveragent@1.3.5  deduped
```
```
$ npm ls -g appium-webdriveragent -j                                                             ✔  10.16.0 ⬢  10:40:15
{
  "dependencies": {
    "appium": {
      "version": "1.15.0",
      "from": "appium",
      "resolved": "https://registry.npmjs.org/appium/-/appium-1.15.0.tgz",
      "dependencies": {
        "appium-webdriveragent": {
          "version": "1.3.5",
          "from": "appium-webdriveragent@1.3.5",
          "resolved": "https://registry.npmjs.org/appium-webdriveragent/-/appium-webdriveragent-1.3.5.tgz"
        },
        "appium-xcuitest-driver": {
          "version": "2.133.1",
          "from": "appium-xcuitest-driver@2.133.1",
          "resolved": "https://registry.npmjs.org/appium-xcuitest-driver/-/appium-xcuitest-driver-2.133.1.tgz",
          "dependencies": {
            "appium-webdriveragent": {
              "version": "1.3.5",
              "from": "appium-webdriveragent@1.3.5",
              "resolved": "https://registry.npmjs.org/appium-webdriveragent/-/appium-webdriveragent-1.3.5.tgz"
            }
          }
        }
      }
    }
  }
}
```

**Comment by dbr13** [comment]
@imurchie 
Thanks

**Comment by surajsalunkhe** [comment]
You can find path here 
/Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent

**Comment by Sujatagp** [comment]
@dbr13 : Are you able to run test, even if the WebDriverAgent directory is placed at other folder?

**Comment by chetan31** [comment]
@dbr13 
I am also not able to find WebDriverAgent folder in Appium 1.15.1 version
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/

WebDriverAgent is not present 

@surajsalunkhe Please look for "Appium 1.15.1 version"

**Comment by chetan31** [comment]
It is solve 

Please look at the below link it helped me a lot thanks 
https://docs.katalon.com/katalon-studio/docs/installing-webdriveragent-for-ios-devices.html

@dbr13 @surajsalunkhe

**Comment by IcyW** [comment]
> @dbr13
> I am also not able to find WebDriverAgent folder in Appium 1.15.1 version
> /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent
> 
> WebDriverAgent is not present
> 
> @surajsalunkhe Please look for "Appium 1.15.1 version"

I cannot find WebDriverAgent folder in Appium v1.17.0 either.

**Comment by imurchie** [comment]
There is no `WebDriverAgent` folder anymore. The folder is `appium-webdriveragent` and is wherever in your install the `appium-webdriveragent` package was installed. It will have the contents structured like https://github.com/appium/WebDriverAgent

**Comment by surajsalunkhe** [comment]
It is present with appium-webdriveragent name. Checked on Appium Version 1.15.1
@chetan31  and @IcyW .

**Comment by JananiBalakrishnan** [comment]
@imurchie

I see the appium-webdriveragent path : 

/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent

And appium path : 

/usr/local/bin/appium

And this command gives this location : npm ls -g appium-webdriveragent
/usr/local/lib
└─┬ appium@1.17.1
  └─┬ appium-xcuitest-driver@3.22.0
    └── appium-webdriveragent@2.14.2

Should we run this command : (https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md
)
mkdir -p Resources/WebDriverAgent.bundle
    ./Scripts/bootstrap.sh -d

**Comment by karanvirkour22** [comment]
I was able to find Webdriveragent in this path
/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent

**Comment by livisRepo** [comment]
I cannot find WebDriverAgent folder in Appium v1.19.0 either.

**Comment by koralaa** [comment]
Hi, I have the same issue in 1.21.0. appium-webdriveragent folder is not automatically creating when install Appium. After Appium install via CLI or Appium Desktop, the appium-webdriveragent folder structure is missing. Can someone help pls? 

Appium desktop - Checked the location /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent
and folder is not there.

via npm - checked the folder /opt/homebrew/lib/node_modules/appium/node_modules/appium-xcuitest-driver
can't see appium-webdriveragent folder.

This is what I see when type 'npm ls -g appium-webdriveragent'
qa.testing@QAs-Mac-mini ~ % npm ls -g appium-webdriveragent
/opt/homebrew/lib
└─┬ appium@1.21.0
  └─┬ appium-xcuitest-driver@3.43.0
    └── appium-webdriveragent@3.8.0

I have installed xcode 12.5 in mac.

**Comment by sarmadhu** [comment]
HI,
@koralaa is your issue resolved?. As i'm facing the same issue.

saran.madhu@techleads-Mac-mini ~ % npm ls -g appium-webdriveragent
/opt/homebrew/lib
└─┬ appium@1.21.0
  └─┬ appium-xcuitest-driver@3.43.0
    └── appium-webdriveragent@3.8.0

**Comment by chetan31** [comment]
@sarmadhu kindly refer the appium website it may help you
They are continuously changing the configuration

**Comment by koralaa** [comment]
@sarmadhu : Certificate was missing in Xcode. Problem was solved after adding the 'Signing certificate in Xcode'. Check whether you have done that step. Xcode ->Preferences -> Go to Accounts tab -> Make sure Apple id is set up -> Then click on Manage Certificates -> If nothing is there, then add certificate here (there's a plus icon in the window to add certificate).  Then uninstall and reinstall Appium solved the problem.

**Comment by nyeinnyeinsanaung** [comment]
> @dbr13 : Are you able to run test, even if the WebDriverAgent directory is placed at other folder? I am stuck at this point as I couldn't find WebDriverAgent, please help

... need to move ?

**Comment by nyeinnyeinsanaung** [comment]
> HI, @koralaa is your issue resolved?. As i'm facing the same issue.
> 
> saran.madhu@techleads-Mac-mini ~ % npm ls -g appium-webdriveragent /opt/homebrew/lib └─┬ appium@1.21.0 └─┬ appium-xcuitest-driver@3.43.0 └── appium-webdriveragent@3.8.0

having the same issue.. resolved ??>

**Comment by nyeinnyeinsanaung** [comment]
> HI, @koralaa is your issue resolved?. As i'm facing the same issue.
> 
> saran.madhu@techleads-Mac-mini ~ % npm ls -g appium-webdriveragent /opt/homebrew/lib └─┬ appium@1.21.0 └─┬ appium-xcuitest-driver@3.43.0 └── appium-webdriveragent@3.8.0

find it here : /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent

**Comment by koralaa** [comment]
Hi, @nyeinnyeinsanaung, Yeah. This issue was resolved now. As I remember the issue was missing certificate in xcode. Problem was solved after adding the 'Signing certificate in Xcode'. Check whether you have done that step. Xcode ->Preferences -> Go to Accounts tab -> Make sure Apple id is set up -> Then click on Manage Certificates -> If nothing is there, then add certificate here (there's a plus icon in the window to add certificate). Then uninstall and reinstall Appium solved the problem. Then you should see appium-wedriver agent folder in /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/

**Comment by Preetha0102** [comment]
Hi @koralaa, I am still facing the same issue. Tried after adding account and certification as mentioned in the above comment. Also uninstalled and installed the Appium. 
 
cd /Applications/Appium.app/Contents/Resources/app/node_modules/appium-webdriveragent results "No such file or directory"

**Comment by Param3159** [comment]
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent

**Comment by nyonnguyen** [comment]
If you are finding the appium-webdriveragent after install the xcuitest driver, try this path `~/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

**Comment by MikePendo** [comment]
```
 npm ls -g appium-webdriveragent
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
/usr/local/lib
└── (empty)
```

**Comment by lamhuynhit** [comment]
> If you are finding the appium-webdriveragent after install the xcuitest driver, try this path `~/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

Thanks @nyonnguyen It worked with me.
