### ISSUE TITLE
iOS : Unable to open the mobile/Emulator screen using inspector session of Appium Desktop

### ISSUE THREAD

**Issue by vaibhav107raj** [appium/appium#14002]
## The problem

The app is getting launched successfully on both Emulator as well as on the real Device. However, the "Inspector Session" of Appium Desktop version 1.13 to identify locators is not able to open the mobile or emulator screen and thus this is creating an issue to know the identifiers.

## Environment

* Appium version : 1.13.0
* Desktop OS/version used to run Appium: mac os 10.15
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Both

## Link to Appium logs

[https://gist.github.com/vaibhav107raj/10c4b0ae446e1d1b06b35db3a2d549c8]

## Code To Reproduce Issue [ Good To Have ]

[https://gist.github.com/vaibhav107raj/cda5cc7b7d2a11914be3f50492e91829](url)

**Comment by KazuCocoa** [comment]
Please update your appium version to the latest one.
The cause looks Xcode 11 issue which has been resolved in a newer version

**Comment by vaibhav107raj** [comment]
I will check. Thanks for your suggestion and quick turn-around.

**Comment by vaibhav107raj** [comment]
@KazuCocoa  Thanks for your suggestion! it worked after upgrading to Appium 1.15 from 1.13 . However, my automation now also works on Appium 1.15.0 for emulator.
But still an issue is there with real device. The app get properly installed and opened using Appium 1.13.0 VERSION. However with Appium 1.15.0 , i am getting WebDriverAgentRunner issue.
Can you please suggest.

**Comment by KazuCocoa** [comment]
Could you share the full log?

**Comment by vaibhav107raj** [comment]
@KazuCocoa  @mykola-mokhnach   

Below is the log using Appium 1.13 and real device , where app is getting installed and is able to open on the device by itself.

Logs : [https://gist.github.com/vaibhav107raj/b169f85a0c20b4f1dfb7edf557d577fc](url)


Below is the log using Appium 1.15 and real device [same device used for appium 1.13 successfull run and same code], where app is getting installed . But the app is not able to open on the device by itself due to web driver agent runner issue.

Logs: [https://gist.github.com/vaibhav107raj/84592b0673bc915a8ee7d3b06cf8e282](url)

**Comment by mykola-mokhnach** [comment]
> [Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.

This is a signing issue and we cannot help much there. Make sure the bundle is signed properly and is deployable from the command line

**Comment by vaibhav107raj** [comment]
@mykola-mokhnach  : I want to highlight this only , the same code and same device is working well with appium 1.13 version [logs already shared]. However , the same device and code configuration is not working with appium 1.15 desktop version and give this signing certificate issue. 

Let me know, if this would be a signing certificate issue, should it work on appium version 1.13 ?

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot help much there. We have a detailed [tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) on how to sign the WDA bundle. If this does not work then try to ask at Appium forum. Although this is definitely not a server issue.

**Comment by vaibhav107raj** [comment]
i tried using Appium 1.13  version today , just to open the  app and it ran perfectly by opening the app on emulator and launching WDA runner on emulator 

logs :  [Appium 1.13 run logs ](https://gist.github.com/vaibhav107raj/c9db64a4a06f3d840555461f16e4b9d4)

however, the logs also highlights as below 👍 

[Xcode] Testing started on 'TRIAL'
[Xcode] 
[Xcode] Failing tests:
[Xcode] 	WebDriverAgentRunner:
[Xcode] 		-[UITestingUITests testRunner]
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Shutting down because we waited 60 seconds for a command



NOTE: The issue regarding WDA still exists while using Appium 1.15 .

Can you please suggest ?

**Comment by vaibhav107raj** [comment]
i just tried to install appium-proxy and now it is working well on appium 1.15 as well. I tried an automation script as well.
Seems all good.

Thanks a lot for your kind suggestions!
