### ISSUE TITLE
Getting pop up "This site is attempting to open a pop-up window" while automation script execution

### ISSUE THREAD

**Issue by ishanm120** [appium/appium#14091]
## The problem
Getting pop up "This site is attempting to open a pop-up window" while automation script execution

## Environment

* Appium Version :1.16
* iOS Device : iphone X
* OS Version : 12.1.1

## Details

I am running my Selenium automation script on real iOS device. When it comes to click on a particular button , it gives pop up: 
 "This site is attempting to open a pop-up window" 

>Action on that button should result into a new window opened, but blocked due to this pop up.
>Executed the same code on Android device, It's working fine.

![IMG_9306](https://user-images.githubusercontent.com/29706721/77146949-3f7b7580-6ab2-11ea-9757-b9ace54dbe0a.jpg)

## Link to Appium logs

https://gist.github.com/ishanm120/931086560a1c7a9a6fb335b140d50009

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/8582

**Comment by imurchie** [comment]
Have you tried adding the `safariAllowPopups` capability, set to `true`?

**Comment by imurchie** [comment]
Otherwise yes, this is a problem. I can try out a fix.

**Comment by ishanm120** [comment]
> you tried adding the `safariAllowPopups` capability, set to `true`?

It didn't work for me.

**Comment by imurchie** [comment]
I have a locally-working fix here: https://github.com/appium/appium-xcuitest-driver/pull/1185

**Comment by ishanm120** [comment]
> I have a locally-working fix here: [appium/appium-xcuitest-driver#1185](https://github.com/appium/appium-xcuitest-driver/pull/1185)

When it will be available for us ?

**Comment by imurchie** [comment]
It is available in the latest beta, as part of `appium-xcuitest-driver@3.19.0`.

**Comment by ishanm120** [comment]
@imurchie 
getting issue while installing latest appium beta version
<img width="567" alt="Screenshot 2020-04-01 at 11 50 03 AM" src="https://user-images.githubusercontent.com/29706721/78131140-3090ad80-7438-11ea-820e-d9fa330d523e.png">

**Comment by imurchie** [comment]
The warning is innocuous. Please provide the full output of the install command, including the command you are running. Information on your system would be useful, too.

**Comment by ishanm120** [comment]
> The warning is innocuous. Please provide the full output of the install command, including the command you are running. Information on your system would be useful, too.

It worked today, and that pop up issue is also resolved.
Thanks.
I hope this is resolved for other OS versions as well like 12.4 , Right??

**Comment by imurchie** [comment]
It should be resolved for _all_ versions that use Xcuitest.

**Comment by ishanm120** [comment]
Issue still persists with appium beta version: v1.17.1-beta.0
iOS OS : 12.1.1
Device: iPhone X
Mac OS: Mojave 10.14.4 (18E227)
XCode: 10.3

**Comment by ishanm120** [comment]
@imurchie 
Can you please check above issue.

**Comment by ishanm120** [comment]
@imurchie 
Tried with iOS mobile version 12.4:
It just clicks on the button but nothing happens after that.

**Comment by ishanm120** [comment]
@imurchie 
My remote debugger is:
/usr/local/lib
└─┬ appium@1.17.1-beta.0
  ├─┬ appium-ios-driver@4.6.2
  │ └── appium-remote-debugger@4.5.0 
  └─┬ appium-xcuitest-driver@3.20.0
    └── appium-remote-debugger@8.9.0

**Comment by imurchie** [comment]
I don't know what "It just clicks on the button but nothing happens after that" means. Which button? What is expected to happen?

**Comment by ishanm120** [comment]
> I don't know what "It just clicks on the button but nothing happens after that" means. Which button? What is expected to happen?

@imurchie 
When i click on button, it should open a new browser window but nothing happens on screen after click.


Please check https://github.com/appium/appium/issues/14157

hope you will get idea. and if still need some info, please do let me know

**Comment by imurchie** [comment]
For the problem actually at hand in this issue, does it still happen? There's so much cruft in here I'm not sure.

**Comment by hemank5** [comment]
> It should be resolved for _all_ versions that use Xcuitest.

I am having the same issue with Protractor using WebDriver and is happening when I am running automation gives the same message pop-up.
Without automation I don't see pop up If I do manually I am able to open the new page on new tab/window.

Currently on Appium Desktop Version 1.15.1
iOS Simulator - iPhone 11 (13.3)

**Comment by mohan-pattar** [comment]
@ishanm120 
With the capability "caps.setCapability("nativeWebTap", true);" and the OS version "1.16.0" worked for me.
But "nativeWebTap" capability interrupting other click action (not all).
