### ISSUE TITLE
Unable to find WEBVIEW context with iOS 13

### ISSUE THREAD

**Issue by jerislee** [appium/appium#14178]
## The problem

I am unable to find WEBVIEW context using driver.contexts. It only shows ['NATIVE_APP'] using get_all_context.  I have no problem getting and switching to WEBVIEW using Appium 1.13 with iOS 12.0. However, recently I want to upgrade to iOS 13 using the latest Appium. I keep running into this problem. 

## Environment

* Appium version: 1.17.1-beta.0
* Last Appium version that did not exhibit the issue: 1.13 + iOS 12.0
* Desktop OS/version used to run Appium: MacOS 10.15.4 / Xcode 11.4
* Node.js version: 13.12.0
* Npm or Yarn package manager: 6.14.4
* Mobile platform/version: iOS 13.0 
* Real device or emulator/simulator: iOS **Simulator** 
* Appium CLI or Appium.app|exe: Appium CLI
```
/usr/local/lib
└─┬ appium@1.17.1-beta.0
  ├─┬ appium-ios-driver@4.6.2
  │ └── appium-remote-debugger@4.5.0 
  └─┬ appium-xcuitest-driver@3.21.1
    └── appium-remote-debugger@8.9.0 
```

## Details
There is no issue with Appium 1.13 + iOS 12.0 switching webview in my app. I don't know what I did wrong in this setup. I have already update everything to the latest version as I can. 
It seems like appium can not find any WEBVIEW at all, since I keeps getting only [NATIVE_APP].
I have tried:
1. Uninstall and reinstall appium CLI both 1.17.1 and beta
2. Add Capabilities like: 'fullContextList': True
I am still unable to resolve this issue.

## Link to Appium logs
GIST Link : https://gist.github.com/jerislee/54e9cf4fc7c944673b779b10b6de64dc
Part of important log :
https://gist.github.com/jerislee/82c6722b6e9157dbabcf0e43e6378107

## Code To Reproduce Issue [ Good To Have ]
```
    def switch_context(self, context):  # context = 'WEBVIEW' / 'NATIVE_APP'
        time.sleep(10)
        self.logger.info("[Automation Log]: before switch " + self.driver.current_context)

        while context not in self.driver.current_context:
            if context == "WEBVIEW":
                self.logger.info(self.driver.contexts)
                try:
                    self.driver.switch_to.context(self.driver.contexts[1])
                except BaseException as msg:
                    self.logger.info(msg)
            elif context == "NATIVE_APP":
                self.driver.switch_to.context(context)
```

**Comment by mykola-mokhnach** [comment]
- Is the web view visible in Safari remote debugger?
- Have you tried to add a timer for web view detection?

**Comment by imurchie** [comment]
You can also try using the `webviewConnectTimeout` capability (set to a number above 0). iOS 13 can take a bit of time to report the apps the Web Inspector can see.

**Comment by jerislee** [comment]
Thanks for your reply.
- Is the web view visible in Safari remote debugger?
Yes, I can see the web view in safari remote debugger and its whole html source code.
- Have you tried to add a timer for web view detection?
I am not sure what you meant here. Do you mean `webviewConnectTimeout`? 
I have tried set it to 10000 and loops for more than 100+ times. I also added "time.sleep(10)" before get_all_context.  It's still not working...

**Comment by mykola-mokhnach** [comment]
> I am not sure what you meant here. Do you mean webviewConnectTimeout?
I have tried set it to 10000 and loops for more than 100+ times. I also added "time.sleep(10)" before get_all_context. It's still not working...

Please provide the log from this attempt. Also, please enable `safariLogAllCommunication` cap for this log

**Comment by jerislee** [comment]
> > I am not sure what you meant here. Do you mean webviewConnectTimeout?
> > I have tried set it to 10000 and loops for more than 100+ times. I also added "time.sleep(10)" before get_all_context. It's still not working...
> 
> Please provide the log from this attempt. Also, please enable `safariLogAllCommunication` cap for this log

Hi, here is the log file for the action. The get all context action is at the end of the log that repeated many times.
https://gist.github.com/jerislee/ab771b721b40a7bb9a71512025e8f88c

**Comment by shibupanda** [comment]
@mykola-mokhnach I am getting the same issue with same scenario.
Am able to get Webview in Safari browser when I checked this manually but yes of course the DOM element are not able to loaded.
Tried Appium version: 1.15.1 and 1.17.0

**Comment by KazuCocoa** [comment]
A note. `Empty page dictionary received`?

```
[debug] [RemoteDebugger] Attempting app 'PID:1142'
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to app 'PID:1142' (id: 27): 'connectToApp'
[debug] [ios-device] Sending message to Web Inspector:
[debug] [ios-device] {
[debug] [ios-device]   "__argument": {
[debug] [ios-device]     "WIRConnectionIdentifierKey": "bde157c0-8b8a-44b5-933c-5cfde1d49000",
[debug] [ios-device]     "WIRApplicationIdentifierKey": "PID:1142"
[debug] [ios-device]   },
[debug] [ios-device]   "__selector": "_rpc_forwardGetListing:"
[debug] [ios-device] }
[debug] [ios-device] Received message from Web Inspector:
[debug] [ios-device] {
[debug] [ios-device]   "__argument": {
[debug] [ios-device]     "WIRApplicationIdentifierKey": "PID:1142",
[debug] [ios-device]     "WIRListingKey": {}
[debug] [ios-device]   },
[debug] [ios-device]   "__selector": "_rpc_applicationSentListing:"
[debug] [ios-device] }
[debug] [RemoteDebugger] Received response from send (id: 27): '["PID:1142",{}]'
[debug] [RemoteDebugger] Sending to Web Inspector took 6ms
[debug] [RemoteDebugger] Empty page dictionary received
[debug] [RemoteDebugger] Error checking application: 'Empty page dictionary received'. Retrying connection
[debug] [RemoteDebugger] Current applications available:
```

**Comment by KazuCocoa** [comment]
I tried Xcode 11.4 and iOS 13.4 simulator with https://github.com/appium/ios-uicatalog app.
https://gist.github.com/KazuCocoa/f6d10b1603c99a467396516aabedb488 is the log to call the contexts endpoint.
When `Empty page dictionary received` happened, no WebView element. (expected)
but when Appium could get page dictionary, it returned WebView context.

If someone had an app which can reproduce and share with, it is appreciated...
(The best is it can reproduce in our test app though...)

**Comment by lvninety** [comment]
Environment : xcode 11.4,  iphone 11(iOS 13.3), Appium 1.17.0, Hybrid app with WKWebView
The issue seems like reproducing to me. 
I tried to inspect elements under the webview with appium inspector, 
but the XCUIElementTypeWebView class is not appear on element hierarchy in the inspector.

However, it is possible to inspect elements in webview by id(accessibility id).
There was no change to my app. (it worked with ios11 + Appium 1.16.0)

**Comment by KazuCocoa** [comment]
Did you try to get web view contexts a couple of times?

> 1.17.0 https://github.com/appium/appium/releases
> Add waitForWebviewMs option to mobile:getContexts endpoint, to block for a period while waiting for webview report (appium/appium-xcuitest-driver#1135)

`webviewConnectTimeout` is capability name

**Comment by jerislee** [comment]
@KazuCocoa 
I've done some tests. I had tried to use a new app only has wkWebveiw that show the same page. In the same environment, appium works perfectly. It can find and switch to webview context.
Therefore, I think it would probably relate to some things that I implement in my iOS App that caused Appium is unable to find webview context. 
The strange thing is that I can find webview using appium 1.13 + iOS 12.0 with the same app, but I can't find it using appium 1.17 + iOS 13.4. 

Does anyone know what might cause that appium is unable to find webview?

**Comment by KazuCocoa** [comment]
The behaviour depends on the device under test since Appium handles WebView stuff via the iOS's web inspector. It means if iOS 13.4's web inspector (safari) has an issue or changes something, it will also affect Appium. So, it is appreciated to compare the same iOS version.

Appium has been moved the communication tool from [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) to Appium's native socket communication in Appium 1.15.0 so that Appium can catch up with the latest iOS version as soon as possible.

If your target page could not find via safari's web inspector, Appium cannot find it at least.
If can find it, need to dig the case more in https://github.com/appium/appium-remote-debugger
https://github.com/appium/appium-ios-driver/blob/04caae028e874eb07faf31c80e309c33a14541cc/lib/commands/context.js#L158 is the entrypoint...

**Comment by lvninety** [comment]
@KazuCocoa 
I tried to use `webviewConnectTimeout` cap, but it's still not working.
The issue was reproduced with appium 1.17.0 + iOS 12.

However, I found a log, '[debug][XCUITest] No web frames found.'
So I inspect webview on safari debugger, there were two webviews in one app.
I don't know why there is 'about:blank' webview(?) 

That might be root cause of the issue in my opinion.. :(
is it issues of safari? or my app?
Attach screenshot.

![blank](https://user-images.githubusercontent.com/41889344/80688844-65f7ec00-8b07-11ea-931e-1a7434f6dd72.png)

**Comment by KazuCocoa** [comment]
Thanks, hm..

Can you get contexts with `fullContextList` capability?
It may include all data including the URLs. `about:blank` also be there, I think.

Btw, I found `ignoreAboutBlankUrl` capability which handles the `about:blank` if Appium includes it as contexts or not.
https://github.com/search?q=org%3Aappium+ignoreAboutBlankUrl&type=Code

**Comment by lvninety** [comment]
The log returns NATIVE_APP only.
`[debug] [W3C (62e784cf)] Responding to client with driver.getContexts() result: [{"id":"NATIVE_APP"}]`
As you said, I tried to set `ignoreAboutBlankUrl` to true, but it's not working.

A strange thing is that is able to search `XCUIElementTypeWebview` elements by classname.
there is a lot of `XCUIElementTypeWebview` elements in a page. (over 10 elements... it depends on page)

And it is able to interact in Webviews with element's accessibility ID.
Below images are element tree and a result of 'XCUIElementTypeWebview' class on Appium inspector.

![tree](https://user-images.githubusercontent.com/41889344/80716433-986b0e80-8b32-11ea-8b58-e05f1454c840.png)
![webview search](https://user-images.githubusercontent.com/41889344/80716444-9c972c00-8b32-11ea-9957-0825615f1ab6.png)

**Comment by KazuCocoa** [comment]
Thanks.

`XCUIElementTypeWebview` stuff was if it asked elements for XCTest framework (NATIVE_APP) or Safari inspector (WebView/Safari), I think. Appium Desktop is designed to interact with native app context, but not with WebView context.

I need to find time to dive deeply more, but I'm afraid Appium team has no good app which can reproduce this... 
https://github.com/appium/ios-uicatalog

**Comment by lvninety** [comment]
Actually, It was possible to interact with webview elements in native app context in Appium Desktop inspector before, even if I used distribution deployment ipa file. Webview was also appeared as native context in the inspector. So that I can automate ios app without development deployment. (if there is no problem with accessibility problems)

For example, there were many ways to find an element in same page like below.
If I find an element, in webview context by xpath:
` wd.findElement("//div[@class = 'accessibility id for an element']")`
If I find same element in native context:
`wd.findElmentByAccessiblityId("accessibility id for an element")` 
`wd.findelementByClasschain("**/XCUIElementTypeCell['name == accessibility id for an element']")`

But now, webview interaction is working in native context only, but elements in webview are not appeared in appium desktop. even if i tried to use dev deployment. 
I'm gonna do more tests, after that I'll give you more details if i can. :(
I hope there would be any clues.

**Comment by KazuCocoa** [comment]
Below is note for me.

---

Available contexts are items which has `pageArray` with `safariLogAllCommunication`. `"Waiting for data."` is waiting for the result as Promise like `{"promise":{"isFulfilled":false,"isRejected":false}}"`. So, I wondered no response returned from remote debugger or something wrong.

```
[debug] [RemoteDebugger]     Application: "PID:16521"
[debug] [RemoteDebugger]         id: "PID:16521"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "Safari"
[debug] [RemoteDebugger]         bundleId: "com.apple.mobilesafari"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: false
[debug] [RemoteDebugger]         isAutomationEnabled: true
[debug] [RemoteDebugger]         pageArray:
[debug] [RemoteDebugger]           - id: 1
[debug] [RemoteDebugger]             title: "Appium/welcome"
[debug] [RemoteDebugger]             url: "http://0.0.0.0:4723/welcome"
[debug] [RemoteDebugger]             isKey: false
[debug] [RemoteDebugger]     Application: "PID:16527"
[debug] [RemoteDebugger]         id: "PID:16527"
[debug] [RemoteDebugger]         isProxy: false
[debug] [RemoteDebugger]         name: "com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         bundleId: "process-com.apple.WebKit.WebContent"
[debug] [RemoteDebugger]         hostId: undefined
[debug] [RemoteDebugger]         isActive: false
[debug] [RemoteDebugger]         isAutomationEnabled: "Unknown"
[debug] [RemoteDebugger]         pageArray: "Waiting for data."
```

**Comment by KazuCocoa** [comment]
Could you collect a log with `safariLogAllCommunicationHexDump` and share `/contexts` command part like https://gist.github.com/KazuCocoa/226edbac7b409e865d97586b599acc9b ?
I guess appium could not get proper response by safari...

**Comment by martinfrancois** [comment]
I'm having the same issue, when I'm calling `mobile: getContexts` the only response I get is `[{"id":"NATIVE_APP"}]` when in Safari.

I'm using an iPad Pro 11" with iOS 13.3.1 with Appium 1.17.1 and the following caps:
```json
{
  "automationName": "XCUITest",
  "deviceName": "iPad Pro",
  "platformName": "iOS",
  "platformVersion": "13.3.1",
  "orientation": "PORTRAIT",
  "maxInstances": 1,
  "printPageSourceOnFindFailure": true,
  "app": "com.apple.mobilesafari",
  "noReset": true,
  "newCommandTimeout": 240,
  "autoDismissAlerts": false,
  "udid": "auto",
  "xcodeOrgId": "XXXXXXXXXX",
  "xcodeSigningId": "iPhone Developer",
  "includeSafariInWebviews": true,
  "fullContextList": true,
  "webviewConnectTimeout": 10000,
  "ignoreAboutBlankUrl": false,
  "safariLogAllCommunication": true
}
```

This resulted in the following log in Appium: https://gist.github.com/martinfrancois/edd7a86b609ae9114fa68c9d5e126173

Sensitive info was replaced by a sequence of `X` characters in both the caps and the log.

Hope that helps in resolving it!

**Comment by KazuCocoa** [comment]
Thanks.

In general, Appium gets the response by Web Inspector like below (It has `Data received` text)
```
[debug] [RemoteDebugger] Sending to Web Inspector took 13ms
[debug] [RemoteDebugger] Waiting up to 5000ms for applications to be reported
[debug] [ios-device] Data received, length: 785
[debug] [ios-device] 00 00 02 80 62 70 6C 69 73 74 30 30 D2 01 02 03 1D 5A 5F ....bplist00.....Z_
[debug] [ios-device] 5F 61 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F _argumentZ__selecto
```

But your attached one printed as below.

```
[debug] [35m[ios-device][39m 00 00 01 01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 ...................
[debug] [35m[ios-device][39m 00 00 00 00 00 00 00 00 0A                               .........
[debug] [35m[RemoteDebugger][39m Sending to Web Inspector took 8ms
[debug] [35m[RemoteDebugger][39m Waiting up to 10000ms for applications to be reported
[debug] [35m[RemoteDebugger][39m Timed out waiting for applications to be reported
[debug] [35m[RemoteDebugger][39m Sending connection key request
[debug] [35m[RemoteDebugger][39m Sending '_rpc_reportIdentifier:' message (id: 1): 'setConnectionKey'
[debug] [35m[ios-device][39m Data sent, length: 174
```

As Appium, it meant no response by the WebInspector. `webviewConnectTimeout` capability may help to get the response... But if this does not help, timeout/interval around https://github.com/appium/appium-remote-debugger/blob/002f0b951258ab10c87beae6ff113b27d2b6369e/lib/mixins/connect.js#L13 potentially help... (Or Web Inspector by Safari itself had issues)

**Comment by martinfrancois** [comment]
@KazuCocoa I think you must've missed that my capabilities already include `webviewConnectTimeout`.

I also just tried different values for `SELECT_APP_RETRY_SLEEP_MS` as you suggested and repeated the same process as above.
Unfortunately all of the tries resulted in the same: `[{"id":"NATIVE_APP"}]`
The different values I tried were: `100`, `1000`, `2000`, `5000` and `10000`. As I mentioned all of them produced the same result except with `10000` the socket would hang up, but maybe that's kind of expected...

Any other ideas?

**Comment by KazuCocoa** [comment]
How about increasing `APP_CONNECT_INTERVAL_MS`?

>  the socket would hang up

hm...
Can the webview communicate with Safari Web Inspector?
I mean _connect with Web Inspector_ -> _inspect the element etc via it_

If it could, perhaps we need to find another way to communicate with WebViews
https://github.com/appium/appium-remote-debugger#safaris-version-of-the-webkit-api

**Comment by martinfrancois** [comment]
> Can the webview communicate with Safari Web Inspector?
> I mean _connect with Web Inspector_ -> _inspect the element etc via it_

This was it! I checked using the Safari Web Inspector and it would also keep stuck at "Connecting...", I then had a look on the iPad in `Settings -> Safari -> Advanced` and just noticed that I did have `Remote Automation` enabled, but `Web Inspector` was **not** enabled. As soon as I **enabled** that, `getContexts` worked:
```
[{"id":"NATIVE_APP"},{"bundleId":"com.apple.mobilesafari","id":"WEBVIEW_470.1","title":"Apple","url":"https://www.apple.com/"}]
```
Maybe @jerislee, @shibupanda and @lvninety can try again with my capabilities from https://github.com/appium/appium/issues/14178#issuecomment-626181289 and check if the setting from before was set correctly?

Thanks a lot @KazuCocoa !

**Comment by shibupanda** [comment]
@martinfrancois 
Thanks for the update. Yes in my case Web Inspector is enabled as it is a prerequisites.
But yes in my case the issue was different. I fixed it by resign it manually using codesign.

**Comment by jimarasim** [comment]
Still having issues with this. Here is a repro using Appium Desktop - Get All Contexts  

ios 13.4
appium 1.17.1-1

Capabilities:
{
  "app": "/Users/jarasim/Downloads/installed/apps/CostcoDebug_1693.zip",
  "platformName": "iOS",
  "platformVersion": "13.4",
  "deviceName": "iPhone 11 Pro Max 13.4",
  "processArguments": "{\"env\":{\"ENV_OVERRIDE\":\"QA\"}}",
  "automationName": "XCUITest",
  "webviewConnectTimeout": "90000",
  "safariLogAllCommunication": true
}

Appium Logs:
[appium-server-logs.txt](https://github.com/appium/appium/files/4870872/appium-server-logs.txt)

Safari Inspector:
<img width="825" alt="Screen Shot 2020-07-03 at 10 52 06 AM" src="https://user-images.githubusercontent.com/2319417/86490228-8288ee00-bd1b-11ea-8105-97065c47c03f.png">

Noticed "JSContext" in Safari inspector keeps appearing/disappearing while there's no change in the loaded page.

**Comment by heychirag** [comment]
Any update on this?

**Comment by heychirag** [comment]
Any update in this? Can't seem to get it working even with `webviewConnectTimeout`.

**Comment by sisihi** [comment]
`        for(int i = 0; i<30; i++) {
            Thread.sleep(1000);
            Set<String> contextNames = driver.getContextHandles();
            for (String contextName : contextNames) {
                System.out.println(contextName); //prints out something like NATIVE_APP \n WEBVIEW_1driver.quit();
            }
        }` 

works for me.

**Comment by facusantillo** [comment]
Still reproducing this issue, any workarounds?

**Comment by arctouch-thiagowerner** [comment]
Facing same issue.

**Comment by burkedavid** [comment]
facing same problem with the following caps:

`    platformName: 'iOS',
    'appium:platformVersion': '14.0',
    'appium:deviceName': 'iPhone 8 Plus Simulator',
    'appium:app': '<redacted>',
    'appium:fullContextList': true,
    'appium:webviewConnectTimeout': '60000',
    'sauce:options': {
      appiumVersion: '1.21.0',
    },`

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/16481#issuecomment-1058149339 may help.
So far, we observed webview appears after some interactions to the view. (this is by Safari/Web Inspector thing)

**Comment by burkedavid** [comment]
Thanks for the reply @KazuCocoa unfortunately any elements in webview are never found.  When I do a console.log for getContext() I do see a webview ID however but switching to this doesnt find any webview elements either.  The script runs on Android successfully  



`2022-03-09T18:47:44.905Z INFO webdriver: COMMAND getContexts()
[0-0] 2022-03-09T18:47:44.905Z INFO webdriver: [GET] https://ondemand.us-west-1.saucelabs.com/wd/hub/session/507efb55a3234ca91r8fa4ef27d901e8/contexts
[0-0] 2022-03-09T18:47:45.977Z INFO webdriver: RESULT [
[0-0]   { id: 'NATIVE_APP' },
[0-0]   {
[0-0]     url: 'https://company/Logon.jsp?mobileToken=true',
[0-0]     bundleId: 'com.mobile',
[0-0]     id: 'WEBVIEW_3689.4',
[0-0]     title: 'MyCompany'
[0-0]   }
[0-0] ]
[0-0] wdioContexts1 : [
[0-0]   { id: 'NATIVE_APP' },
[0-0]   {
[0-0]     url: 'ttps://company/Logon.jsp?mobileToken=true',
[0-0]     bundleId: 'com.mobile',
[0-0]     id: 'WEBVIEW_3689.4',
[0-0]     title: 'MyCompany'
[0-0]   }
[0-0] ]


`

**Comment by jlipps** [comment]
@burkedavid did you confirm you were able to inspect the webview from desktop safari?

**Comment by burkedavid** [comment]
@jlipps webview from desktop in safari is fine just nothing in iOS simulator.

**Comment by KazuCocoa** [comment]
what the result of https://github.com/appium/appium-xcuitest-driver#mobile-getcontexts ?
Could you share the appium log as well?

**Comment by jlipps** [comment]
> webview from desktop in safari is fine just nothing in iOS simulator.

@burkedavid what do you mean? you mean you don't see any ability to inspect the webview context for the simulator in desktop safari? that would be the problem, then.

**Comment by cdubwisdom** [comment]
Has anyone found a work around or a fix for this. It's been three years since the opening of this thread and I can currently facing the same problem. I just want to able to verify that the weblink in my app is redirecting to the correct url

**Comment by outi5** [comment]
@cdubwisdom, I've been working on this same issue recently and still haven't been able to get it to work, but I did find this discussion, which might be helpful: [https://github.com/appium/appium/issues/16481](url). If you figure out a solution, please post it!

**Comment by cdubwisdom** [comment]
@outi5, apparently it's an issue with iOS 16+. SafariViews are not debuggable. Most likely it will require a fix on the iOS side or an update to the xcuitest driver.

Also that link didn't go anywhere

**Comment by outi5** [comment]
Thanks, @cdubwisdom! 
I wonder why I'm able to see the WEBVIEW when using Appium Inspector? I've been beating my head against the wall on this one for quite a few days now. I'll give it a try on a different iOS version and then wait on Apple ;)

(I updated the link. Thanks for letting me know.)

**Comment by jankdc** [comment]
For iOS 16.4 or above, for anyone who lost their minds trying to debug this, there was a recent change where you need to set `.isInspectable` on the `WKWebView` object to `true` (see https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/).

**Comment by jlipps** [comment]
@KazuCocoa @mykola-mokhnach can we add this to our xcuitest webview docs so we can reference?

**Comment by jlipps** [comment]
thanks for the reference @jankdc !

**Comment by KazuCocoa** [comment]
addressed -> https://github.com/appium/appium-xcuitest-driver/pull/1721

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
