### ISSUE TITLE
Cannot switch driver context to Web

### ISSUE THREAD

**Issue by LoveleenSaini** [appium/appium#14332]
## The problem

After upgrading Xcode from version 10 to 11 Appium is unable to switch driver context from native to web. It throws this error in server logs: 
> Error checking application: 'Empty page dictionary received'. Retrying connection

## Environment

* Appium version: **1.17.1**
* Desktop OS/version used to run Appium: **macOS Catalina. Version 10.15.3**
* Node.js version: **12.16.1**
* Npm package manager: **Npm 6.13.4**
* Mobile platform/version under test: **iOS 13.3**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **CLI**

## Link to Appium logs

[Appium Server Logs](https://gist.github.com/LoveleenSaini/195902c635fdb45e10c5d5a4b978fe96)

## Code To Reproduce Issue
```
public static void changeDriverContextToWeb(AppiumDriver<MobileElement> driver, int timeoutSeconds) throws Exception {
    Logging.info("Waiting for WEB context to be available. Timeout - " + timeoutSeconds);
    boolean switched = false;
    DateTime timeout = DateTime.now().plusSeconds(timeoutSeconds);
    java.util.Set<String> contextNames;
    do {
        Logging.info("Getting all currently available driver contexts.");
        contextNames = RunCukesTest.driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println(contextName);
            // On Android available contexts list can include 'WEBVIEW_chrome' but that is not the one to switch to.
            if (contextName.contains("WEB") && !contextName.contains("chrome")) {
                Logging.info("WEB context is available. Switching to it.");
                driver.context(contextName);
                Logging.info("Switched to WEB context.");
                switched = true;
                break;
            }
        }
        if (DateTime.now().isAfter(timeout)) {
            throw new Exception("Timeout trying to switch driver context to WEB.");
        }
    } while (!switched);
}
```

**Comment by mykola-mokhnach** [comment]
Is the web view visible to Safari remote debugger?

**Comment by LoveleenSaini** [comment]
Yes it is. The web view and all elements inside it are visible/accessible.

**Comment by KazuCocoa** [comment]
What about web inspector preference?
https://github.com/appium/appium/issues/14178#issuecomment-626294777

It is appreciated to attach the log with `safariLogAllCommunication` capability.

**Comment by LoveleenSaini** [comment]
[Server logs with safariLogAllCommunication enabled](https://gist.github.com/LoveleenSaini/75b1a4ea1b223c579a217748a799be6a)

On simulator:
Settings -> Safari -> Advanced -> **Remote Automation is enabled**
Settings -> Safari -> Advanced -> **Web Inspector is NOT PRESENT**
Settings -> Developer -> **Enable UI Automation is enabled**

**Comment by KazuCocoa** [comment]
Thanks.
Hm... The web inspector did not return the page information as below.
```
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to app 'PID:55712' (id: 21): 'connectToApp'
[debug] [ios-device] Sending message to Web Inspector:
[debug] [ios-device] {
[debug] [ios-device]   "__argument": {
[debug] [ios-device]     "WIRConnectionIdentifierKey": "d7fab8b9-14e4-4557-adcd-e626402483c6",
[debug] [ios-device]     "WIRApplicationIdentifierKey": "PID:55712"
[debug] [ios-device]   },
[debug] [ios-device]   "__selector": "_rpc_forwardGetListing:"
[debug] [ios-device] }
[debug] [ios-device] Received message from Web Inspector:
[debug] [ios-device] {
[debug] [ios-device]   "__argument": {
[debug] [ios-device]     "WIRApplicationIdentifierKey": "PID:55712",
[debug] [ios-device]     "WIRListingKey": {}
[debug] [ios-device]   },
[debug] [ios-device]   "__selector": "_rpc_applicationSentListing:"
[debug] [ios-device] }
[debug] [RemoteDebugger] Received response from send (id: 21): '["PID:55712",{}]'
[debug] [RemoteDebugger] Sending to Web Inspector took 7ms
[debug] [RemoteDebugger] Empty page dictionary received
```

Could you try out newer Xcode version like 11.4?
I wondered if it depended on Xcode and base simulator image.

**Comment by LoveleenSaini** [comment]
Issue exists after upgrading Xcode to 11.4.

[Logs with Xcode 11.4](https://gist.github.com/LoveleenSaini/8fa1563cb73f280e46b52ba36c52842c)

**Comment by KazuCocoa** [comment]
What about the log with Xcode 11.x and iOS 12.x?


Btw, our test app https://github.com/appium/ios-uicatalog worked well in Xcode 11 and 10 and some iOS version combinations.

**Comment by LoveleenSaini** [comment]
I will try to check that combination today.

**Comment by Jiurong-Yang** [comment]
Our team is seeing the same issue, but I believe it's working for IOS 12 but not for IOS 13.

**Comment by LoveleenSaini** [comment]
@KazuCocoa it worked fine with Xcode 11.4.1 and simulator on iOS 12.2.

[Logs with Xcode 11.4 and iOS 12.2](https://gist.github.com/LoveleenSaini/dddd6db7d294d2dd5215fe502e8e28e7)

Seems like the issue is with Xcode 11.x and iOS 13.x.

**Comment by KazuCocoa** [comment]
Okay. Yeah, the below line was expected.

```
[debug] [XCUITest] Remote debugger notified us of a new page listing: {"appIdKey":"64750","pageArray":[{"id":3,"title":"Seat Picker","url":"file:///Users/loveleen.saini/Library/Developer/CoreSimulator/Devices/38FD662F-6998-4AA9-B227-E0E4963604AC/data/Containers/Bundle/Application/B0318AC2-57C6-4245-8497-93DBCBBD1321/xxxxx.app/Frameworks/SeatMapWidgetWrapper.framework/seat-picker.html","isKey":false}]}
```

Perhaps iOS 13's remote debugger has an issue or they introduced a new way.
https://github.com/WebKit/webkit/tree/master/Source/JavaScriptCore/inspector/protocol
(I guess they has an issue since if the old way was deprecated, something error should have happened...)

**Comment by LoveleenSaini** [comment]
I was thinking for using Xcode 11.x and iOS 12.x for now but this combination has its own issues. For example, element.clear() function doesn't work.

**Comment by Vinocm** [comment]
Even I'm facing similar issue, any update on this?

**Comment by Vinocm** [comment]
After increasing the max frame size for web inspector service this issue got resolved for me.
increased MAX_FRAME_SIZE = 90000000;
https://github.com/appium/appium-ios-device/pull/50/commits/891ac29cfcbe4fba4be3709646a114da26cdcc16

**Comment by Vinocm** [comment]
Even after updating frame-size faced issue in another machine, Today tried by adding this capability and the issue is resolved now

desiredCapabilities.setCapability("webviewConnectTimeout", 90000);

**Comment by jimarasim** [comment]
I'm still having issues finding a WEBVIEW on certain pages, even with the webviewConnectTimeout.

**Comment by tejasv02** [comment]
I am having similar issues. When I load NATIVE page, I see only native context, then I navigate to WEBVIEW (I see NATIVE context and sometimes WEBVIEW contexts are also displayed) when I navigate back to native context it shows 3-4 contexts (1 NATIVE, 2-3 WEBVIEW contexts)

**Comment by anupreetrayat** [comment]
do we have any update on this??

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
