### ISSUE TITLE
bug: <title>Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by HristinaStankovic** [appium/appium#20633]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading macOS to the latest version, I was forced to upgrade Xcode to version 16.0 from the App Store. I used the latest version of Appium server, 2.11.5 (although I also tried many older versions, almost all 2.X versions, and received the same result), as well as the XCUITest driver version 5.16.1 (I tried installing lower versions of this driver in combination with Appium as well). After attempting to run an automated test on iPhone devices (iOS 15.x and iOS 17.x), I received the following error as soon as the perform() method, which is part of the TouchAction class in Java, was executed: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance xxx.

The complete method I used for the swipe action is: public void swipeMethodName(double startPercentage, double endPercentage, double anchorPercentage) {
    Dimension size = Base.driver.manage().window().getSize();
    int anchor = (int) (size.height * anchorPercentage);
    int startPoint = (int) (size.width * startPercentage);
    int endPoint = (int) (size.width * endPercentage);
    new TouchAction(Base.driver)
            .press(point(startPoint, anchor))
            .waitAction(waitOptions(ofMillis(3000)))
            .moveTo(point(endPoint, anchor))
            .release().perform();
}

Do someone know what is the solution to this problem? I tried adding the capabilities "appium:waitForQuiescence", false as well as "appium:shouldWaitForQuiescence", true (I changed the values true/false, tried every combination, but it didn’t work).

As an addition to what I wrote - the same error appears in the Appium logs when I try to run the Appium Inspector, and it causes an infinite loop; the Inspector does not display the application at all. I have tried several of the latest versions of the Appium Inspector from the repository: https://github.com/appium/appium-inspector/releases.

### Expected Behavior

Method perform(), which is part of the TouchAction class in Java, should be executed without any problems. 

### Minimal Reproducible Example

Step failed
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance xxx.xxx.xxx.xxx
Build info: version: 'xxx.xxx.xxx.xxx', revision: 'xxx.xxx.xxx.xxx', time: '2018-11-14T08:17:03'
Step failed
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance.

Build info: version: 'xxx.xxx.xxx.xxx', revision: 'xxx.xxx.xxx.xxx', time: '2018-11-14T08:17:03'
System info: host: 'MacBook-Pro.', ip: xxx.xxx.xxx.xxx, os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '15.0', java.version: '17.0.7'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: xxx.xxx.xxx.xxx..., automationName: XCUITest, browserName: , bundleId: xxx.xxx.xxx.xxx...., databaseEnabled: false, derivedDataPath: xxx.xxx.xxx.xxx..., deviceName: iPhone, javascriptEnabled: true, locationContextEnabled: false, locationServicesAuthorized: true, locationServicesEnabled: true, networkConnectionEnabled: false, newCommandTimeout: 240, noReset: true, platform: MAC, platformName: iOS, platformVersion: 17.6.1, shouldTerminateApp: true, takesScreenshot: true, udid: xxx.xxx.xxx.xxx, useNewWDA: true, webStorageEnabled: false}
Session ID: xxx.xxx.xxx.xxx
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)  
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)  
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)  
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)  
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)  
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)  
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)  
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)  
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)  
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)  
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)  
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)  
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)  
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)  
at io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:41)  
at io.appium.java_client.TouchAction.perform(TouchAction.java:187)  
at xxx.xxx.xxx.xxx.Action.ClassName.clickByPercentage(ClassName.java:1306)  
at xxx.xxx.xxx.xxx.Action.ClassName.hideKeyboard(ClassName.java:2928)  
at xxx.xxx.xxx.xxxTest.Steps.hideKeyboard(Steps.java:153)  
at ✽.Hide keyboard(file:xxx.xxx.xxx.xxx/Smoke.feature:62)

### Environment

- Operating system:
- Appium server version (almost all from 2.0.0 to the latest 2.11.5):
- Appium driver(s) and their version(s) (uiautomator2@2.29.4 [installed (npm)], xcuitest versions - tried from 4.12.0 to 5.16.1 [installed (npm)]):
- Appium plugin(s) and their version(s) (None):
- Node.js version (v21.7.1):
- `npm` version (10.5.0):
- Last component(s) version which did _not_ exhibit the problem: Mac OS Sonoma 14, Xcode version 15.2, appium v.2.5.4, uiautomator2@2.29.4 [installed (npm)], xcuitest@5.16.1 [installed (npm)]
- Real device or emulator/simulator: real devices

**Comment by HristinaStankovic** [comment]
As an addition to what I wrote, which I omitted - the same error appears in the Appium logs when I try to run the Appium Inspector, and it causes an infinite loop; the Inspector does not display the application at all. I have tried several of the latest versions of the Appium Inspector from the repository: https://github.com/appium/appium-inspector/releases.

**Comment by itkhanz** [comment]
Which version of Appium Java Client are you using? Please update to latest Appium Java Client and use W3C Sequences to construct cross platform gestures or use driver sepcific gestures. Touch Action is no longer supported in latest Appium Java Client.
See
https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md

https://github.com/appium/java-client/blob/master/docs/v8-to-v9-migration-guide.md

**Comment by HristinaStankovic** [comment]
> Which version of Appium Java Client are you using? Please update to latest Appium Java Client and use W3C Sequences to construct cross platform gestures or use driver sepcific gestures. Touch Action is no longer supported in latest Appium Java Client. See https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md
> 
> https://github.com/appium/java-client/blob/master/docs/v8-to-v9-migration-guide.md

I am using 7.3.0 appium java client version.

**Comment by itkhanz** [comment]
> > Which version of Appium Java Client are you using? Please update to latest Appium Java Client and use W3C Sequences to construct cross platform gestures or use driver sepcific gestures. Touch Action is no longer supported in latest Appium Java Client. See https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md
> > https://github.com/appium/java-client/blob/master/docs/v8-to-v9-migration-guide.md
> 
> I am using 7.3.0 appium java client version, Selenium 3. Which version should I upgrade to, if at all? Currently, it would be useful to my team and me if we can use TouchAction for a while longer, I'm interested to know if that is possible in any way?

Try upgrading first to V8 (8.6.0) where you have the possibility to still use TouchAction, and then make a progressive update to v9 (9.3.0)
See compatibility matrix of Appium and Selenium 
https://github.com/appium/java-client?tab=readme-ov-file#compatibility-matrix

Also try installing the latest available Appium Inspector and run it together with latest Apoium server to see if you still have this problem.

I am not exactly sure whether this error has something to do with TouchAcion but you would certainly want to upgrade to latest bindings sooner to avoid any issues.

**Comment by KazuCocoa** [comment]
`Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]` error has been fixed in https://github.com/appium/appium/issues/20239. Please use XCUITest driver 7.24.15+ for Xcode 16 beta 5+ environment.
https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/

**Comment by mykola-mokhnach** [comment]
Closed as duplicate

**Comment by HristinaStankovic** [comment]
> > > Which version of Appium Java Client are you using? Please update to latest Appium Java Client and use W3C Sequences to construct cross platform gestures or use driver sepcific gestures. Touch Action is no longer supported in latest Appium Java Client. See https://github.com/appium/java-client/blob/master/docs/v7-to-v8-migration-guide.md
> > > https://github.com/appium/java-client/blob/master/docs/v8-to-v9-migration-guide.md
> > 
> > 
> > I am using 7.3.0 appium java client version, Selenium 3. Which version should I upgrade to, if at all? Currently, it would be useful to my team and me if we can use TouchAction for a while longer, I'm interested to know if that is possible in any way?
> 
> Try upgrading first to V8 (8.6.0) where you have the possibility to still use TouchAction, and then make a progressive update to v9 (9.3.0) See compatibility matrix of Appium and Selenium https://github.com/appium/java-client?tab=readme-ov-file#compatibility-matrix
> 
> Also try installing the latest available Appium Inspector and run it together with latest Apoium server to see if you still have this problem.
> 
> I am not exactly sure whether this error has something to do with TouchAcion but you would certainly want to upgrade to latest bindings sooner to avoid any issues.

I still have the same problem with Appium Inspector, despite that I've installed the lattest version of appium - 2.11.5, the lattest version of appium inspector for Mac - Appium-Inspector-2024.9.1-mac-arm64.dmg, and the lattest version of xcuitest driver - xcuitest@7.27.0 [installed (npm)]. The error log is shown below: 

[xxxxxxxxxxx][XCUITestDriver@959a] Got response with status 200: {"value":{"width":xxxxxxxxxxx,"height"xxxxxxxxxxx},"sessionId":"xxxxxxxxxxx"}
[xxxxxxxxxxx][XCUITestDriver@959a] Responding to client with driver.getWindowRect() result: {"width":xxxxxxxxxxx,"height":xxxxxxxxxxx"x":0,"y":0}
[xxxxxxxxxxx][HTTP] <-- GET /wd/hub/session/xxxxxxxxxxx/window/rect 200 173 ms - 48 
[xxxxxxxxxxx][HTTP] --> GET /wd/hub/session/xxxxxxxxxxx/source {}
[xxxxxxxxxxx][XCUITestDriver@959a] Calling AppiumDriver.getPageSource() with args: ["xxxxxxxxxxx"]
[xxxxxxxxxxx][XCUITestDriver@959a] Executing command 'getPageSource'
[xxxxxxxxxxx][XCUITestDriver@959a] Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
[xxxxxxxxxxx][XCUITestDriver@959a] Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://xxxxxxxxxxx/session/xxxxxxxxxxx/source?format=xml&scope=AppiumAUT] with no body
[xxxxxxxxxxx][XCUITestDriver@959a] Got response with status 500: {"value":{"error":"unknown error","message":"-[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance xxxxxxxxxxx","traceback":"(\n\t0   CoreFoundation xxxxxxxxxxx objc_exception_throw + 60\n\t2   CoreFoundation  xxxxxxxxxxx CoreFoundation                      xxxxxxxxxxx xxxxxxxxxxx  CoreFoundation                      xxxxxxxxxxx_CF_forwarding_prep_0 + 96\n\t5   WebDriverAgentLib                   xxxxxxxxxxx[XCUIElement(FBUtilities) fb_waitUntilStableWithTimeout:] xxxxxxxxxxx   WebDriverAgentLib                   xxxxxxxxxxx +[FBXPath writeXmlWithRootElement:indexPath:elementStore:includedAttributes:writer:] + xxxxxxxxxxx WebDriverAgentLib                   xxxxxxxxxxx
[xxxxxxxxxxx][W3C] Matched W3C error code 'unknown error' to UnknownError
[xxxxxxxxxxx][XCUITestDriver@959a] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance xxxxxxxxxxx
    at errorFromW3CJsonCode (/Users/xxxxxxxxxxx/node_modules/appium-xcuitest-driver/node_modules/@appium/xxxxxxxxxxx/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/xxxxxxxxxxx/node_modules/appium-xcuitest-driver/node_modules/@appium/xxxxxxxxxxx/errors.js:981:14)
    at JWProxy.command (/Users/xxxxxxxxxxx/node_modules/appium-xcuitest-driver/node_modules/@appium/xxxxxxxxxxx/proxy.js:348:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at XCUITestDriver.proxyCommand (/Users/xxxxxxxxxxx/node_modules/appium-xcuitest-driver/xxxxxxxxxxx/proxy-helper.js:103:35)
    at XCUITestDriver.mobileGetSource (/Users/xxxxxxxxxxx/node_modules/appium-xcuitest-driver/xxxxxxxxxxx/source.js:50:35)
    at XCUITestDriver.getPageSource (/Users/xxxxxxxxxxx/node_modules/appium-xcuitest-driver/xxxxxxxxxxx/source.js:25:9)
[xxxxxxxxxxx][HTTP] <-- GET /wd/hub/session/xxxxxxxxxxx/source 500 37 ms - 1429 
[xxxxxxxxxxx][HTTP] --> GET /wd/hub/session/xxxxxxxxxxx/timeouts {}
[xxxxxxxxxxx][XCUITestDriver@959a] Calling AppiumDriver.getTimeouts() with args: ["xxxxxxxxxxx"]
[xxxxxxxxxxx][XCUITestDriver@959a] Executing command 'getTimeouts'

**Comment by KazuCocoa** [comment]
Perhaps the device has old WDA. Please try out uninstalling WDA/clearing xcodebuild cache once.
