### ISSUE TITLE
Defect: RemoveApp() do not close the LogCat.

### ISSUE THREAD

**Issue by EthanJiang** [appium/appium#3977]
The RemoveApp() need to close the logCat!.

Test Step:
1. [Start Install&Launch the apk.]
2. RemoveAPP.
3. Install app again
3. Launch App.

But if we do a CloseApp action before RemoveApp, the test will pass.

Error message:
 Responding to client with error: {"status":1,"value":{"message":"Unable to launch the app: Error: Trying to start logcat capture but it's already started!"},"sessionId":"87f3fe28-2669-4b53-a2d4-16b36bed7eb5"}

**Comment by pawanonline85** [comment]
Hi Jonahss,

Any update on this issue (Trying to start logcat capture but it's already started). Is it fixed in Appium 1.3.7?

Thanks,
Pawan

**Comment by Jonahss** [comment]
Doesn't look like it yet sorry. This issue still needs to get scheduled into a milestone.

**Comment by applepluot** [comment]
Is there a workaround for this issue?

**Comment by divyanshugarg** [comment]
You can launch main/root activity using 'startActivity(String appPackage, String appActivity,
			String appWaitPackage, String appWaitActivity)' method till it fix.
