### ISSUE TITLE
appium directory issue

### ISSUE THREAD

**Issue by tarunHub** [appium/appium#4245]
> Starting Node Server
> info: Welcome to Appium v1.2.4 (REV 71584425ecf777349e3215f0f18e71e7782acfb6)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium"}
> info: Console LogLevel: debug
> info: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"C:\\Users\\Tarun Gupta\\workspace1\\androidAcco\\app\\acco.apk","appPackage":"com.accoservice.cico","appActivity":"com.accoes.MainActivity","platformVersion":"4.4","browserName":"","platformName":"Android","deviceName":"6DV4R4EU4SZDR4AQ"}}[39m
> info: [debug] Using local app from desired caps: C:\Users\Tarun Gupta\workspace1\androidAcco\app\acco.apk
> info: [debug] Creating new appium session 6781207a-7e0f-43ad-bd14-37d3fa07452a
> info: Starting android appium
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> error: Unhandled error: Error: ENOENT, no such file or directory 'C:\AndroidSDK\sdk\tools;C:\AndroidSDK\sdk\platform-tools;C:\AndroidSDK\sdk\build-tools;\build-tools'
>     at Object.fs.readdirSync (fs.js:654:18)
>     at exports.getDirectories (C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\helpers.js:98:18)
>     at ADB.checkSdkBinaryPresent (C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:84:25)
>     at ADB.checkAdbPresent (C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:121:8)
>     at null.<anonymous> (C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\lib\devices\android\android-common.js:323:30)
>     at C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\async\lib\async.js:610:21
>     at C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\async\lib\async.js:249:17
>     at iterate (C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\async\lib\async.js:149:13)
>     at C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\async\lib\async.js:160:25
>     at C:\AppiumForWindows-1.2.4.1\Appium\node_modules\appium\node_modules\async\lib\async.js:251:21 context: [POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\Tarun Gupta\\workspace1\\androidAcco\\app\\acco.apk","appPackage":"com.accoservice.cico","appActivity":"com.accoes.MainActivity","platformVersion":"4.4","brow]

**Comment by balajig18** [comment]
Im also facing same issue......

**Comment by 0x1mason** [comment]
Where is your Android SDk installed? Here is the error:

error: Unhandled error: Error: ENOENT, no such file or directory
'C:\AndroidSDK\
sdk\tools;C:\AndroidSDK\sdk\platform-tools;C:\AndroidSDK\sdk\build-tools;\build-
tools'

Is ANDROID_HOME set? Have you tried adding C:\AndroidSDK\sdk  to your PATH?

**Comment by tarunHub** [comment]
my issue is resolved....
u should give full path in environment variable....no need to create android_home
eg 
my path : C:\AndroidSDK\sdk\tools;C:\AndroidSDK\sdk\platform-tools;C:\AndroidSDK\sdk\build-tools\17.0.0;

**Comment by g-one** [comment]
That's good but Eric meant also meant the same,either you can set
 ANDROID_HOME directly to the PATH variable or you can create a separate
ANDROID_HOME System variable and set the SDK path value.

Then set that variable=ANDROID_HOME to the PATH variable.

Thanks,
Jeevan

**Comment by tarunHub** [comment]
error: Unhandled error: Error: ENOENT, no such file or directory 'D:\Android\Android-Sdk;\build-tools'
I was getting the same error.
i know we need to set android_home. but stll i was getting the same error, that why i set the path in environment variable.
In addition i set the full path to device device api level.
for example :
If your device is at api level 17 or 4.2.2
C:\AndroidSDK\sdk\build-tools\17.0.0;

**Comment by 0x1mason** [comment]
IIUC, this is resolved.  Please let me know if it is otherwise.

**Comment by vikramvi** [comment]
correct way of setting ANDROID_HOME & related folder paths under it

https://gist.github.com/patrickhammond/4ddbe49a67e5eb1b9c03

**Comment by Srihari88** [comment]
Hello Mate,

I've set the same path to my environment variable section but still getting the same error. 

My Environment variable path
C:\Users\Sree\AppData\Local\Android\sdk\tools;C:\Users\Sree\AppData\Local\Android\sdk\platform-tools;C:\Users\Sree\AppData\Local\Android\sdk\build-tools\23.0.3;

After running my Appium server getting the error below.

 info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_101
> error: Unhandled error: Error: ENOENT, no such file or directory 'C:\Users\Sree\AppData\Local\Android\sdk;\build-tools'
>     at Object.fs.readdirSync (fs.js:654:18)
>     at exports.getDirectories (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\helpers.js:100:18)
>     at [object Object].ADB.checkSdkBinaryPresent (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:97:25)
>     at [object Object].ADB.checkAdbPresent (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:134:8)
>     at Function.ADB.createADB (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:73:7)
>     at [object Object].androidCommon.initAdb (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:1083:9)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:607:21
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:246:17
>     at iterate (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:146:13)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:157:25
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:248:21
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:612:34
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:1077:12)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:1064:12)
>     at ChildProcess.exithandler (child_process.js:635:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Socket.<anonymous> (child_process.js:956:11)
>     at Socket.EventEmitter.emit (events.js:95:17)
>     at Pipe.close (net.js:465:12) context: [POST /wd/hub/session {"desiredCapabilities":{"appPackage":"io.selendroid.testapp","appActivity":".HomeScreenActivity","platformVersion":"6.0","browserName":"","platformName":"Android","deviceName":"SORS9LY54HEA4SFE"}}]
> info: [debug] Checking whether adb is present

**Comment by imurchie** [comment]
@Srihari88 What is `ANDROID_HOME` set to? It looks like you have a semicolon at the end of it.
