### ISSUE TITLE
 TouchAction is concatenating coordinates

### ISSUE THREAD

**Issue by markcorbyn** [appium/appium#4360]
It appears Appium is concatenating the coordinates provided to a TouchAction. I'm using Appium 1.3.4 and testing on iOS. I'm using I'm using the iOS Selenium driver but with my own TouchAction implementation.

The iOS client side code looks like:

```
SETouchAction *action = [[SETouchAction alloc] init];
[action longPressAtX:123 y:98];
[action moveToX:456 y:76];
[action moveToX:321 y:45];
[driver performTouchAction:action];
```

The debug logs are:

```
info: --> POST /wd/hub/session/e6ec94af-67f9-4573-85cb-7b26181d5253/touch/perform {"actions":[{"options":{"x":"123","y":"98"},"action":"longPress"},{"options":{"x":"456","y":"76"},"action":"moveTo"},{"options":{"x":"321","y":"45"},"action":"moveTo"}]}
info: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":\"123\",\"y\":\"98\"}],\"time\":0.2},{\"touch\":[{\"x\":\"456123\",\"y\":\"7698\"}],\"time\":0.4},{\"touch\":[{\"x\":\"321456123\",\"y\":\"457698\"}],\"time\":0.6000000000000001}])"
info: [debug] Sending command to instruments: target.touch([{"touch":[{"x":"123","y":"98"}],"time":0.2},{"touch":[{"x":"456123","y":"7698"}],"time":0.4},{"touch":[{"x":"321456123","y":"457698"}],"time":0.6000000000000001}])
info: [debug] [INST STDERR] 2015-01-08 14:19:52.788 ScriptAgent[79272:2a0f] Log written to /Users/mark/Library/Developer/CoreSimulator/Devices/9063BA05-841B-441C-ACCD-83ADD3A2A73C/data/Library/Logs/CrashReporter/UIALogs/ScriptError-2015-01-08-141952.plist
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Debug: Got new command 21 from instruments: target.touch([{"touch":[{"x":"123","y":"98"}],"time":0.2},{"touch":[{"x":"456123","y":"7698"}],"time":0.4},{"touch":[{"x":"321456123","y":"457698"}],"time":0.6000000000000001}])
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Debug: evaluating target.touch([{"touch":[{"x":"123","y":"98"}],"time":0.2},{"touch":[{"x":"456123","y":"7698"}],"time":0.4},{"touch":[{"x":"321456123","y":"457698"}],"time":0.6000000000000001}])
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Debug: target.touch(__NSCFArray)
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Debug: point is not within the bounds of the screen
info: [debug] Socket data received (70 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"point is not within the bounds of the screen"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"point is not within the bounds of the screen"},"sessionId":"e6ec94af-67f9-4573-85cb-7b26181d5253"}
info: <-- POST /wd/hub/session/e6ec94af-67f9-4573-85cb-7b26181d5253/touch/perform 500 1058.775 ms - 205 
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Error: VerboseError: point is not within the bounds of the screen
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Error: Error during eval: touch@[native code]
       eval code
eval@[native code]
startProcessing@file:///usr/local/lib/node_modules/appium/CB912F05-0DD6-4B31-8859-23E7F520812A/bootstrap-2e6b83239819fb8c.js:2663:30
bootstrap@file:///usr/local/lib/node_modules/appium/CB912F05-0DD6-4B31-8859-23E7F520812A/bootstrap-2e6b83239819fb8c.js:2729:31
global code@file:///usr/local/lib/node_modules/appium/CB912F05-0DD6-4B31-8859-23E7F520812A/bootstrap-2e6b83239819fb8c.js:2738:10
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Debug: responding with:
info: [debug] [INST] 2015-01-08 03:19:52 +0000 Debug: Running system command #22: /usr/local/Cellar/node/0.10.34/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"point is not within the bounds of the screen"}...
```

Are the parameters sent to /wd/hub/session/e6ec94af-67f9-4573-85cb-7b26181d5253/touch/perform correct?
If so, it appears Appium is concatenating the coordinates so that by the third command the coordinates are {"x":"321456123","y":"457698"} rather than {"x":"321","y":"45"}

Thanks

**Comment by jlipps** [comment]
It does look like there's an appium bug in there, however it also looks like your client is sending the x/y values as strings rather than integers; if you change that, is it a suitable workaround?

**Comment by markcorbyn** [comment]
@jlipps Thanks for looking into this.  There was indeed an issue client side which was converting numbers to strings.  I've changed this and the result it now as follows:
```
info: <-- POST /wd/hub/session/ebf331e3-5e94-478c-bff6-78673620ab78/element/7/click 200 1165.762 ms - 74 {"status":0,"value":"","sessionId":"ebf331e3-5e94-478c-bff6-78673620ab78"}
info: --> POST /wd/hub/session/ebf331e3-5e94-478c-bff6-78673620ab78/touch/perform {"actions":[{"options":{"x":123,"y":98},"action":"longPress"},{"options":{"x":456,"y":76},"action":"moveTo"},{"options":{"x":321,"y":45},"action":"moveTo"}]}
info: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":123,\"y\":98}],\"time\":0.2},{\"touch\":[{\"x\":579,\"y\":174}],\"time\":0.4},{\"touch\":[{\"x\":900,\"y\":219}],\"time\":0.6000000000000001}])"
info: [debug] Sending command to instruments: target.touch([{"touch":[{"x":123,"y":98}],"time":0.2},{"touch":[{"x":579,"y":174}],"time":0.4},{"touch":[{"x":900,"y":219}],"time":0.6000000000000001}])
info: [debug] [INST STDERR] 2015-01-09 09:04:08.510 ScriptAgent[84402:2a0f] Log written to /Users/mark/Library/Developer/CoreSimulator/Devices/9063BA05-841B-441C-ACCD-83ADD3A2A73C/data/Library/Logs/CrashReporter/UIALogs/ScriptError-2015-01-09-090408.plist
info: [debug] [INST] 2015-01-08 22:04:08 +0000 Debug: Got new command 21 from instruments: target.touch([{"touch":[{"x":123,"y":98}],"time":0.2},{"touch":[{"x":579,"y":174}],"time":0.4},{"touch":[{"x":900,"y":219}],"time":0.6000000000000001}])
info: [debug] [INST] 2015-01-08 22:04:08 +0000 Debug: evaluating target.touch([{"touch":[{"x":123,"y":98}],"time":0.2},{"touch":[{"x":579,"y":174}],"time":0.4},{"touch":[{"x":900,"y":219}],"time":0.6000000000000001}])
info: [debug] [INST] 2015-01-08 22:04:08 +0000 Debug: target.touch(__NSCFArray)
info: [debug] [INST] 2015-01-08 22:04:08 +0000 Debug: point is not within the bounds of the screen
info: [debug] Socket data received (70 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"point is not within the bounds of the screen"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"point is not within the bounds of the screen"},"sessionId":"ebf331e3-5e94-478c-bff6-78673620ab78"}
info: <-- POST /wd/hub/session/ebf331e3-5e94-478c-bff6-78673620ab78/touch/perform 500 1046.775 ms - 205 
info: [debug] [INST] 2015-01-08 22:04:08 +0000 Error: VerboseError: point is not within the bounds of the screen
info: [debug] [INST] 2015-01-08 22:04:08 +0000 Error: Error during eval: touch@[native code]
       eval code
```

It appears the Appium is still adding the current value to the previous one, but now that they're numbers it is using arithmetic rather than concatenation.  While I believe the "moveTo" spec expects the coordinates to be absolute x/y coordinates, I can work around this bug by treating it as "moveBy" instead and rather than sending:
```
SETouchAction *action = [[SETouchAction alloc] init];
[action longPressAtX:123 y:98];
[action moveToX:456 y:76];
[action moveToX:321 y:45];
[driver performTouchAction:action];
```
I can send:
```
SETouchAction *action = [[SETouchAction alloc] init];
[action longPressAtX:123 y:98];
[action moveToX:333 y:-22];   // x:456 - 123, y:76 - 98
[action moveToX:-135 y:-31];   // x:321 - 456, y:45 - 76
[driver performTouchAction:action];
```
which replicates the same scenario.

**Comment by bootstraponline** [comment]
I think this has to do with the values being treated as an offset instead of a distinct point. A few people have encountered the same problem in the past. I don't know if it's a bug in appium or just how the touch actions are expected to work.

https://github.com/appium/ruby_lib/issues/293

**Comment by jlipps** [comment]
I don't know if it's intended behavior or not either, but it certainly has been surprising. Either way, and for good or for ill, the touch spec has changed to something completely different, so we'll be implementing that soon and this will all be somewhat moot. See #4195

**Comment by markcorbyn** [comment]
This link also seems to be related: https://github.com/appium/appium/pull/3932
The java client docs also specify that they expect moveTo to be absolute position:  http://appium.github.io/java-client/io/appium/java_client/TouchAction.html

For now I'll assume moveTo means moveBy with relative coordinates.

**Comment by bootstraponline** [comment]
> Either way, and for good or for ill, the touch spec has changed to something completely different, so we'll be implementing that soon and this will all be somewhat moot. See #4195

:+1:

**Comment by moizjv** [comment]
Looks like we can look into this issue along with #4195

**Comment by jlipps** [comment]
This issue has been resolved for a while, closing.

**Comment by mounamukhar** [comment]
Which version has the resolution? I am still facing this in 1.6.5
