### ISSUE TITLE
Extremely slow performance on Mac OSX 10.10.1 Yosemite

### ISSUE THREAD

**Issue by chrigrahcisco** [appium/appium#4397]
Appium.app 1.3.4
Python 2.7 with Appium-Python-Client 0.11
Mac OSX 10.10.1 Yosemite
Xcode 6.1.1
iOS Simulator 8.1

Since upgrading from Mavericks to Yosemite Appium performance is extremely, extremely slow. Actions that used to take a few seconds can sometimes take several minutes to execute, particularly when interrogating the current screen / source such as determining if an element exists by xpath.

You can see others reporting the same: https://discuss.appium.io/t/ios-sim-tests-running-very-slowly-on-yosemite-anyone-else/2230/4

Happy to provide more specific details beyond my generalized claim of slowness if you can provide specific steps you want me to execute to gather additional details. Unfortunately I no longer have a Mavericks machine to execute on to gather comparative data.

**Comment by amedvedjev** [comment]
same config but Java client - no problem.
we had similar problem when "instruments-without-delay" where removed in appium server start.

suggest to check did "instruments-without-delay" loaded successfully during server start.

**Comment by Rosepotato** [comment]
I met the same problem. every action (e.g. find element and click ) will take more than 5s. It's really too slow.
My evn:
Appium.app 1.3.4
Java Client
Mac OSX 10.10.1 Yosemite
Xcode 6.1.1
iOS Simulator 7.1

**Comment by penguinho** [comment]
Do you have the "Use Native Instruments Library" preference checked in your iOS settings?

**Comment by chrigrahcisco** [comment]
Note that I'm also still fighting against this issue which causes most of my tests to fail to execute: https://github.com/appium/appium/issues/4178

I mention this as it potentially impacts my "slowness" issue.

Here's some test execution time data. I did not log failures due to the notification dialog bug. But it indicates that Appium.app 1.3.4 has some sort of issue with it getting slower as time progresses.

--------------

full logging, server flag off

Elapsed time =  7.64217400551
Elapsed time =  48.3870658875
Elapsed time =  68.0257499218
Elapsed time =  145.143904924
Elapsed time =  175.712619066
Elapsed time =  199.230959177

Quit and restarted Appium.app

Elapsed time =  7.85054707527

Quit and restarted Appium.app

full logging, server flag on --native-instruments-lib 

Some initial failures
Elapsed time =  36.7825860977
Elapsed time =  37.0590860844
Elapsed time =  67.7876679897
Elapsed time =  119.499984026
Many more failures and I gave up trying to get more data

**Comment by amedvedjev** [comment]
did you try to play with log level?

**Comment by sebv** [comment]
Yeah it's instruments without delay, I've recompiled it for iOS8 recently. 

Just try this 10 times, it should take less than 10 seconds:
```
driver.execute("$.log('hello world')");
```

try to do `pkill -f Simulator` before the test.

**Comment by chrigrahcisco** [comment]
Apparently it's the logging, which I don't recall having any issues in the past.

Details:

--native-instruments-lib --log-level warn

Elapsed time =  36.5361509323
Elapsed time =  36.9421339035
Elapsed time =  36.590624094


--log-level warn

Elapsed time =  5.91939210892
Elapsed time =  5.91077017784
Elapsed time =  5.92024707794
Elapsed time =  5.8953371048

**Comment by amedvedjev** [comment]
we have problem with previous versions and always use "quite" mode with long test or test run of many test cases. unfortunately it was removed in latest version and we start using ERROR level as minimum possible.

**Comment by sebv** [comment]
@chrigrahcisco it's normal with `--native-instruments-lib` there is a one sec delay between each command.

**Comment by chrigrahcisco** [comment]
The conclusion is it's the logging bogging down my tests.

Thanks for the assistance.

**Comment by amedvedjev** [comment]
so why you closed issue if the problem exists :-) ?
we narrow that problem in level of logging and i believe it should be fixed....

**Comment by sebv** [comment]
We need to take a good look at logging, specially when combined with GUI, maybe replace winston, or allow people to configure rolling logging, moving this to 1.3.7. @0x1mason could you assign to correct milestone.

**Comment by 0x1mason** [comment]
@chrigrahcisco I have a proposed workaround here: https://github.com/appium/appium/issues/4638#issuecomment-90585639

**Comment by jlipps** [comment]
@chrigrahcisco I'm also curious if this reproduces when you're not using Appium.app. Can you report whether @0x1mason's workaround works for you?

**Comment by chrigrahcisco** [comment]
Unfortunately I do not know what NSLog is or how to go about attempting those workarounds in my Appium.app Python environment. My current process is to enabled debug logging when troubleshooting a specific problem during test development, otherwise I set logging to error:warn which severely limits the logging.

**Comment by jlipps** [comment]
@chrigrahcisco I'd like to try and actually reproduce this. do you have any hints of the kind of test I could write that would reproduce this? does this reproduce with any of Appium's test apps? (found [here](https://github.com/appium/sample-code)) does the test have to be a certain length?

**Comment by yaphatak** [comment]
@chrigrahcisco : can you comment this line https://github.com/appium/appium/blob/master/lib/devices/ios/webkit-remote-debugger.js#L50 and restart appium node and run test?

**Comment by yaphatak** [comment]
@jlipps we were able to improve performance by replacing console.log with logger.debug or even removing this line https://github.com/appium/appium/blob/master/lib/devices/ios/webkit-remote-debugger.js#L50. I am working with our org to set up fork repo and I will send few pull requests (which fixed few issue for us)

**Comment by jlipps** [comment]
@yaphatak thanks for the investigation! we're trying to get 1.4 out ASAP so i made these changes: https://github.com/appium/appium/pull/5036

can you see if this helps you? unfortunately i don't think it will help @chrigrahcisco since he's not using a real device.

**Comment by chrigrahcisco** [comment]
Unfortunately I don't have anything additional or helpful to add at this time. Unsure when I'll have free time to investigate further and try to supply a test against the sample app to reproduce the issue.

**Comment by jlipps** [comment]
we're totally redoing logging in appium 1.5, so this should be fixed with those changes. we'll check back in at that release

**Comment by chrigrahcisco** [comment]
Sorry I haven't been contributing here. I actually did spend some time a couple weeks ago attempting to reproduce this with one of the test apps but was unable to. Based on that, I suspect part of the issue is with the monster UIATable elements in my AUT. There are often 100+ UIATableCell and I'm sure that's chewing up a lot more resources than the simple test apps you have shared.  Hit me back up when Appium.app 1.5 is released and I'll be able to test that with my AUT.

**Comment by ShankarGargXebia** [comment]
i am using Appium 1.4.8 and my AUT has lots of TableViews and TableCells, Appium takes more than 1 minute to find the element and i can see in logs lot of statements. While everything works fine when AUT does not have many TableViews and TableCells.

I have two questions:
1. When is this issue expected to be fixed?
2. Why Appium fails to identify elements when using TableViews and TableCells, is use of TableViews and TableCells not a good UI strategy?

**Comment by amedvedjev** [comment]
@ShankarGargXebia let's us know the size of PageSource when it is fine and when it working longer.
```
driver.getPageSource()
```
We have absolutely same problem with gallery object of starting from 2-3 items (with 10 items or more it is absolutely not acceptable speed of finding) where each item occupies full screen and have many(15-20) objects inside(like image, description, header, links, icons and so on).

the only workaround we did is take one time getPageSource() and check all we need inside it by parsing it as XML.

BTW can you test native UIAutomator speed doing same command? just interesting... i guess it is just native behavior but not sure.

**Comment by ShankarGargXebia** [comment]
@amedvedjev Here is the pagesource of the application where it is taking too long to find elements. https://drive.google.com/file/d/0By9mn5ED6LgNRXdUN0dhTFJGbzQ/view?usp=sharing

Regarding "the only workaround we did is take one time getPageSource() and check all we need inside it by parsing it as XML." - I am not sure if i get it right. but as per my understanding this workaround will not help me as even if i get page source once and verify items in it, but i need to click on elements in TableView and verify something, repeating this process few times. And the original problem still remains that Appium is taking too long to find elements in Tableview that session expires even though timeout is 120 seconds.

Please let me know if i was able to make my point or not.

**Comment by amedvedjev** [comment]
i do not see any Table or Cell elements in above PageSource :-)

**Comment by ShankarGargXebia** [comment]
@amedvedjev : yes, this worries me as well. That in PageSource there are no Tables while i can see them while finding elements. Let me attach Appium Element Finder screenshot and also Appium Logs. Let me know if this helps.

Appium Logs: https://drive.google.com/file/d/0By9mn5ED6LgNaHZ4QTYyTVBac1E/view?usp=sharing
Finder window screenshot attached.
<img width="1376" alt="screen shot 2015-09-16 at 6 25 49 pm" src="https://cloud.githubusercontent.com/assets/10280199/9905192/15e1aa9c-5ca1-11e5-9e94-df9e6fb85b63.png">

Please let me know if more info is required.

**Comment by ShankarGarg** [comment]
@amedvedjev : any update on this issue. 

@imurchie : Can we fix this bug on priority for next beta release of Appium 1.5?

**Comment by amedvedjev** [comment]
what we see in logs:
```
2015-09-16 12:52:11:568 - info: [debug] This is the last data final length: 985848
2015-09-16 12:53:37:616 - info: [debug] This is the last data final length: 985848
... so on
```

you XML tree is almost 1MB. no wonder that it is taking almost 30sec to transfer it from device or simulator to Appium and then it is taking much time to process so huge xml

**Comment by ShankarGarg** [comment]
So what could be workaround for this. i guess i cant reduce the XML tree.

**Comment by amedvedjev** [comment]
1) leave as is (maximum you can reduce from 1 min to let say 35-40sec)
2) if you still insist to save 20-25sec then create you own strategy inside test with minimum requests to Appium server on such screen like:
 - get large XML tree of page
 - search (parse XML) all what you need before go to next page

**Comment by ShankarGarg** [comment]
Ok. I will try option 2, but recently i was not able to interact with the page at all. When i was running with pre launch application than Appium used to take more than 2-3 minutes to interact with the application and Appium Inspector was  hung most of the time. But let me check again and i will update here.

**Comment by amedvedjev** [comment]
option 3:
 - if you do not need much iterations on page and this page does not change much = you can do image recognition and compare full or partially needed part of screen against master images.

**Comment by ShankarGarg** [comment]
Yes, thats the last step of the test case, we scroll till end of page and stitch the screenshots and than compare the expected and actual screenshots.But before that i need to verify some actions like click etc on this page and i was facing two problems:
1. using Appium Inspector i was not able to get the locators for this page( i used UI Automator and solved this problem)
2. Appium keeps on loading the XML and does not reach to parse the first statement of verifying if the element is even present on this page. ( this is the problem for me and i will work on this to check what's wrong).

**Comment by amedvedjev** [comment]
you may click on image :-). we did it in one of our tests for iOS where element was not visible anywhere but it was clickable anyway.
we implemented full image recognition (except character recognition):
 - we can check does such image exists on screen
 - get existing image coordinates and click by them

some steps i mention in here: https://github.com/appium/appium/issues/943

**Comment by ShankarGargXebia** [comment]
I still cant figure out whats the problem. But here is link to appium log. For my AUT, it is still taking too long to respond. i cant even use Appium Inspector to identify the elements. https://drive.google.com/file/d/0By9mn5ED6LgNR2ZDTkFMR2hsaWM/view?usp=sharing

Please check and confirm if this big logs are normal?

**Comment by ShankarGargXebia** [comment]
Hi Guys,

any updates on how to fix this issue? iOS automation of my AUT is stuck because of this. Appium takes more than 2-3 minutes to execute even one step.

Thanks,
Shankar

**Comment by ShankarGargXebia** [comment]
changing log level to Debug in appium GUI app 1.4.8 fixed the issue for me. @chrigrahcisco : Thanks for mentioning the solution

**Comment by gselsidi** [comment]
How do you turn off the logging in Appium? What are the commands for the environmental variables in the GUI, or how can I do it in JAVA through the Appium desired capabilities setup?

**Comment by ShankarGargXebia** [comment]
Check the Log level in Settngs of Appium GUI App:

<img width="694" alt="screen shot 2015-10-23 at 9 15 48 pm" src="https://cloud.githubusercontent.com/assets/10280199/10697810/6c440578-79cb-11e5-8ad0-08ae829726e7.png">

**Comment by gselsidi** [comment]
I see the default is basically debug, which runs slowly for me. How can I run my settings through GUI in command line so I can turn off debug logging?

Thanks

**Comment by imurchie** [comment]
To change the log level through the command line, add the server argument `--log-level` to your startup.

For example, to use `info`:

```shell
appium --log-level info
```

**Comment by ShankarGargXebia** [comment]
@imurchie : is this bug expected to be fixed anytime soon?

**Comment by gselsidi** [comment]
@imurchie Is there a way to apply arguments through the gui environmental variables box? As when I run Appium through command line, I keep getting "could not find device to launch, you requested this but only this is available" error. Even though I launch it with the same settings as the GUI

**Comment by imurchie** [comment]
There should be an option in "Developer Settings" => "Custom Server Flags".

**Comment by ShankarGargXebia** [comment]
Hi All,

For Appium and iOS slow execution (incase of Collection views and Table Views) we have changed the way we interact with iOS. Instead of using Xpath, now we use iOSUIAutomator.
Implemented a PoC for iOSUIAutomator strategy instead of Xpath. 
In Multiple runs it was proved that its very fast as compared to Xpath. Earlier steps that took 90 secs are taking less than 10 secs. 
Here are the results in milli seconds for iOSUIAutomator and Xpath:

Run 1:
IOS Automator :8341
XPath :63066

Run 2:
IOS Automator :8474
XPath :61177

Run 3:
IOS Automator :5788
XPath :70475

No need to wait for 1.5 version for fix of this bug.

**Comment by narulacool** [comment]
@ShankarGargXebia Can you give an example of how you are using IOS Automator!

**Comment by ShankarGargXebia** [comment]
@narulacool : Please check Following links for better understanding of  IOS Automator:

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios_predicate.md
https://discuss.appium.io/t/how-to-use-findelements-byiosuiautomation/607/22

**Comment by narulacool** [comment]
@ShankarGargXebia : Thanks!!

**Comment by ShankarGarg** [comment]
You closed this bug because instead of xpath we can use iOSUiAutomation  or this has been fixed using xpath also?

~
Thanks
Shankar
+91-9873842038

**Comment by jlipps** [comment]
I don't think there's anything we can do WRT xpath, and it looks like uiautomation is a good workaround

**Comment by ShankarGargXebia** [comment]
Agreed

~
Thanks
Shankar
+91-9873842038

Sent from mobile, excuse typos

On 23-Dec-2015, at 3:24 AM, Jonathan Lipps <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think there's anything we can do WRT xpath, and it looks like uiautomation is a good workaround

-

**Comment by vm31** [comment]
So can't we use appium inspector for locating elements on iOS? I am using appium 1.4.13 which is extremely slow in tap /action on elements

**Comment by knreddy036** [comment]
Scripts are running very slow with appium 1.5.2 version , but with appium 1.4.3 version ,it is very fast .Suppose for each testscript in appium 1.4.3 ,it takes 80 sec ,but with appium 1.5.2 ,it is taking 400 sec .Any Idea how to fix this one ?

**Comment by knreddy036** [comment]
With Appium 1..5.2,/1.5.3 execution time is taking double time than Appium 1.4.13 on iPhone safari browser.Any idea how to fix this ?

**Comment by amirwaisman** [comment]
appium 1.5.3 shows EXTREMELY slow performance with driver.getPageSource().

**Comment by jawlitkp** [comment]
Any solution for slowness in safari test ? please share solution
