### ISSUE TITLE
mobile:scroll fails in iOS 8.3

### ISSUE THREAD

**Issue by imurchie** [appium/appium#4836]
Using Xcode 6.3 beta 4, ff you scroll to the bottom of a scroll view, leave it, and return, scroll throws an error in the bootstrap code (see our basic tests on UICatalog, [here](https://github.com/appium/appium/blob/master/test/functional/ios/uicatalog/basic-specs.js#L48)).

``` shell
info: --> POST /wd/hub/session/c0d4a222-8ccb-449d-855b-a984bc8bee3d/execute {"script":"mobile: scroll","args":{"direction":"down"}}
info: [debug] Pushing command to appium work queue: "au.scrollFirstView('Down')"
info: [debug] Sending command to instruments: au.scrollFirstView('Down')
info: [debug] [INST] 2015-04-01 18:37:26 +0000 Debug: Got new command 28 from instruments: au.scrollFirstView('Down')
info: [debug] [INST] 2015-04-01 18:37:26 +0000 Debug: evaluating au.scrollFirstView('Down')
info: [debug] [INST] 2015-04-01 18:37:26 +0000 Debug: Looking for view of type scrollview
info: [debug] [INST] 2015-04-01 18:37:26 +0000 Debug: Looking for view of type tableview
info: [debug] [INST] 2015-04-01 18:37:26 +0000 Debug: target.frontMostApp().elements()[0].elements()[1].scrollDown()
info: [debug] [INST] 2015-04-01 18:37:26 +0000 Debug: Unexpected error in -[UIATableView_0x7fa699c6a520 scrollDown], /SourceCache/UIAutomation_Sim/UIAutomation-430.1.1/Framework/UIAElement.m line 1480, kAXErrorFailure
info: [debug] Socket data received (189 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"Unexpected error in -[UIATableView_0x7fa699c6a520 scrollDown], /SourceCache/UIAutomation_Sim/UIAutomation-430.1.1/Framework/UIAElement.m line 1480, kAXErrorFailure"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Unexpected error in -[UIATableView_0x7fa699c6a520 scrollDown], /SourceCache/UIAutomation_Sim/UIAutomation-430.1.1/Framework/UIAElement.m line 1480, kAXErrorFailure"},"sessionId":"c0d4a222-8ccb-449d-855b-a984bc8bee3d"}
info: <-- POST /wd/hub/session/c0d4a222-8ccb-449d-855b-a984bc8bee3d/execute 500 310.358 ms - 324
```

This seems to be a regression in the sim code, and happens periodically on a new release (see #3851, for instance).

Related to #4828.

**Comment by jlipps** [comment]
out of curiosity, is gesture recognition fixed in ios 8.3? i.e., can we use the actual gesture methods to scroll now?

**Comment by imurchie** [comment]
It doesn't seem to work, no.

**Comment by alatyshev** [comment]
Still an issue with iOS 8.4 sim as well. Instruments fail only when scroll is reaching the end.

**Comment by marciok** [comment]
Having this issue now on the 8.4, whenever I try to scroll: 
```execute_script 'mobile: scroll', direction: 'down'```
I get:
```
Selenium::WebDriver::Error::JavascriptError: Unexpected error in -[UIATableView_0x7fde2593fba0 scrollDown], /SourceCache/UIAutomation_Sim/UIAutomation-430.2.1/Framework/UIAElement.m line 1480, kAXErrorFailure
from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
```

**Comment by peushan** [comment]
Hi All, 
Do anyone know a solution for this above error. I am also come across this issue and searching for any alternatives as its crash ones the scroll:down calls. Below is the error i got. 

Debug: Unexpected error in -[UIAScrollView_0x137d916b0 scrollDown], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation/UIAutomation-448/Framework/UIAElement.m line 1480, kAXErrorFailure

Appium version: 1.5.2
iOS version: 9.3 
Please let me know if anybody needs more information regarding to this. 

Regards,
Pamodh

**Comment by imurchie** [comment]
The `kAXErrorFailure` seems to happen when it tries to scroll beyond the end of the scrollable view. A fix is forthcoming.The `kAXErrorFailure` seems to happen when it tries to scroll beyond the end of the scrollable view. A fix is forthcoming.

**Comment by ews-android** [comment]
@imurchie

Do you have any idea, how to do scrolling/swipe (up/down/left/right) in ios simulator . 

I am using java, i tried almost every thing, like scroll, swipe and TouchAction, but no success . 
Can you help me ?

**Comment by imurchie** [comment]
@ews-android Please start a new issue with as much information as you can about what you did and what the outcome was (including logs, etc.). This issue is not the place for more piling on.

**Comment by saikrishna321** [comment]
@jlipps this can be closed, we no more support "mobile: scroll"

**Comment by SrinivasanTarget** [comment]
@triager please close
