### ISSUE TITLE
Appium ignores iframe context when getting page source (iOS)

### ISSUE THREAD

**Issue by JasnoWa** [appium/appium#5199]
When the driver is switched to the context of an iframe and you attempt to get the page source, you'll get the source for the parent page instead of the iframe.  For example assume you have the following webpages:

index.html

``` html
<html>
<head>
<title>PARENT PAGE</title>
</head>
<body>
<div>PARENT PAGE DIV</div>
<iframe src="frame.html" id="myFrame"></iframe>
</body>
</html>
```

frame.html

``` html
<html>
<head>
<title>IFRAME PAGE</title>
</head>
<body>
<div id='iframeDiv'>IFRAME PAGE DIV</div>
</body>
</html>
```

And you execute the following driver commands (showing python here but I've seen this via java bindings as well):

``` python
driver = webdriver.Remote( command_executor='http://127.0.0.1:4444/wd/hub', desired_capabilities={'browserName': 'Safari', 'deviceName': 'iPhone 5s', 'platformVersion': '8.1', 'platformName': 'iOS'})
driver.get('http://localhost:8000/index.html')
driver.switch_to.frame(driver.find_element_by_tag_name("iframe"))
print driver.page_source
```

The page source printed there will be from index.html instead of frame.html

**Comment by sebv** [comment]
Hum, looks like a bug, as a workaround, you could probably write it in javascript and retrieve it with `execute`.

**Comment by jlipps** [comment]
we do have tests of iframe handling here: https://github.com/appium/appium/blob/master/test/functional/common/webview/frames-base.js

which makes me ask 2 questions:

1. i don't see tests for switching to a frame by an element object. is that supported? did you try switching by name or id instead?
2. the [JSONWP](https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/source) doesn't say anything about `source` changing based on the frame. is that the way it works in, say, FirefoxDriver? if so, it could be it's just an oversight on Appium's part and something we can add (returning the frame source if we're in a frame context)

**Comment by sebv** [comment]
One thing to keep in mind is that the iframe sources do not appear within the parent source, so that kind of make sense to retrieve the source of the current frame. But I agree with @jlipps , we should check what selenium is doing and do the same.

**Comment by JasnoWa** [comment]
Switching frames via the id leads to the same result

```python
driver.switch_to.frame('myFrame')
print driver.page_source # Parent page returned
```

**Comment by lukeis** [comment]
it's one of those things that hasn't been well defined in a spec anywhere, the W3C spec doesn't even deal with page source, there was [even a recent discussion on the W3C webdriver spec](http://lists.w3.org/Archives/Public/public-browser-tools-testing/2015JanMar/0079.html) regarding page source, which decided that the API end point should not be spec'd and client ends should start sending a javascript snippet in execute script.

That being said, Firefox currently behaves by returning the page source of the frame context it is currently in.

**Comment by lukeis** [comment]
@jlipps also in regards to the switching to frame by element, yes that is supported in the old [JSONWP](https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/frame)  "id - {string|number|null|WebElement JSON Object}"

But in the future only WebElement and index are going to be allowed (not string name):
https://w3c.github.io/webdriver/webdriver-spec.html#switching-frames

**Comment by lukeis** [comment]
btw @jlipps & @sebv meet Jason, we work on the same team together :)

**Comment by jlipps** [comment]
hi @JasnoWa! and thanks for context @lukeis. @lukeis do you recommend that appium return the frame-internal source?

**Comment by lukeis** [comment]
@jlipps yes, I would recommend doing just that (since some of our users expect this same behavior cross browser :) )

**Comment by jlipps** [comment]
:+1: ok this is marked as a bug accordingly so we will get to it when we can

**Comment by lukeis** [comment]
thanks much :)

**Comment by moriaam** [comment]
Do you have en estimation to when will this be fixed?

**Comment by denslinsunitha** [comment]
is this issue fixed now ?

**Comment by jlipps** [comment]
@denslinsunitha it is listed as a bug with a priority label and is open, so it is not fixed.

**Comment by denslinsunitha** [comment]
We are still face this issue.
below are the configuration which we are using:
Appium : 1.6.4
Ios: 10.3

**Comment by siggerzz** [comment]
Any idea when this is going to be fixed? Most of my hybrid app is in an IFrame, which kind of defeats the purpose of using Appium if I can only have these tests working on Android...

**Comment by lukeis** [comment]
The workaround is simple and works on all other drivers too:

    driver.execute_script('return document.documentElement.outerHTML')

**Comment by jlipps** [comment]
thanks @lukeis! @siggerzz i hear you, and i will also bump up the priority of this issue. it hasn't been worked on mostly because no one commented on it in 2 years so it didn't seem that urgent.

**Comment by siggerzz** [comment]
@jlipps Thanks! I appreciate you guys have been working on more important issues. Looking forward to the fix!

**Comment by siggerzz** [comment]
Has any progress been made on this at all?

**Comment by imurchie** [comment]
This should be fixed in the latest beta version of Appium (and will be in 1.7.2)

**Comment by siggerzz** [comment]
@imurchie This seems to be working now! I am having an issue clicking elements within my IFrame though (only affects iOS).

The click is executed, however nothing actually happens. Which project should I raise this with?

**Comment by dpgraham** [comment]
@imurchie Can I close this?
