### ISSUE TITLE
"TypeError: undefined is not a function" when creating a new session

### ISSUE THREAD

**Issue by diana-zaharia** [appium/appium#5266]
Trying to run tests for mobile web app on Android Browser, using following capabilities:

```
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Browser");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.1.1");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
```

appium 1.4.3, running on linux x64 with chromedriver 2.16, following error is logged when creating new session:

```
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data"}
info: [debug] dataDir set to: /data
error: Unhandled error: TypeError: undefined is not a function
    at [object Object].ChromeAndroid.createSession (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/chrome.js:154:33)
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:607:21
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:246:17
    at iterate (/home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:146:13)
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:157:25
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/android.js:541:5)
    at next (/home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:798:43)
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:32:16
    at [object Object].exports.respond (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/common.js:28:9)
    at [object Object].<anonymous> (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/android.js:507:16)
    at [object Object].<anonymous> (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/uiautomator.js:95:9)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20) context: [POST /wd/hub/session {"desiredCapabilities":{"browserName":"Browser","autoWebview":true,"platformName":"Android","deviceName":"Android Emulator","platformVersion":"5.1.1"}}]
```

**Comment by moizjv** [comment]
Can you try using `browserName` as `Chromium` ?

**Comment by nikhil969** [comment]
I am also facing the same issue

**Comment by diana-zaharia** [comment]
Same for Chrome browser:
`2015-06-18 15:21:18:462 - error: Unhandled error: TypeError: undefined is not a function
    at [object Object].ChromeAndroid.createSession (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/chrome.js:154:33)
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:607:21
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:246:17
    at iterate (/home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:146:13)
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:157:25
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/android.js:541:5)
    at next (/home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:798:43)
    at /home/emulator/nodejs/lib/node_modules/appium/node_modules/async/lib/async.js:32:16
    at [object Object].exports.respond (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/common.js:28:9)
    at [object Object].<anonymous> (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/android.js:507:16)
    at [object Object].<anonymous> (/home/emulator/nodejs/lib/node_modules/appium/lib/devices/android/uiautomator.js:95:9)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20) context: [POST /wd/hub/session {"desiredCapabilities":{"browserName":"Chrome","platformName":"Android","deviceName":"Android Emulator","platformVersion":"5.1.1"}}]`

**Comment by moizjv** [comment]
@diana-zaharia yes looks like an issue in newer version of appium. Chromedriver binary is missing.

**Comment by moizjv** [comment]
@diana-zaharia work around is can you run `./reset.sh` ?

**Comment by moizjv** [comment]
@diana-zaharia it was an upstream dependency issue. Thanks for raising it here. We have release 1.4.5, try to upgrade it should fix this issue.

**Comment by diana-zaharia** [comment]
@moizjv thanks for helping, unfortunately I'm still facing some issues:
- after upgrading to 1.4.5 I'm facing the issue tracked in #5274 
- running reset.sh results in failure:
`* Determining platform
* Platform is linux
---- Resetting / Initializing Appium ----
RESETTING NPM
* Installing new or updated NPM modules (including devDeps)
npm WARN package.json appium@1.4.5 No license field.
npm WARN optional dep failed, continuing udidetect@1.0.7
RESETTING GENERAL
* Nothing to do, not a git repo
RESETTING ANDROID
* Configuring Android bootstrap
Running "configAndroidBootstrap" task
Error: Target id is not valid. Use 'android list targets' to get the target ids.
Warning: Setup cmd /home/emulator/Android/Sdk/tools/android failed with code 1 Use --force to continue.

Aborted due to warnings.
---- FAILURE: reset.sh exited with status 1 ----
`

**Comment by nikhil969** [comment]
Thanks @moizjv  got it working finally faced issues while updating it to 1.4.5. I got it updated to 1.4.5 randomly by goolge searching so please can u provide some clean steps to install 1.4.5 version

**Comment by moizjv** [comment]
@nikhil969 @diana-zaharia yes we had few issues with patch releases. Can you try now with upgrading to 1.4.6?

**Comment by diana-zaharia** [comment]
1.4.6 is working fine, I just upgraded and managed to run the tests. Thanks!

**Comment by moizjv** [comment]
NP :)

**Comment by anmudgal** [comment]
Appium 1.4.6 did not solve a long due problem of (iOS webkit debug proxy issue) "IOS Safari browser multiple tests running sequentially on same device". Uptil 1.4.3 this scenario used to work after restarting appium and iOS_debug_webkit_proxy after every test.. 1.4.6 can not find any web views for second test. 
And on 1.4.3 Android chrome is not working. Can you please help me here.. I am ok with patching 1.4.3 for android to work, which already works for IOS with restart solution.
