### ISSUE TITLE
findElement by IosUIAutomation returns a parsing error when selector contains an apostrophe

### ISSUE THREAD

**Issue by sergejjkim** [appium/appium#5511]
appium 1.4.8, java bindings 3.0.0
finding element
By.IosUIAutomation: target.frontMostApp().mainWindow().tableViews()[0].cells().firstWithPredicate("staticTexts[1].value CONTAINS 'j'ai déjà regardé futurama'")

results in An error occurred while executing user supplied JavaScript. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.42 seconds

appium logs say:

info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Unable to parse the format string \"staticTexts[1].value CONTAINS 'j'ai déjà regardé futurama'\""},"sessionId":"83ac5451-de8a-4bd0-b688-e1eec3a44ef9"}
info: <-- POST /wd/hub/session/83ac5451-de8a-4bd0-b688-e1eec3a44ef9/element 500 1921.587 ms - 262 

same problem if I try to escape ' with \\'

**Comment by scottdixon** [comment]
Should be resolved in 1.5.

Please reopen + provide logs if otherwise.

**Comment by sergejjkim** [comment]
issue is still actual on 1.5.2

```
[debug] [Instruments] [INST] 2016-05-18 13:57:37 +0000 Debug: Got new command 84 from instruments: au.getElementByUIAutomation('target.frontMostApp().mainWindow().tableViews().firstWithPredicate(\"name == \'streamItemsTable\'\").cells().firstWithPredicate(\"staticTexts[1].value CONTAINS \'RT @alysiagray: Futurama and Bob\'s Burgers type of morning\'\")')
[debug] [Instruments] [INST] 2016-05-18 13:57:37 +0000 Debug: evaluating au.getElementByUIAutomation('target.frontMostApp().mainWindow().tableViews().firstWithPredicate(\"name == \'streamItemsTable\'\").cells().firstWithPredicate(\"staticTexts[1].value CONTAINS \'RT @alysiagray: Futurama and Bob\'s Burgers type of morning\'\")')
[debug] [Instruments] [INST] 2016-05-18 13:57:37 +0000 Debug: byUIAutomation: evaluating code: target.frontMostApp().mainWindow().tableViews().firstWithPredicate("name == 'streamItemsTable'").cells().firstWithPredicate("staticTexts[1].value CONTAINS 'RT @alysiagray: Futurama and Bob's Burgers type of morning'")

[debug] [UIAuto] Socket data received (154 bytes)

[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Unable to parse the format string \"staticTexts[1].value CONTAINS 'RT @alysiagray: Futurama and Bob's Burgers type of morning'\""}
[HTTP] <-- POST /wd/hub/session/ccb58e3f-73fc-4f69-bae9-9faa4cd3bcd0/element 500 979 ms - 215 
[debug] [Instruments] [INST] 2016-05-18 13:57:37 +0000 Error: VerboseError: Unable to parse the format string "staticTexts[1].value CONTAINS 'RT @alysiagray: Futurama and Bob's Burgers type of morning'"
[debug] [Instruments] [INST] 2016-05-18 13:57:37 +0000 Error: Error during eval: firstWithPredicate@[native code]
       eval code
eval@[native code]
_getElementsByUIAutomation@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/DD6DC479-DD7B-41A0-AFC1-DF21BA53FD89/bootstrap-f09613698d23252b.js:1615:23
getElementByUIAutomation@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/DD6DC479-DD7B-41A0-AFC1-DF21BA53FD89/bootstrap-f09613698d23252b.js:1591:50
eval code
eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/DD6DC479-DD7B-41A0-AFC1-DF21BA53FD89/bootstrap-f09613698d23252b.js:2793:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/DD6DC479-DD7B-41A0-AFC1-DF21BA53FD89/bootstrap-f09613698d23252b.js:2861:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/DD6DC479-DD7B-41A0-AFC1-DF21BA53FD89/bootstrap-f09613698d23252b.js:2870:10
[debug] [Instruments] [INST] 2016-05-18 13:57:37 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-05-18 13:57:37 +0000 Debug: Running system command #85: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/rp/mzskym_9167_7hxy9158768j2tlz6b/T/instruments_sock 2,{"status":17,"...

[HTTP] --> POST /wd/hub/session/ccb58e3f-73fc-4f69-bae9-9faa4cd3bcd0/element {"using":"-ios uiautomation","value":"target.frontMostApp().mainWindow().tableViews().firstWithPredicate(\"name == 'streamItemsTable'\").cells().firstWithPredicate(\"staticTexts[1].value CONTAINS 'RT @alysiagray: Futurama and Bob's Burgers type of morning'\")"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["-ios uiautomation","target.frontMostApp().mainWindow().tableViews().firstWithPredicate(\"name == 'streamItemsTable'\").cells().firstWithPredicate...
[debug] [iOS] Executing iOS command 'findElement'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByUIAutomation('target.frontMostApp().mainWindow().tableViews().firstWithPredicate(\"name == \'streamItemsTable\'\").cells().firstWithPredicate(\"staticTexts[1].value CONTAINS \'RT @alysiagray: Futurama and Bob\'s Burgers type of morning\'\")')

[debug] [Instruments] [INST] 2016-05-18 13:57:38 +0000 Debug: Got new command 85 from instruments: au.getElementByUIAutomation('target.frontMostApp().mainWindow().tableViews().firstWithPredicate(\"name == \'streamItemsTable\'\").cells().firstWithPredicate(\"staticTexts[1].value CONTAINS \'RT @alysiagray: Futurama and Bob\'s Burgers type of morning\'\")')
```

if trying to use \" instead of ' in UIAutomation selector
```

[debug] [Instruments] [INST] 2016-05-18 13:13:07 +0000 Debug: evaluating au.getElementByUIAutomation('target.frontMostApp().mainWindow().tableViews().firstWithPredicate(\"name == \'streamItemsTable\'\").cells().firstWithPredicate(\"staticTexts[1].value CONTAINS \"It\'s #KimPossible and #StevenUniverse on this week\'s episode! (After the requisite amount of #Futurama talk) https:\/\/t.co\/fYVMezGxil\"\")')
[debug] [Instruments] [INST] 2016-05-18 13:13:07 +0000 Debug: byUIAutomation: evaluating code: target.frontMostApp().mainWindow().tableViews().firstWithPredicate("name == 'streamItemsTable'").cells().firstWithPredicate("staticTexts[1].value CONTAINS "It's #KimPossible and #StevenUniverse on this week's episode! (After the requisite amount of #Futurama talk) https://t.co/fYVMezGxil"")
[debug] [UIAuto] Socket data received (90 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Unexpected identifier 'It'. Expected ')' to end a argument list."}
[HTTP] <-- POST /wd/hub/session/93a4c69e-8a87-498a-9e1c-6242f03ce710/element 500 607 ms - 151 
[debug] [Instruments] [INST] 2016-05-18 13:13:07 +0000 Error: SyntaxError: Unexpected identifier 'It'. Expected ')' to end a argument list.
```

**Comment by sergejjkim** [comment]
Thanks!

2016-07-22 0:41 GMT+03:00 Scott Dixon <notifications@github.com>:

**Comment by rkavalap** [comment]
@sergejjkim 
Does this still repro with latest version of appium ? If so can you post server log as a gist
