### ISSUE TITLE
[1.5] Appium fails when several android devices connected

### ISSUE THREAD

**Issue by bayandin** [appium/appium#5949]
I use Appium 1.5.0-beta9, and have several Android devices (it's Genymotion, but with real ones problem the same)

```
$ adb devices -l
List of devices attached
192.168.56.103:5555    device product:vbox86p model:test3 device:vbox86p
192.168.56.102:5555    device product:vbox86p model:test2 device:vbox86p
192.168.56.101:5555    device product:vbox86p model:test1 device:vbox86p
```
Example of test ruby:
```ruby
#!/usr/bin/env ruby

require 'appium_lib'

android_opts = {
  caps: {
    platformName: 'Android',
    deviceName: '192.168.56.102:5555',
    platformVersion: '5.1.0',
    browserName: 'Browser'
  },
  appium_lib: {
    port: 4723,
  }
}

appium = Appium::Driver.new(android_opts)
driver = appium.start_driver

driver.get 'https://github.com/appium/appium'
appium.driver_quit
```

Result:
```
/Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok': An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.browser' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255} (Selenium::WebDriver::Error::UnknownError)
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:56:in `new'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:56:in `for'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver.rb:86:in `for'
	from /Users/bayandin/.rvm/gems/ruby-2.1.5/gems/appium_lib-8.0.0/lib/appium_lib/driver.rb:484:in `start_driver'
	from bug.rb:18:in `<main>'
```

Appium log:
```
2015-12-23 14:40:45:819 - info: [Appium] Welcome to Appium v1.5.0-beta9
2015-12-23 14:40:45:820 - info: [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2015-12-23 14:40:45:821 - info: [Appium] Non-default server args:
2015-12-23 14:40:45:821 - info: [Appium]     log: appium.log
2015-12-23 14:40:58:745 - info: [HTTP] --> POST /wd/hub/session
2015-12-23 14:40:58:764 - info: [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","deviceName":"192.168.56.102:5555","platformVersion":"5.1.0","browserName":"Browser"},null,null,null]
2015-12-23 14:40:58:766 - info: [Appium] Creating new AndroidDriver session
2015-12-23 14:40:58:772 - info: [BaseDriver] Session created with session id: 636d0284-b9a6-444a-9297-13da1fb4a7a5
2015-12-23 14:40:58:774 - info: [debug] [AndroidDriver] Getting Java version
2015-12-23 14:40:58:891 - info: [AndroidDriver] Java version is: 1.7.0_79
2015-12-23 14:40:58:891 - info: [AndroidDriver] We're going to run a Chrome-based session
2015-12-23 14:40:58:892 - info: [AndroidDriver] Chrome-type package and activity are com.android.browser and com.android.browser.BrowserActivity
2015-12-23 14:40:58:893 - info: [ADB] Checking whether adb is present
2015-12-23 14:40:58:898 - info: [ADB] Using adb from /usr/local/opt/android-sdk/platform-tools/adb
2015-12-23 14:40:58:899 - info: [AndroidDriver] App file was not listed, instead we're going to run com.android.browser directly on the device
2015-12-23 14:40:58:899 - info: [debug] [AndroidDriver] Checking whether package is present on the device
2015-12-23 14:40:58:901 - info: [debug] [ADB] Getting connected devices...
2015-12-23 14:40:58:910 - info: [debug] [ADB] 3 device(s) connected
2015-12-23 14:40:58:912 - info: [debug] [ADB] Running /usr/local/opt/android-sdk/platform-tools/adb with args: ["shell","pm","list","packages","com.android.browser"]
2015-12-23 14:40:58:944 - error: [ADB] Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.browser' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.execFunc$ (lib/tools/system-calls.js:188:11)
    at tryCatch (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Volumes/Second/repos/rb/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Volumes/Second/repos/rb/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Volumes/Second/repos/rb/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
 [Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.browser' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}]
2015-12-23 14:40:58:945 - info: [debug] [ADB] Running /usr/local/opt/android-sdk/platform-tools/adb with args: ["shell","pm","list","packages","com.android.browser"]
2015-12-23 14:40:58:956 - error: [ADB] Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.browser' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.execFunc$ (lib/tools/system-calls.js:188:11)
    at tryCatch (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Volumes/Second/repos/rb/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Volumes/Second/repos/rb/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Volumes/Second/repos/rb/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
 [Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.browser' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}]
2015-12-23 14:40:58:957 - info: [debug] [AndroidDriver] Shutting down Android driver
2015-12-23 14:40:58:959 - warn: [AndroidDriver] Cannot shut down Android driver; it has already shut down
2015-12-23 14:40:58:960 - error: [MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/usr/local/opt/android-sdk/platform-tools/adb shell pm list packages com.android.browser' exited with code 255{"stdout":"","stderr":"error: more than one device/emulator\n","code":255}
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.execFunc$ (lib/tools/system-calls.js:188:11)
    at tryCatch (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Volumes/Second/repos/rb/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Volumes/Second/repos/rb/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Volumes/Second/repos/rb/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Volumes/Second/repos/rb/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
2015-12-23 14:40:58:966 - info: [HTTP] <-- POST /wd/hub/session 500 217.289 ms - 382
```

Problem actual even if I start Appium with `--default-capabilities '{"udid":"192.168.56.102:5555"}'` (you can find log for this case [here](https://gist.github.com/bayandin/3d2ec767073d90945d97))

**Comment by Jonahss** [comment]
Good find, this is a bug!

Here's the offending line: https://github.com/appium/appium-android-driver/blob/7709affb9d3d35fd7a6f6401921e4a19a9a16c00/lib/driver.js#L249

The command should be using the specified udid.

@imurchie  This is a bug in 1.5 Android Driver

**Comment by Jonahss** [comment]
Should be fixed by https://github.com/appium/appium-android-driver/pull/77

You can try again, if able to build from source, otherwise will be in the next published release.

**Comment by Jonahss** [comment]
Also, you can run `npm install appium-android-driver` and use it ^.^

**Comment by dhirenmudgil** [comment]
I did ran the npm install appium-android-driver, but still facing the issue. when the next release is planned .

**Comment by imurchie** [comment]
The issue now is that `appium-android-bootstrap` uses its own instance of `appium-adb`, and it does not handle the udid properly. We need to change it so you can pass in an adb object.

**Comment by imurchie** [comment]
Should be fixed now.

**Comment by imurchie** [comment]
Closing as fixed.

**Comment by jossjacobo** [comment]
Hello, I am still having a similar issue. I am trying to get the selenium grid working with multiple android/ios devices connected to the same box.

Appium -v `1.5.2`
Selenium Server Standalone `2.53.0`

I am able start the grid and register appium nodes to it.

Sample `nodeconfig.json`
```
{
	"capabilities": [{
		"deviceName": "192.168.60.104:5555",
		"version": "5.0.1",
		"maxInstances": 3,
		"platformName": "ANDROID",
		"os": "ANDROID"
	}],
	"configuration": {
		"cleanUpCycle": 2000,
		"timeout": 30000,
		"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
		"url": "http://192.168.60.1:4724/wd/hub",
		"host": "192.168.60.1",
		"port": 4724,
		"maxSession": 6,
		"register": true,
		"registerCycle": 5000,
		"hubPort": 4444,
		"hubHost": "192.168.60.1"
	}
}
```

Running my scripts and setting up the Appium Driver looks like this
```
  caps = Appium.load_appium_txt file: File.join(Dir.pwd, 'appium.txt')
  caps[:caps][:app] = Dir.pwd + "/" + caps[:caps][:app] #for some reason having an appium_lib => server_url messes up the relative paths.
  Appium::Driver.new caps
```

appium.txt
```
[caps]
platformName = "ANDROID"
platformVersion = "5.0.1"
deviceName = "192.168.60.104:5555"
udid = "192.168.60.104:5555"
app = ".artifacts/android.apk"
appPackage = "com.nycfc.android"

[appium_lib]
server_url = "http://localhost:4444/wd/hub"
require = ["./spec/requires.rb"]
sauce_username = ""
sauce_access_key = ""
```

When running the scripts with good-ole `rspec` it gets stuck on 
```
- waiting for device -
error: more than one device/emulator
...
```

What am I missing? Any help would be greatly appreciated.

Thanks!

**Comment by alexlazarciuc** [comment]
Hello,

I'm facing the same problem. Running the latest Appium version using with Genymotion. So when I run my tests then I'm getting the bellow error:

[ADB] Error: Error while getting connected devices. Original error: Command 'C:\\Users\\alex.lazarciuc\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe devices' exited with code 1
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:118:9)
    at tryCatch (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Error while getting connected devices. Original error: Command 'C:\\Users\\alex.lazarciuc\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe devices' exited with code 1
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:118:9)
    at tryCatch (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\alex.lazarciuc\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [ADB] Could not find devices, restarting adb server...

Can anyone advice how to handle this? Thanks in advance.

**Comment by sarvotam22** [comment]
I am facing the same issue as @alexlazarciuc

**Comment by gastonci** [comment]
Same here

**Comment by rajit30** [comment]
@imurchie  We are still encountering the issue. Could you please have a look . I have created a separate issue on the same , but i guess the root cause is the same for both. 

Issue:
https://github.com/appium/appium/issues/8777

**Comment by prat3ik** [comment]
Hi @imurchie ,
I am also still facing this issue while starting Appium Inspector Session with Genymotion Device.
Please see below configuration(Which is working on my real device): 
```
{
  "app": "/Users/harry/Documents/PK_Workspace/Appium_Framework/Android/src/app/androidMessaging.apk",
  "automationName": "uiautomator2",
  "platformName": "Android",
  "platformVersion": "8.0",
  "appPackage": "com.google.android.apps.messaging",
  "appActivity": "com.google.android.apps.messaging.ui.ConversationListActivity",
  "deviceName": "c4e3f3cd"
}
```
But when I change 

> "deviceName": "192.168.56.101:5555"

 and  

> "platformVersion": "7.0"

It is giving me the error:
**An unknown server-side error occurred while processing the command. Original error: Error in waiting for device. Original error: 'Error executing adbExec. Original error: 'Command '/Users/harry/Library/Android/sdk/platform-tools/adb -P 5037 -s 192.168.56.101\:5555 wait-for-device' exited with code 1'; Stderr: 'error: unknown host service'; Code: '1''. Retrying by restarting ADB**

Can you please give me the hint what I am missing here ?

**Comment by nuanyang233** [comment]
Hi, @prat3ik .
I am facing the same problem as you.
How did you finally solve this problem?

**Comment by prat3ik** [comment]
Hi,
I did not resolve this error still.

**Comment by nuanyang233** [comment]
@prat3ik 
Hi!
I just solved this problem!

I checked my adb and found that there are two adb on my computer and I use the linux system.

So, I first checked the adb path in my genymotion, you can find it in the settings

Then delete the adb command in /usr/bin, and then use the cp command to copy the adb you just found to /usr/bin. Then use the adb devices command to check the success.

I have started my app using appium desktop.

you can try it!

**Comment by prat3ik** [comment]
That's really great.
Thanks for letting me know,
I will try that soon.

**Comment by Ucoon** [comment]
@nuanyang233 I tryed it like you said, but there still failed. This is my server log:
```
[debug] [ADB] Running 'E:\Tools\Android\adt-bundle-windows-x86-20140321\adt-bundle-windows-x86-20140321\sdk\platform-tools\adb.exe -P 5037 -s SA17C07838 shell am force-stop com.android.settings'
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 26b8d138-ec95-478e-80d0-8f46afc225b9 from our master session list
[ADB] Error sending command, reconnecting device and retrying: shell,am,force-stop,com.android.settings
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] Could not find devices, restarting adb server...
[debug] [ADB] Restarting adb
[debug] [ADB] Killing adb server on port 5037
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'E:\Tools\Android\adt-bundle-windows-x86-20140321\adt-bundle-windows-x86-20140321\sdk\platform-tools\adb.exe -P 5037 -s SA17C07838 shell am force-stop com.android.settings'
[ADB] Error sending command, reconnecting device and retrying: shell,am,force-stop,com.android.settings
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
Unhandled rejection Error: Error executing adbExec. Original error: 'Command 'E\:\\Tools\\Android\\adt-bundle-windows-x86-20140321\\adt-bundle-windows-x86-20140321\\sdk\\platform-tools\\adb.exe -P 5037 -s SA17C07838 shell am force-stop com.android.settings' exited with code 4294967295'; Stderr: 'error: device not found'; Code: '4294967295'
    at ADB.execFunc$ (C:\Users\hezj\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\system-calls.js:327:13)
    at tryCatch (C:\Users\hezj\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\hezj\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\hezj\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\hezj\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at <anonymous>
```
is it there some other solution?
