### ISSUE TITLE
Android 5.1 - When setting "language" and "locale" the emulator reboots and Appium fails to unlock the emulator screen

### ISSUE THREAD

**Issue by albedithdiaz** [appium/appium#6110]
When setting the 'language' and ‘locale’ in the Android emulators, the Appium driver reboots the emulator to set the locale but it is failing to unlock the screen right after. I found this issue while using Appium 1.4.16 and an Android 5.1 emulator. 

These where my desired capabilities:
        self.desired_capabilities = {}
        self.desired_capabilities['platformName'] = 'Android'
        self.desired_capabilities['platformVersion'] = '5.1'
        self.desired_capabilities['browserName'] = ''
        self.desired_capabilities['app']= '/Users/albedithdiaz/AlbeApp.apk'
        self.desired_capabilities['deviceName'] = 'Android Emulator'
        self.desired_capabilities['appiumVersion'] = '1.4.16'
        self.desired_capabilities['autoAcceptAlerts'] = "true"
        self.desired_capabilities['acceptSslCerts'] = 'true'
        self.desired_capabilities['language'] = 'EN'
        self.desired_capabilities['locale']= 'en_GB'

`error: Failed to start an Appium session, err was: Error: Screen did not unlock`

Here is my local Appium log:
[Appium_locale_failedToUnlockDevice.txt](https://github.com/appium/appium/files/120039/Appium_locale_failedToUnlockDevice.txt)

Here is an image of the emulator screen when the error happened:
![screen shot 2016-02-05 at 4 03 08 pm](https://cloud.githubusercontent.com/assets/7218814/12862750/6bb3e0ba-cc23-11e5-81e8-7b99ebcf7a41.png)

**Comment by karthick2313** [comment]
share the code/command you use to change locale

**Comment by imurchie** [comment]
This appears to be a problem with unlocking the phone in general, which gets less reliable the more recent the version of Android. We're trying to figure out how to do it well.

**Comment by jlipps** [comment]
This is fixed in 1.5.1

**Comment by FangXun0615** [comment]
It seems that this issue was not fixed totally,
we tried setting the 'language' and ‘locale’ in the Android emulators,but it didn't work
 'language': 'ja'
 'locale': 'ja_JP'
after reboot the Emulator ,the language of locked screen was ja,but after unlock the screen,the language was return to en

we are using  Appium v1.5.2 with Android Emulator
