### ISSUE TITLE
Encountered internal error running command: TypeError: Cannot read property 'send' of null Appium 1.5.1

### ISSUE THREAD

**Issue by whopiecat** [appium/appium#6251]
Issue : Encountered internal error running command: TypeError: Cannot read property 'send' of null

Running SafariLauncher on iPhone 5 (8.3) real device in a Selenium Grid.
iPhone 6 (8.4) (Appium 1.4.16) in Selenium Grid, works good

Unable to navigate to Google.

## Environment

* Appium v1.5.0-beta16 that exhibits the issue:
* Last Appium version that did not exhibit the issue-Appium 1.4.16 on os_webkit_debug_proxy 27753 
* OS/version used to run Appium: OSx Version: 10.11.3
* Node.js version: v5.0.0
* Mobile platform/version under test: iOS 8.
* Real device or emulator/simulator:Real Device
* Appium CLI :
* SafariLauncher

Link to Appium logs:
 <script src="https://gist.github.com/whopiecat/9cc5027fa31e278711ce.js"></script>

 Error: try to navigate to Google in Selenium Grid

**Comment by scottdixon** [comment]
Can you please provide a link to a gist of your Appium logs?

**Comment by whopiecat** [comment]
Sorry,
https://gist.github.com/whopiecat/9cc5027fa31e278711ce

Thanks for your help

**Comment by whopiecat** [comment]
Any update after the logs were provided?

**Comment by scottdixon** [comment]
It's in the queue - will get back to you when we investigate.

**Comment by whopiecat** [comment]
Thanks 

    On Wednesday, March 9, 2016 3:01 PM, Scott Dixon <notifications@github.com> wrote:
 

 It's in the queue - will get back to you when we investigate.—

**Comment by whopiecat** [comment]
This is only an issue when playing tests in the Selenium Grid. It seems the Desired Capabilities of the mobile device are being adjusted.

**Comment by whopiecat** [comment]
I noticed that the HTTP packet content for Appium 1.4.14 displays like below:
{"status":0,"value":{"build":{"version":"1.4.14","revision":"RealMobileDeviceUDID"}}}∑-Ûº¿¯¯

while the HTTP packet content for Appium 1.5.16 displays like below:
{"status":0,"value":{"build":{"version":"1.5.0-beta16","revision":**null**}},"sessionId":null}∑-u¨ô«ˆˆ

(null Bolded)
 
Maybe helps

**Comment by scottdixon** [comment]
Your logs mention `uid: 'udidOfRealDevice'` - Can you please confirm you're actually sending in the UDID? 

Does the real device do anything while the test runs? (i.e can you see it open the browser?)

Also, does the exact same script work on 1.4.16?

**Comment by whopiecat** [comment]
(1.) Yes, the correct UDID is displayed in the HTTP packet content.

(2.) I am testing with an iPhone 6 and an iPhone 5.
       The iPhone 6 (1.4.14 Appium) opens Sarafi Launcher > navigates to Google.com > Fills out form fields at URL. The iPhone 5 (1.5.0-beta 16 Appium) opens Sarafi Launcher > navigates to Apple.com > [hangs on Apple.com].

(3.) I need to get a more of a "matched environment" to you. I have updated to using the Appium 1.4.16 version of the **ios-webkit-debug-proxy-launcher.js** to support all iOS devices.

 (?) To properly support the Appium 1.5.0-beta 16 version, which version of the iso-webkit-debug-proxy or iso-webkit-debug-proxy-launcher, should be used (match version)?

(FYI) I used the newer style of providing desired capabilities as default capabilities in the Appium 1.5.0_beta 16 version, for the iPhone 5.

Please let me know how you would like me to set my environment up to provide actionable research for Appium.

**Comment by whopiecat** [comment]
The working iPhone 6 is on a standard ios-webkit-proxy-launcher port 27753
The not working iPhone 5 is on a non standard ios-webkit-proxy-launcher port 27755

**Comment by whopiecat** [comment]
Hello:
I installed the 1.5.1 version today

I am still seeing the error:
Encountered internal error running command: TypeError: Cannot read property 'send' of null

Thanks,
Paul

**Comment by imurchie** [comment]
I think I have fixed this. The fix is published in `appium-ios-driver@1.11.0`. If you are running from source you ought to be able update it there. If you are running from npm, you can re-install, adding the `--no-shrinkwrap` flag to get the latest.

**Comment by whopiecat** [comment]
Thanks,
I still see the same error with 1.5.1 after the --no-shrinkwrap install.
Is there a way to confirm the install of the appium-ios-driver version.

**Comment by whopiecat** [comment]
I pulled from source and see the appium-ios-driver@1.11.1 installed.

**Comment by whopiecat** [comment]
Now I see numerous calls of 
[Appium] Grid registration error: Cannot find proxy with ID =http://http:-1 in the registry.

Suggestions?

**Comment by whopiecat** [comment]
Is there an suggestion of how to fix the below Appium error?
Grid registration error: Cannot find proxy with ID =http://http:-1 in the registry

Thanks,
