### ISSUE TITLE
findElements returns irrelevent element when it should return an empty list

### ISSUE THREAD

**Issue by adamf663** [appium/appium#6269]
Items on screen are a listview where each subelement of the listview is a linear layout containing an android:id/title  and an optional android:id/summary.

Given a webelement pointing to the listview, findElementsById is called for android:id/summary. If the item is there, it is found correctly.  If there is no android:id/summary within the listview, appium goes crazy and returns an android:id/summary off an unrelated row (listview).

This problem also occurs in the notifications dropdown and also when xpath's are used.  
Attached are screen shot, pagesource, uix, the appium log and a logcat.

Code snipped to get the web elements with the listviews:

``` java
    Map<String, WebElement> title2Container = new HashMap<>();

        for ( WebElement rowContainer : driver.findElementById("android:id/list").findElements(By.className("android.widget.LinearLayout")) )
            title2Container.put( rowContainer.findElement( By.id("android:id/title")).getText(), rowContainer );
```

code snipped to get the android:id/summary from a list element:

``` java
    WebElement lookupContainer(String title ) {
        return title2Container.get(title);
    }
    public String getFieldByTitle( String title ){
        WebElement containerElem = lookupContainer(title);
        List<WebElement> valueElems = containerElem.findElements(By.id("android:id/summary"));
        if ( valueElems.size()==1 )
            return valueElems.get(0).getText();
        else
            return "";
```

Test snippets"

``` java
            log.info( "port = "+systemUpdate1.getFieldByTitle("Server port"));
// returns correct field, value of 80
            log.info( "relative path = "+systemUpdate1.getFieldByTitle("Relative path on server"));
// returns wrong field, ("HTTP") from wrong row
```

[wrongrow.zip](https://github.com/appium/appium/files/167613/wrongrow.zip)

**Comment by adamf663** [comment]
Any chance this might be fixed soon?  It is very annoying having automation that uses the notifications page fail because appium has returned irrelevant screen elements.

**Comment by imurchie** [comment]
Since we don't have an app with the specific layout you want, can you provide the code that fails when dealing with notifications?

**Comment by adamf663** [comment]
It's in the ticket.
The layout is android wide.  pull the notifications at any time, run uiautomatorviewer and you'll have a fresh example.

----- Original Message -----

**Comment by imurchie** [comment]
On my devices I don't see this. I have a scroll view that has nested framelayouts and linearlayouts. Some LinearLayouts have `android:id/title` text fields, and either `android:id/big_text` or `android:id/text` text fields. 

But I don't get the wrong elements from find operations.

**Comment by adamf663** [comment]
Please see my submission.  The problem is if there should be NO items returned.  If you do a findElements for a resource-id com.android.systemui:id/notification_stack_scroller,
you'll get one element, the entire list.  If you do a findElements from the com.android.systemui:id/notification_stack_scroller looking for class=android.widget.FrameLayout, you'll get an array of each row in the notifications.   The problem starts when you drill down into those frameLayouts.  Within each framelayout is a resource-id android:id/title.  Every notification row has this and appium is ok with that.  The problem is if you look for a resource-id android:id/text for the subsequent lines.  There can be multiple lines and appium handles that fine.  The problem is when there are NO lines.  Appium will return the first android:id/text if finds whether it is a child of the element you're doing the findElements on, or if there aren't any, appium will keep going and return one from another row!

----- Original Message -----

**Comment by adamf663** [comment]
attached is the module I use for notifications and another I use for a setup page.  The software update setup page has a field for "relative path on server" and if there isn't a path set, appium returns data from the next row, the network protocol.  I'm also attaching a capture of that screen's structure.

----- Original Message -----

**Comment by imurchie** [comment]
Finally got a reproducing example. Thanks for the pointers. My device is slightly different:

0. `com.android.systemui:id/scroll` element
    0. all sub-elements with id `com.android.systemui:id/content`
        0. `android:id/title` sub-element
        0. `android:id/text` sub-element 

The last will not fail if it isn't there, just get the next `android:id/text` element.

Working on fixing.

**Comment by adamf663** [comment]
It shouldn't return the next android:id/text element if there isn't one below the parent being queried! 
I think you're using a different definition of "fail".  :-)  Fail to me means returning wrong results.  Fail to you seems to mean not to return an error.

----- Original Message -----

**Comment by imurchie** [comment]
Yes, we are on the same page. I mean fail as in return a failing response. That is, not find an element.

It fails conceptually, in that it finds the wrong element.

**Comment by adamf663** [comment]
can it return an empty response instead of failing (tossing an exception)?

----- Original Message -----

**Comment by imurchie** [comment]
No. The Selenium specification requires it to throw an ElementNotFoundException ([spec](https://www.w3.org/TR/webdriver/#find-element)).

**Comment by adamf663** [comment]
seems reasonable.  can always catch it.

----- Original Message -----

**Comment by imurchie** [comment]
The problem is with Android, unfortunately. Appium is just using the UiAutomator method to get the children with a particular selector. 

I will keep digging to try to figure out a way to fix the Android bug.

**Comment by adamf663** [comment]
My planed workaround was to compare the location/dimension of found element with parent.  If the found element is outside the parent's bounds, discard it.


----- Original Message -----

**Comment by imurchie** [comment]
Yes, that's my next workaround, if I can't patch the Android code.

**Comment by imurchie** [comment]
I've published a fix as `appium-android-bootstrap@2.7.0`. Are you running from source? Can you update that package and try? Thanks.

**Comment by adamf663** [comment]
I have tried to use 1.5.x and it still crashes constantly making it utterly unuseable.

I think I may have located the cause -- the failures always occur when I test with two phones.
I run two appium servers on different ports.  I recall somewhere where 1.5.x tries to reuse the same adb.  Do you recall that and know where I can get a fix so I can use 1.5.x with multiple phones?  This is a complete showstopper for using 1.5.x.

I build via linuxbrew and npm.  I have all the source code left behind.  I can use your patch if you tell me the commands I need to build it.

----- Original Message -----

**Comment by imurchie** [comment]
I have not run into Appium 1.5.x trying to use the same adb instance for multiple Appium instances. I would love to try to get to the bottom of it, but without the logs or more information, I really can't.

As for getting the patch, if you're running from npm, just do `npm install appium --no-shrinkwrap` (with `-g` if it is global).

**Comment by adamf663** [comment]
Got 1.5.1, but I still can't use appium 1.5.x due to incessant crashes.

I'm not sure the details here, but this is consistent with the crashes I see every time I've tried to use appium 1.5.x:
the appium log:
2016-03-30 13:57:21:265 - [debug] [ADB] Running /opt/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","651365571","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
2016-03-30 13:57:41:278 - [debug] [ADB] Running /opt/android-sdk-linux/platform-tools/adb with args: ["-P",5037,"-s","651365571","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
2016-03-30 13:58:01:337 - [HTTP] <-- GET /wd/hub/session/f46a37a1-226d-4dc1-845f-198063583b0b/screenshot 500 40085 ms - 531 
Error: write EPIPE
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at WriteWrap.afterWrite (net.js:763:14)

Error returned to java:
2016-03-30 07:58:01.183 DEBUG Settings_Phone_Page(Device(651363722)) - scrollTo: About phone
2016-03-30 07:58:01.342 DEBUG Thread(Device(651365571)) - An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: Command '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s 651365571 shell /system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png' timed out after 20000ms{"stdout":"override rw-rw-r-- root:root for '/data/local/tmp/screenshot.png'? ","stderr":"","code":null} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 40.10 seconds
Build info: version: '2.49.1', revision: '808c23b0963853d375cbe54b90bbd052e2528a54', time: '2016-01-21 09:37:52'
System info: host: 'qa1404test', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-57-generic', java.version: '1.8.0_74'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{appPackage=com.android.settings, networkConnectionEnabled=true, noSign=true, warnings={}, databaseEnabled=false, deviceName=651365571, platform=LINUX, appActivity=.Settings, desired={appPackage=com.android.settings, appActivity=.Settings, noSign=true, newCommandTimeout=30000, platformName=Android, udid=651365571, deviceName=Android phone}, newCommandTimeout=30000, platformVersion=5.1.1, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformName=Android, udid=651365571}]
Session ID: f46a37a1-226d-4dc1-845f-198063583b0b
2016-03-30 07:58:01.347 DEBUG Device(651365571) - Closing Device(651365571)
Mar 30, 2016 7:58:01 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:5001: Connection reset
Mar 30, 2016 7:58:01 AM org.apache.http.impl.execchain.RetryExec execute


Perhaps it was a screenshot operation that crashed appium.  It is unacceptable that appium does not recover.



----- Original Message -----

**Comment by adamf663** [comment]
This was the fix for the multiple instances bug:
https://raw.githubusercontent.com/appium/appium-android-driver/99ce7dcffb762706dd5c7e43130dc6be270dee57/lib/driver.js
I didn't save the issue it is associated with.  The fix isn't in 1.5.1.

----- Original Message -----

**Comment by jeangb** [comment]
Hello, I  the same issue that @adamf663 and it's very annonying that the findElementById doesn't return null and instead returns a child from a cousin of the parent...
A workaround is using findElementByXpath but I would really prefer using ById.
Do you have any news on this @imurchie ? I'm using Appium v1.5.3 on windows, and running tests on 1 Android device for now.

**Comment by appiumnovice** [comment]
Just for information, if you find a workaround for this issue, you can close the similar issue #6945.

**Comment by adamf663** [comment]
After months where appium would crash if I used adb, I decided to dump appium.   That crash is fixed, but I don't  forgive the 3 months of down time.  That's my workaround.

I thought the irrelevant element return was fixed.

----- Original Message -----

**Comment by tfcardoso** [comment]
This still happens.

I have a WebElement myElement of type android.widget.RelativeLayout. 

And when I search for:

    myElement.findElement(By.id("id"))

I naturally get NoSuchElement Exception. But if I do

    myElement.findElements(By.id("id"))

it replies with one element, that has x,y points outside of myElement.

It is no problem for me, I just have to use findElement and catch exception, but it still a bug

**Comment by dpgraham** [comment]
@tfcardoso What is the ID of the element that is being located by `myElement.findElements(By.id("id"))`.

**Comment by tfcardoso** [comment]
Hi @dpgraham, this happens in more than one place, but for example in screen attached, if I get a FrameLayout element and if I query for the tv_duration id (with findElements) then it always returns an element if if inside that FrameLayout, one does not exists.

With the findElement everything works properly.

[https://image.prntscr.com/image/DnZhJdfuTBaDzWc0sLvZpQ.png](url)

**Comment by dpgraham** [comment]
@tfcardoso Can you provide the source XML? It looks like what's happening is it's not isolating the xpaths to within the context `myElement`.

**Comment by adamf663** [comment]
I thought this was fixed back in version 1.5.0.4 or so.
The problem is if findElements should return null but returns an out of bounds element instead.
For example given a structure:
  A
    1
      a
      b
    2
  B
    1 
      c

If it is called on A1, it returns a and b as expected.
The problem si if called on A2, findElements returns c instead of null.

----- Original Message -----

**Comment by mykola-mokhnach** [comment]
Is the issue still relevant? Can it be reproduced with UIA2 backend in the recent Appum version?

**Comment by adamf663** [comment]
I dumped appium after around version 1.5 (1.4?)  because it had been unusable for nearly a year.
You'll have to test it yourself;  I gave clear instructions on the bug, basically:
    Notification A
       item A
    Notification B
    Notification C
      item C

The bug is that a query of "Notification B"'s children returns item C.

----- Original Message -----

**Comment by mykola-mokhnach** [comment]
I don't observe such issues in UIA2. Closing as obsolete
