### ISSUE TITLE
Starting Appium fails on Android N (Nougat)

### ISSUE THREAD

**Issue by jnahansen** [appium/appium#6665]
## The problem
Android N is failing or seems unsupported

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

I cannot run even the simplest Appium test on Android N (Developer Preview 4)

## Environment

* Appium version (or git revision) that exhibits the issue: v1.5.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOSX El Capitan
* Node.js version (unless using Appium.app|exe): v4.4.5
* Mobile platform/version under test: Android N (Developer Preview4)
* Real device or emulator/simulator: Nexus5X (real device)
* Appium CLI or Appium.app|exe: CLI

## Details

Getting following error:
debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/jhansen/android/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb with args: ["-P",5037,"-s","00a9ebf92cb2a949","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running /Users/jhansen/android/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb with args: ["-P",5037,"-s","00a9ebf92cb2a949","install","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[debug] [ADB] Running /Users/jhansen/android/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb with args: ["-P",5037,"-s","00a9ebf92cb2a949","install","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/Users/jhansen/android/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -P 5037 -s 00a9ebf92cb2a949 install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk' exited with code 1{"stdout":"","stderr":"Failed to install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\n","code":1}
    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

[files.zip](https://github.com/appium/appium/files/366372/files.zip)

## Code To Reproduce Issue [ Good To Have ]

I start appium and run a python test as follows:

# NOTE: code to reproduce is in attached zipfile
>appium &
>py.test -s  android_simple.py

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
It tries to install Appium settings module and somehow fails to do it since the module is already installed. Have you tried to remove it manually

```bash
adb uninstall io.appium.settings
```

and restart the script?

**Comment by droca** [comment]
I'm using Appium with Cucumber and besides this issue, I found the same problem when appium tries to install `io.appium.unlock` as well. As a workaround I manually uninstall `io.appium.settings` and `io.appium.unlock` on the `Before` Cucumber hook.

**Comment by imurchie** [comment]
Unfortunately I don't seem to be able to get a system image for API 24, so I can't try this out and get to the bottom of it.

Any chance you want to delve into the problem and see if you can get to a solution? We can help along the way, if possible.

**Comment by vaishnavik88** [comment]
I am also facing this issue with Android N. I tried removing io.appium.settings and io.appium.unlock. But now facing below error. I am pretty new to Appium and mobile testing. Any help will be much appreciated. Thanks.

### Details
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[Appium] Request to register with grid was unsuccessful: Error: connect ECONNREFUSED 127.0.0.1:4444
[debug] [Appium] Hub down or not responding: Error: connect ECONNREFUSED 127.0.0.1:4444
[Appium] Request to register with grid was unsuccessful: Error: connect ECONNREFUSED 127.0.0.1:4444
[debug] [Appium] Hub down or not responding: Error: connect ECONNREFUSED 127.0.0.1:4444
[Appium] Request to register with grid was unsuccessful: Error: connect ECONNREFUSED 127.0.0.1:4444
[debug] [Appium] Hub down or not responding: Error: connect ECONNREFUSED 127.0.0.1:4444
[debug] [Appium] Appium successfully registered with the grid on 127.0.0.1:4444
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Selenium_server\\apk\\qa-approvalmode0_service.ltm.nurago.com_stable_v_1_23_8.apk","appPackage":"com.nurago.mobilemonitor.qa","appActivity":"com.nurago.mobilemonitor.ui.DefaultActivity","platformName":"Android","version":"6.0.1","deviceName":"HT4AHJT06375"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Selenium_serve...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   app: 'C:\\Selenium_server\\apk\\qa-approvalmode0_service.ltm.nurago.com_stable_v_1_23_8.apk'
[Appium]   appPackage: 'com.nurago.mobilemonitor.qa'
[Appium]   appActivity: 'com.nurago.mobilemonitor.ui.DefaultActivity'
[Appium]   platformName: 'Android'
[Appium]   version: '6.0.1'
[Appium]   deviceName: 'HT4AHJT06375'
[Appium]   udid: 'HT4AHJT06375'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version.
[BaseDriver] Session created with session id: ecb69453-7dae-4d5e-873d-965decd01ac2
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: HT4AHJT06375
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to HT4AHJT06375
[BaseDriver] Using local app 'C:\Selenium_server\apk\qa-approvalmode0_service.ltm.nurago.com_stable_v_1_23_8.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","install","C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","install","C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","getprop","ro.build.version.release"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","dumpsys","window"]
[AndroidDriver] Unlocking screen
[debug] [AndroidDriver] Screen is locked, trying to unlock
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","am","force-stop","io.appium.unlock"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Device API level: 24
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","am","start","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Device API level: 24
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","am","start","-n","io.appium.unlock/.Unlock","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","dumpsys","window"]
[debug] [AndroidDriver] Screen unlocked successfully
[AndroidDriver] Remote apk path is /data/local/tmp/951a81c2c0675e14e6707c9f8d10dac4.apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","ls","/data/local/tmp/951a81c2c0675e14e6707c9f8d10dac4.apk"]
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","ls","/data/local/tmp/951a81c2c0675e14e6707c9f8d10dac4.apk"]
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command 'C:\\Users\\v.krishnamurthy\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s HT4AHJT06375 shell ls /data/local/tmp/951a81c2c0675e14e6707c9f8d10dac4.apk' exited with code 1{"stdout":"","stderr":"ls: /data/local/tmp/951a81c2c0675e14e6707c9f8d10dac4.apk: No such file or directory\r\n","code":1}
    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)
    at tryCatch (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at run (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:104:47)
    at C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:115:28
    at flush (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[HTTP] <-- POST /wd/hub/session 500 7567 ms - 523
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Selenium_server\\apk\\qa-approvalmode1_service.ltm.nurago.com_stable_v_1_23_8.apk","appPackage":"com.nurago.mobilemonitor.qa","appActivity":"com.nurago.mobilemonitor.ui.DefaultActivity","platformName":"Android","version":"6.0.1","deviceName":"HT4AHJT06375"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Selenium_serve...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   app: 'C:\\Selenium_server\\apk\\qa-approvalmode1_service.ltm.nurago.com_stable_v_1_23_8.apk'
[Appium]   appPackage: 'com.nurago.mobilemonitor.qa'
[Appium]   appActivity: 'com.nurago.mobilemonitor.ui.DefaultActivity'
[Appium]   platformName: 'Android'
[Appium]   version: '6.0.1'
[Appium]   deviceName: 'HT4AHJT06375'
[Appium]   udid: 'HT4AHJT06375'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version.
[BaseDriver] Session created with session id: 3b46711f-c572-4134-af0e-ca1dbe4f71d5
[debug] [AndroidDriver] Getting Java version
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 6900 ms - 83
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: HT4AHJT06375
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to HT4AHJT06375
[BaseDriver] Using local app 'C:\Selenium_server\apk\qa-approvalmode1_service.ltm.nurago.com_stable_v_1_23_8.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","install","C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","install","C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command 'C:\\Users\\v.krishnamurthy\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s HT4AHJT06375 install C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk' exited with code 1{"stdout":"","stderr":"Failed to install C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\r\n","code":1}
    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)
    at tryCatch (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at run (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:104:47)
    at C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:115:28
    at flush (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[HTTP] <-- POST /wd/hub/session 500 1707 ms - 910
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Selenium_server\\apk\\qa-approvalmode2_service.ltm.nurago.com_stable_v_1_23_8.apk","appPackage":"com.nurago.mobilemonitor.qa","appActivity":"com.nurago.mobilemonitor.ui.DefaultActivity","platformName":"Android","version":"6.0.1","deviceName":"HT4AHJT06375"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Selenium_serve...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   app: 'C:\\Selenium_server\\apk\\qa-approvalmode2_service.ltm.nurago.com_stable_v_1_23_8.apk'
[Appium]   appPackage: 'com.nurago.mobilemonitor.qa'
[Appium]   appActivity: 'com.nurago.mobilemonitor.ui.DefaultActivity'
[Appium]   platformName: 'Android'
[Appium]   version: '6.0.1'
[Appium]   deviceName: 'HT4AHJT06375'
[Appium]   udid: 'HT4AHJT06375'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: version.
[BaseDriver] Session created with session id: 0b079489-de9d-4987-8dc2-256b348713a7
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: HT4AHJT06375
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to HT4AHJT06375
[BaseDriver] Using local app 'C:\Selenium_server\apk\qa-approvalmode2_service.ltm.nurago.com_stable_v_1_23_8.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","install","C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[debug] [ADB] Running C:\Users\v.krishnamurthy\AppData\Local\Android\sdk\platform-tools\adb.exe with args: ["-P",5037,"-s","HT4AHJT06375","install","C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command 'C:\\Users\\v.krishnamurthy\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s HT4AHJT06375 install C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk' exited with code 1{"stdout":"","stderr":"Failed to install C:\\Users\\v.krishnamurthy\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-driver\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\r\n","code":1}
    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)
    at tryCatch (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at run (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:104:47)
    at C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\es6.promise.js:115:28
    at flush (C:\Users\v.krishnamurthy\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\node_modules\core-js\library\modules\$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[HTTP] <-- POST /wd/hub/session 500 1640 ms - 910

**Comment by dtopuzov** [comment]
+1 with the same problem.

**Comment by securessid** [comment]
@vaishnavik88 , @dtopuzov 
Is the thing mentioned above "{"stdout":"","stderr":"ls: /data/local/tmp/951a81c2c0675e14e6707c9f8d10dac4.apk: No such file or directory\r\n","code":1}" working fine with the work around/node.js change? I couldn't make it out from the link @dtopuzov mentioned.

Thanks in advance.

**Comment by draganglumac** [comment]
Same problem here.

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug

**Comment by cschabetsberger-micro-focus** [comment]
I was able to reproduce this issue and fixed it, so I filed a pull request: https://github.com/appium/appium-adb/pull/171

**Comment by vchimev** [comment]
Hello,

I applied the changes from https://github.com/appium/appium-adb/pull/171 locally, but now I am stuck at:
```
Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/Users/vchimev/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell ls /data/local/tmp/fd6c3a7cad25102c9f2248b12b7820f3.apk' exited with code 1{"stdout":"","stderr":"ls: /data/local/tmp/fd6c3a7cad25102c9f2248b12b7820f3.apk: No such file or directory\n","code":1}
```
Full log here: https://gist.github.com/vchimev/329b8c1cc59dbf44cea3e6e2ba6fd5c9.

Any ideas? CC: @cschabetsberger-micro-focus

Many thanks.

**Comment by imurchie** [comment]
https://github.com/appium/appium-adb/pull/172 should fix that.

**Comment by rashia** [comment]
@imurchie  even appium/appium-adb#172 doesn't fix my problem.
I'm using Appium 1.4.16 on windows, and updated appium-adb to the latest.

**Comment by wanglin1985** [comment]
@imurchie, I'm using Apium 1.5.3 on MacOSX, and this issues still exists.(python code)
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/Users/lin/android-sdk-macosx/platform-tools/adb -P 5037 -s 192.168.56.102:5555 install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk' exited with code 1{"stdout":"","stderr":"Failed to install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\n","code":1}
    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)

**Comment by wanglin1985** [comment]
I'm using Appium 1.5.3 on Mac OSX, this issue still exists.(python code)
[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: Command '/Users/username/android-sdk-macosx/platform-tools/adb -P 5037 -s xxx.xxx.xx:5555 install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk' exited with code 1{"stdout":"","stderr":"Failed to install /usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]\n","code":1}
    at ADB.execFunc$ (lib/tools/system-calls.js:189:13)

**Comment by imurchie** [comment]
@rashia What do you mean by updating `appium-adb` to the latest? How did you do this?

@wanglin1985 The changes will not automatically be available in older versions of Appium.

**Comment by droca** [comment]
For me it's working fine, thx for the effor 👍

**Comment by rashia** [comment]
@imurchie 
Updated  `appium-adb ` using command `npm install appium-adb@2.6.13`

**Comment by imurchie** [comment]
@rashia That will not update in a way that the server will be able to identify. You need to either re-install the server (with the `--no-shrinkwrap` flag) or go into your Appium installation and run the above npm install command.

**Comment by bhadrikishore** [comment]
I am using appium version 1.4.13.1 on window 7. But i am getting below error while execution.

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not extract PIDs from ps output. PIDS: [], Procs: ["bad pid 'uiautomator'"]) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 31.07 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_91'
Driver info: io.appium.java_client.android.AndroidDriver

Please help me how to resolve this issue?

**Comment by vikramvi** [comment]
@bhadrikishore always use latest version of appium and please open new issue instead of commenting on closed one.

**Comment by Kalyan1989** [comment]
We have a new GUI tool that you can download at: https://github.com/appium/appium-desktop/releases/latest

**Comment by Kalyan1989** [comment]
We have a new GUI tool that you can download at: https://github.com/appium/appium-desktop/releases/latest

**Comment by Elanthingal** [comment]
@Kalyan1989 is that link is usefull to automate nougat without any issue ???

**Comment by rahuln04** [comment]
I am trying to launch Appium session using 1.4.13.1(Ophiuchus) version with lower mobile OS versions  before 7 it works perfectly fine. When i tried with Android Nougat 7 version it fails.. I get the below exception. Kindly help how to fix it as i need to run the tests on Android 7 version.

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not extract PIDs from ps output. PIDS: [], Procs: ["bad pid 'uiautomator'"]) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 14.25 seconds

**Comment by bhadrikishore** [comment]
Hi rahul,

Please mention below mandatory details in desired capabilities.

App----> apk path
Apppackage------>app package info
App activity
Udid----> device id(adb device)

capabilitiesForAppium.setCapability(MobileCapabilityType.APP_PACKAGE,
appPackage);
    capabilitiesForAppium.setCapability(MobileCapabilityType.APP, appPath);
capabilitiesForAppium.setCapability(MobileCapabilityType.APP_ACTIVITY,
appActivity);
capabilitiesForAppium.setCapability("udid", udid);

I hope it should work.

Thanks,
Bhadri Kishore

**Comment by ios-dev-newbie** [comment]
I am using Appium version: 1.7.1
node: 9.3.0

I am also not able to launch an application in android N.
log can be found in attached file.
[nougat_error.txt](https://github.com/appium/appium/files/1688853/nougat_error.txt)

Please let me know what changes need to perform on Android N as it is working perfectly below Android N.

**Comment by ios-dev-newbie** [comment]
I have solved my problem of starting of appium on Android-N with below setting
npm uninstall -g appium && npm install -g appium --no-shrinkwrap
And updated the "automationName" to "UiAutomator2".

But Now facing another issue.
Please check below gist file.
https://gist.github.com/ios-dev-newbie/551c551f3d5e1b64c259118d3c1754cb

**Comment by sudamaHingave** [comment]
I'm Also facing same issue my appium version is  1.7.2
