### ISSUE TITLE
adb disconnects on macOS Sierra - Appium Terminates the server instance

### ISSUE THREAD

**Issue by Benn-Matthew** [appium/appium#6944]
## The problem

adb disconnects on macOS Sierra - so appium terminates the server instance. Any fix or workaround available - PFA log
## Environment
- Appium version : Version 1.5.3 (Ara)
- Desktop OS/version used to run Appium: Mac OS Serria
- Node.js version (unless using Appium.app|exe):  v4.2.4
- Mobile platform/version under test: Android Kitkat
- Real device or emulator/simulator: Real Device - Nexus 4
- Appium CLI or Appium.app|exe: Appium.app
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

https://gist.github.com/Benn-Matthew/938271e7d7689ab06898086accf8c4fd
## Code To Reproduce Issue [ Good To Have ]

Run Appium test script in batch. Env - Mac OS Sierra

**Comment by JaniJegoroff** [comment]
This is indeed annoying. Google is working on this and there should be fix available for testing in Android Studio Preview channel. Not sure when it will be released for Android SDK Manager though.

https://code.google.com/p/android/issues/detail?id=219085#c29

**Comment by jorisw** [comment]
So, is the fix in adb or in Google USB Driver or where? My adb version (1.0.36)  has not changed, even in SDK r25, and my adb still won't recognize my devices. Whereas my Mac running El Capitan does.

**Comment by JaniJegoroff** [comment]
I have no issues on Sierra anymore after installing platform tools from Preview channel.

```
Android Debug Bridge version 1.0.36
Revision 19394af606f6-android
```
<img width="610" alt="screen shot 2016-12-08 at 14 17 11" src="https://cloud.githubusercontent.com/assets/2363231/21013224/1d3aa872-bd51-11e6-99cb-df2c4f138aef.png">

**Comment by simonjgamer** [comment]
I do not seem to have Tools (Preview Channel) in my SDK manage. Although Enable preview is ticked in preference of SDK manager. Any idea?

**Comment by plaudev** [comment]
I have platform-tools 25.0.5 and still issue not fixed

**Comment by jboffel** [comment]
Personally having platform-tools 25.0.3 and adb is just terribly unstable used with appium. Impossible to run tests...

**Comment by JaniJegoroff** [comment]
@plaudev @jboffel Just out of curiosity, what's the exact version number of `adb` you are using?

I'm still using below version from beta channel and no issues at all.
```
Android Debug Bridge version 1.0.36
Revision 19394af606f6-android
```

**Comment by jboffel** [comment]
Android Debug Bridge version 1.0.36
Revision 0e9850346394-android

Appium 1.6.3

using real device android 5.0.2

**Comment by JaniJegoroff** [comment]
@jboffel Interesting, I'm using real Android device (5.0.2) as well and Appium 1.6.3/4.

I'm going to update my platform-tools, run my tests and look if I come across with any problems.

**Comment by JaniJegoroff** [comment]
I have no problems after updating platform-tools to 25.0.3, tests are rock solid.
```
Janis-MacBook-Pro:bdd janijegoroff$ adb version
Android Debug Bridge version 1.0.36
Revision 0e9850346394-android
```
Our CI machine (Mac El Capitan) is using older ADB (version 1.0.32) and is rock solid as well.

**Comment by plaudev** [comment]
Android Debug Bridge version 1.0.36
Revision 0e9850346394-android
