### ISSUE TITLE
API calls are way too slow

### ISSUE THREAD

**Issue by Mygod** [appium/appium#6969]
## The problem

I'm using java-client to do some automation with appium and it seems that it's way too slow.

For example, `RemoteWebElement.click` takes 0.4 seconds on average and can take up to 3 seconds sometimes. I'm running on a emulator and it doesn't make sense that this operation is so slow.
## Environment
- java client build version or git revision if you use some shapshot:4.1.2
- Appium version (or git revision) that exhibits the issue:1.6.0-beta3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:Linux Mint 18 (Ubuntu 16.04 x64)
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Android emulator API 24
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: CLI (launched using `AppiumDriverLocalService`)
## Link to Appium logs

```
2016-10-08 05:20:45:796 - info: [HTTP] --> POST /wd/hub/session/2c73a0a8-c376-44ce-96a5-f2ed5d3b1900/element/44/click {"id":"44"}
2016-10-08 05:20:45:797 - info: [MJSONWP] Calling AppiumDriver.click() with args: ["44","2c73a0a8-c376-44ce-9...
2016-10-08 05:20:45:798 - info: [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"44"}}
2016-10-08 05:20:45:799 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"44"}}
2016-10-08 05:20:45:800 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2016-10-08 05:20:45:800 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
2016-10-08 05:20:46:128 - info: [debug] [AndroidBootstrap] Received command result from bootstrap
2016-10-08 05:20:46:129 - info: [MJSONWP] Responding to client with driver.click() result: true
2016-10-08 05:20:46:129 - info: [HTTP] <-- POST /wd/hub/session/2c73a0a8-c376-44ce-96a5-f2ed5d3b1900/element/44/click 200 333 ms - 76 
2016-10-08 05:20:46:130 - info: [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
```
## Code To Reproduce Issue [ Good To Have ]

`element.click();`

P.S. Original issue: https://github.com/appium/java-client/issues/484

**Comment by mykola-mokhnach** [comment]
Which backend you use for Android automation: UiAutomation1 (the default one), Selendroid or UiAutomation2?

**Comment by Mygod** [comment]
Probably the default one. Maybe I should try UA2?

**Comment by mykola-mokhnach** [comment]
We had similar problem with UiAutomation1 and Android 5.0+. That is why we have switched to Selendroid. It has many limitations, but it's fast. UA2 should be ok from this perspective and code migration process from UA1 should not be too painful.

**Comment by chrisie** [comment]
We're seeing a similar problem with Appium and iOS (so the problem is not just the Android automation). We recently upgraded from Appium 1.4.13 to 1.6.0 and the difference in speed is huge...

**Comment by Mygod** [comment]
@mykola-mokhnach Thanks! I tried out UA2 but [it's so broken](https://github.com/appium/appium-uiautomator2-server/issues/27) that it's not useful for me. :disappointed:

**Comment by Mygod** [comment]
Update: UA2 is now fixed and it's much faster (0.01s - 0.02s per click instead of 0.1s - 3s)

**Comment by VasilijSviridov** [comment]
what about iOS automation and 1.6 appium, any help on this ?

**Comment by idxn** [comment]
I've still see the problem on UA2 sometimes for the click api as the log provided below.
Appium version: 1.6.4
Android emulator version 7.1.1
It takes almost 2 second for click an element.

normal response
https://gist.github.com/idxn/cd7bba360f7579d98f31e516ecd79d5f

slow response
https://gist.github.com/idxn/cd7bba360f7579d98f31e516ecd79d5f

**Comment by robertluo1949** [comment]
How to switch UiAutomation1 to UiAutomation2 on appium project ?

**Comment by idxn** [comment]
@robertluo1949 check https://github.com/appium/appium-uiautomator2-server/wiki

**Comment by robertluo1949** [comment]
@idxn There is no useful about UIAutomator2.
We are find that is is cause of animations. My andriod app need launch  animations on many pages,howover ,it use many time to excute scripts.

**Comment by idxn** [comment]
@robertluo1949  I'm not quite sure what you want then. You asked how to switch from UA1 to UA2. It is stated in the wiki as follows:

> Based on the automationName property in the desired capabilities, appium redirects to the corresponding driver module (by default appium passes to appium-android-driver on the absence of automationName)
> If the automationName is uiautomator2 then appium redirects to appium-uiautomator2-driver to create the new session.
