### ISSUE TITLE
Error while using sendKeys method on iOS simulator

### ISSUE THREAD

**Issue by PeterGolf** [appium/appium#7113]
## The problem

I have a problem while using sendKeys method on simulator. On real device it works correct.
Error:

[JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"D1FE8CA8-EF43-49D7-AC22-4FE6FA1B5EB8","status":13}
[HTTP] <-- POST /wd/hub/session/d3895ae5-1309-4850-afbf-1752d4f1ac18/element/82335E7E-5FCA-40A0-86FF-6A0F406CF741/value 500 5679 ms - 304 
[HTTP] --> DELETE /wd/hub/session/d3895ae5-1309-4850-afbf-1752d4f1ac18 {}
## Environment
- Appium version: 1.6.0 Beta3
- Node.js version (unless using Appium.app|exe):
- simulator: 9.3 and 10.0

**Comment by imurchie** [comment]
Any chance of getting the server logs, as a [gist](https://gist.github.com)? Without them we cannot tell what is going on.

**Comment by PeterGolf** [comment]
@imurchie how can i get all server logs?

**Comment by imurchie** [comment]
Wherever you run Appium. They should start with something like

```
[Appium] Welcome to Appium v1.6.0 (REV 2176894a5be5da17a362bf3f20678641a78f4b69)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by PeterGolf** [comment]
https://gist.github.com/PeterGolf/4496042021728bd832422b35cb4708e5

**Comment by PeterGolf** [comment]
@imurchie are this logs is that what you need to find out what is going on?

**Comment by PeterGolf** [comment]
@imurchie is it looks like a bug or i have made some mistake in capabilities or something else?

**Comment by imurchie** [comment]
No, this is not a bug. You need to click on the text field before sending keys to it. This should be fixed on the server side.

**Comment by PeterGolf** [comment]
@imurchie still not working: 
Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}
Command duration or timeout: 5.92 seconds

**Comment by PeterGolf** [comment]
@imurchie need your help :(

**Comment by imurchie** [comment]
Was the keyboard present?

**Comment by PeterGolf** [comment]
Yes

**Comment by VivaLosDoyers** [comment]
Is your simulator set to "Connect Hardware Keyboard"? Try turning that off.

If that fixes your problem, this is actually a a bug in XCTest, where tests will fail in Xcode as well, and thus this is likely not an Appium bug.

**Comment by imurchie** [comment]
Sometimes having "slow animations" on will make the keyboard coming up so slow that the command can fail, too.

**Comment by PeterGolf** [comment]
@imurchie i tried make it in debug mode, also the same error, so will try to set off "Connect Hardware Keyboard"

**Comment by PeterGolf** [comment]
@VivaLosDoyers how can i turn off "Connect Hardware Keyboard" in xcode 8?

**Comment by VivaLosDoyers** [comment]
@PeterGolf it's in the menu in the simulator.

![screen shot 2016-10-28 at 1 47 16 am](https://cloud.githubusercontent.com/assets/20602881/19800679/9a6fc898-9cb0-11e6-9dfa-646b07114d4a.png)

**Comment by PeterGolf** [comment]
@VivaLosDoyers can't find this menu in Xcode 8 :(

**Comment by imurchie** [comment]
It is on the simulator, not Xcode. Run the simulator, and that menu will be there.

**Comment by PeterGolf** [comment]
@imurchie when i start simulator app from: /Applications/Xcode.app/Contents/Developer/Applications , it is starting iPhone 6 (iOS 10.0) simulator. No menu :(

**Comment by imurchie** [comment]
There is no menu across the top of the screen? Like in:

![screenshot 2016-10-28 11 58 10](https://cloud.githubusercontent.com/assets/2614354/19802874/1c48b410-9d06-11e6-99b7-b744789d7cbf.png)

**Comment by PeterGolf** [comment]
@imurchie Find it...thx a lot! I just new in Mac OS

**Comment by PeterGolf** [comment]
But the same problem...

**Comment by PeterGolf** [comment]
Any more ideas how to solve this problem?

**Comment by imurchie** [comment]
I just want to confirm. You are finding a text field, clicking on it, and the software keyboard comes up on the simulator, then you are sending the text?

**Comment by mbaglay** [comment]
Have the same problem. First tapping an input field does not work. Appium "does" tap and waits for keyboard. If I click fast enough this field keyboard appears and whole the test goes well, including all next taps.

Code:
`usernameField.tap(1,500);

usernameField.sendKeys(username);`

Here is the logs of server

`[HTTP] --> POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/touch/perform {"actions":[{"action":"press","options":{"element":"E82546B7-E9E4-4090-A071-B001F725C885"}},{"action":"wait","options":{"ms":500}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [XCUITest] Executing command 'performTouch'
[JSONWP Proxy] Proxying [POST /tap/E82546B7-E9E4-4090-A071-B001F725C885] to [POST http://localhost:8100/session/EEFD273A-0CE4-4344-B31D-2896A7A4F55C/tap/E82546B7-E9E4-4090-A071-B001F725C885] with body: {}
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"EE...
[MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/touch/perform 200 828 ms - 74 
[HTTP] --> POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/timeouts {"type":"implicit","ms":0}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"7d1e5af9-280...
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 0ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/timeouts 200 1 ms - 76 
[HTTP] --> GET /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/context {}
[MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["7d1e5af9-2805-4a1d-b2a1-8...
[debug] [XCUITest] Executing command 'getCurrentContext'
[MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/context 200 1 ms - 84 
[HTTP] --> POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/elements {"using":"class name","value":"XCUIElementTypeTextField"}
[MJSONWP] Calling AppiumDriver.findElements() with args: ["class name","XCUIElementT...
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/EEFD273A-0CE4-4344-B31D-2896A7A4F55C/elements] with body: {"using":"class name","valu...
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"EC281...
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"EC281187-A733-...
[HTTP] <-- POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/elements 200 264 ms - 169 
[HTTP] --> POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/timeouts {"type":"implicit","ms":1000}
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"7d1e5af9-...
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 1000ms
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/timeouts 200 1 ms - 76 
[HTTP] --> POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/element/EC281187-A733-4D23-B43C-5A99A56B3BD0/value {"id":"EC281187-A733-4D23-B43C-5A99A56B3BD0","value":["CSVTE_11_HP_08"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["CSVTE_11_HP_08"],"EC2811...
[debug] [XCUITest] Executing command 'setValue'
[JSONWP Proxy] Proxying [POST /element/EC281187-A733-4D23-B43C-5A99A56B3BD0/value] to [POST http://localhost:8100/session/EEFD273A-0CE4-4344-B31D-2896A7A4F55C/element/EC281187-A733-4D23-B43C-5A99A56B3BD0/value] with body: {"value":["C","S","V","T","...
[JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com....
[HTTP] <-- POST /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/element/EC281187-A733-4D23-B43C-5A99A56B3BD0/value 500 5960 ms - 304
HTTP] --> GET /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [GET /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/screenshot] to [GET http://localhost:8100/session/EEFD273A-0CE4-4344-B31D-2896A7A4F55C/screenshot] with body: {}
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0...
[JSONWP Proxy] Replacing sessionId EEFD273A-0CE4-4344-B31D-2896A7A4F55C with 7d1e5af9-2805-4a1d-b2a1-84345c32764f
[HTTP] <-- GET /wd/hub/session/7d1e5af9-2805-4a1d-b2a1-84345c32764f/screenshot 200 39 ms - 106594 `

**Comment by imurchie** [comment]
@mbaglay I don't understand what you mean by "if I click fast enough".

**Comment by mbaglay** [comment]
@imurchie I mean before an error and end of scenario

**Comment by imurchie** [comment]
You should be able to click and then wait for the keyboard to come up.

**Comment by mbaglay** [comment]
@imurchie so I did. but in automated state this does not work

**Comment by imurchie** [comment]
I mean that you can use a wait method to wait for the keyboard element to
be available. Totally automatable.

**Comment by mbaglay** [comment]
@imurchie changed code

`
        usernameField.tap(1, 500);
        WebDriverWait wait = new WebDriverWait(driver, 30);
        wait.until(ExpectedConditions
                .visibilityOfAllElementsLocatedBy(
                        new By.ByClassName("XCUIElementTypeKeyboard")));
        usernameField.sendKeys(username);`

but this did not help at all. An input field does not even take the focus.

**Comment by imurchie** [comment]
Hmm. Ok. I'll investigate a server-side solution.

**Comment by VasilijSviridov** [comment]
@mbaglay  I used your solution, but its not working 

WebDriverWait wait = new WebDriverWait(driver, 180); wait.until(ExpectedConditions .visibilityOfAllElementsLocatedBy( new By.ByClassName("XCUIElementTypeKeyboard")));

driver.getKeyboard().sendKeys("1234");

errors: org.openqa.selenium.WebDriverException: Error Domain=XCTestManagerErrorDomain Code=14 "Timed out waiting for key event to complete" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete} Command duration or timeout: 18.24 seconds Build info: version: '2.5.....


getPageSource() :  <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/3/0/0/2" x="0" y="352" width="320" height="216">
                        <XCUIElementTypeKeyboard name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/3/0/0/2/0" x="0" y="308" width="320" height="260">
                            <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/3/0/0/2/0/0" x="0" y="352" width="320" height="216">
                                <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/3/0/0/2/0/0/0" x="0" y="352" width="320" height="216">
                                    <XCUIElementTypeKey name="q" label="q" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/3/0/0/2/0/0/0/0" x="0" y="363" width="32" height="42">
                                    </XCUIElementTypeKey>
                                    <XCUIElementTypeKey name="w" label="w" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/3/0/0/2/0/0/0/1" x="32" y="363" width="32" height="42">

**Comment by mbaglay** [comment]
@VasilijSviridov as I wrote 

> but this did not help at all. An input field does not even take the focus.

**Comment by VasilijSviridov** [comment]
@mbaglay I upgraded Xcode to 8.1 and device to 10.1, and I am not getting anymore error message, all is working on my side. 
Cheers

**Comment by mbaglay** [comment]
@VasilijSviridov thanks, I will try if it works for me

**Comment by PeterGolf** [comment]
I have this problem on real iPhone (10.1) and simulator (9.3). But on iPad (9.3) it is fine

**Comment by imurchie** [comment]
I've opened a PR (https://github.com/appium/appium-xcuitest-driver/pull/273) with a potential fix for this. At least, it works on my end in multiple scenarios.

**Comment by PeterGolf** [comment]
@imurchie how can we try this fix now?

**Comment by VasilijSviridov** [comment]
I suppose you need to update xcode to 8.1 and your device to 10.1 then use this logic every time you want to sendkeys :
WebDriverWait wait = new WebDriverWait(driver, 30); wait.until(ExpectedConditions .visibilityOfAllElementsLocatedBy( new By.ByClassName("XCUIElementTypeKeyboard")));
driver.getKeyboard().sendKeys("yourkeys");

works for me on iOS 10.1 iPhone 5S real device.

**Comment by PeterGolf** [comment]
@VasilijSviridov but i need to tap on element before this?

**Comment by VasilijSviridov** [comment]
yes of course

**Comment by PeterGolf** [comment]
@VasilijSviridov not helping for me :( can we speak in private?

**Comment by VasilijSviridov** [comment]
@PeterGolf sure no worries

**Comment by PeterGolf** [comment]
@VasilijSviridov how can i contact you?

**Comment by PeterGolf** [comment]
@imurchie tell me please, how to try your fix?

**Comment by imurchie** [comment]
It has been published in the driver. You can get the updates by re-installing Appium without shrinkwrap. 

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by PeterGolf** [comment]
@imurchie not helping rob me

**Comment by imurchie** [comment]
I don't know what that means.

**Comment by PeterGolf** [comment]
@imurchie after installing latest master version, i have this error:

[XCUITest] Error starting iproxy: 'The process did not start in the allotted time (5000ms)'
[XCUITest] Unable to start iproxy. Is it installed?
[XCUITest] Shutting down WebDriverAgent
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] iproxy exited 
[XCUITest] System log exited with code '0'
[debug] [XCUITest] WebDriverAgent process did not end in a timely fashion. Sending SIGHUP signal...
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Full reset requested. Will try to uninstall the app 'ru.****'.
[debug] [XCUITest] Removed 'ru.***'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture

**Comment by imurchie** [comment]
I see that too. I am looking into it.

**Comment by PeterGolf** [comment]
@imurchie okey, thank you very much! Tell me when i can try to verify please. And also i have a question: i'm using this command now ((IOSElement) driver.findElement(By.xpath(LOGIN_TEXT_BOX_LOCATOR))).setValue(login) is it correct?

**Comment by imurchie** [comment]
If that is the correct Xpath, then yes.

Can you try re-installing again. My apologies. The xcuitest driver ought to be 2.0.34 now.

**Comment by PeterGolf** [comment]
@imurchie okey, will try again, thank you! Will post results here soon

**Comment by PeterGolf** [comment]
@imurchie i have an error while building Agent: ../appium-master/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m:13:9: 'RoutingHTTPServer/RoutingHTTPServer.h' file not found

**Comment by PeterGolf** [comment]
@imurchie okey, i tried, the problem with proxy was fixed, but i still have an error with sendKeys, but! i forgot to tell, that this is a keyboard only with numbers

**Comment by imurchie** [comment]
That might be useful information.

Does the keyboard appear at all?

Can you provide the logs (as a [gist](https://gist.github.com))?

**Comment by PeterGolf** [comment]
Yes, it is appeared.
logs: https://gist.github.com/PeterGolf/4421d842348eb9af291ec988e0dce6a7

**Comment by imurchie** [comment]
It does? It does not get recognized. This is strange.

Can you try to call `clear` before sending the text?

**Comment by PeterGolf** [comment]
I just tried to sendKeys to field with normal keyboard, works fine.
Ok, will try clear before

**Comment by imurchie** [comment]
Ok. I'm going to find a way to test on the number keypad, and proceed.

**Comment by PeterGolf** [comment]
@imurchie this problem while using clear: Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}
Command duration or timeout: 6.04 seconds

**Comment by imurchie** [comment]
Hmph. Ok.

A basic test of a number keypad seems to work. Since there are a number of ways to get such a keyboard, is it possible to post the pertinent view?

**Comment by PeterGolf** [comment]
No, it is impossible :(

**Comment by imurchie** [comment]
There's not much I can do, then.

**Comment by PeterGolf** [comment]
@imurchie  may be any other info, that can help you?

**Comment by PeterGolf** [comment]
@imurchie  no way?

**Comment by imurchie** [comment]
At a minimum, how the text field is constructed and the keyboard is configured. If I just set the keyboard to be numeric, things work. But I imagine there is other stuff going on to control the keyboard on your part.

**Comment by PeterGolf** [comment]
@imurchie  Then i think it is impossible, i don't have this information. But i think it is a basic numeric keyboard.

**Comment by nesa246** [comment]
@imurchie I am also facing the same issue, when I install the latest appium version 

Can you please let me know whats wrong 


[XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.59.131:8100'
[XCUITest] WebDriverAgent started at url 'http://192.168.59.131:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8200 to device port 8100 over USB
[XCUITest] Error starting iproxy: 'The process did not start in the allotted time (5000ms)'
[XCUITest] Unable to start iproxy. Is it installed?
[XCUITest] Shutting down WebDriverAgent
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] System log exited with code 'null'
[XCUITest] iproxy exited 
[debug] [XCUITest] WebDriverAgent process did not end in a timely fashion. Sending SIGHUP signal...
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 46521 ms - 177

**Comment by PeterGolf** [comment]
@imurchie maybe there could be some workaround for numeric keyboard? Another methods or commands?

**Comment by imurchie** [comment]
@PeterGolf The only other command that sends text is whatever generates the `keys` endpoint in your language binding (sending keys to the active element).

**Comment by imurchie** [comment]
@nesa246 Do you have `iproxy` installed?

**Comment by PeterGolf** [comment]
@imurchie i found a work around by making tap action with position. But can you tell me: how can i use this: driver.findElement(By.xpath("//blablabla")).click() or tap with some offset?

**Comment by VasilijSviridov** [comment]
@PeterGolf  sorry for delay, I used image recognition to tap on element I need.

Cheers
