### ISSUE TITLE
ChromeDriver install fails behind proxy, when installing appium

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7163]
## The problem

Not able to install Appium 1.6.0 on Mac OSx 10.12 through terminal command

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.5.2
* Desktop OS/version used to run Appium: Mac OS 10.12
* Node.js version (unless using Appium.app|exe): Latest Version
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPad Air 2 real device
* Appium CLI or Appium.app|exe: npm install -g appium 

## Details

Please check the log below. It is not able to establish connection to the ip 172.217.6.16:80 but i am able to download chromdriver manually from the http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip

Is there any workaround for this if no fix available  ? I tried with 1.6.1/2/3 beta version as well but Result is same.

Our team is trying to do iOS 10.1 iPad App automation.

```
Automations-Mac:~ automation$ npm -g install appium@1.6.0
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@2.9.2 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
RequestError: Error: connect ECONNREFUSED 172.217.6.16:80
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:813:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "appium@1.6.0"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.2 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/automation/npm-debug.log
npm ERR! code 1
```

**Comment by imurchie** [comment]
Are you behind a firewall or anything like that?

**Comment by gopi09m** [comment]
We have a proxy  which is http://proxy.abc:8000/
I am able to open the http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip in browser
I am able to open "172.217.6.16:80" in browser but it displays "The specified bucket does not exist."

Is there any setting on Mac I should change to allow it through firewall ? Its a brand new Mac  .

**Comment by imurchie** [comment]
Can you try https://jjasonclark.com/how-to-setup-node-behind-web-proxy

**Comment by gopi09m** [comment]
It gives me a different error now:

npm WARN retry will retry, error on last attempt: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.abc.com proxy.abc.com:8080​

it has a fetch failed error

**Comment by imurchie** [comment]
Are you sure you have the address right?

**Comment by gopi09m** [comment]
Sorry for the late reply. I ran the two commands as below 

npm config set proxy http://proxy.abc:8000
npm config set https-proxy http://proxy.abc:8000


the error is different now:

utomations-Mac-mini:~ automation$ npm -g install appium@1.6.0
npm ERR! registry error parsing json
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "-g" "install" "appium@1.6.0"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9

npm ERR! Unexpected token < in JSON at position 0
npm ERR! <HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=ISO-8859-1"><TITLE>Not Found</TITLE></HEAD>
npm ERR! <H1>Not Found</H1> The requested object does not exist on this server. The link you followed is either outdated, inaccurate, or the server has been instructed not to let you have it. Please inform the site administrator of the <A HREF="install appium@1.6.0">referring page</A>.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/automation/npm-debug.log

**Comment by gopi09m** [comment]
Is there any installer for 1.6.0 version ? installer always works . not sure why npm terminal command always fails.

**Comment by imurchie** [comment]
There is not, as of yet. 

The npm problem is a general one. You probably cannot install _anything_. It is largely a matter of googling and finding a solution that works. Unfortunately different proxies have different solutions.

**Comment by gopi09m** [comment]
Is there a way to skip installation of chrome driver ? I don't need it as i only do automation of nativeiOS apps. 

One more observation is i moved to another network where there is no firewall and it still failed to install chromedriver with connection refused error. Strangely 1.6.0-beta was able to install chromedriver successfully but 1.6.1-beta failed with below error : 

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_112
info Selendroid Ensuring /Users/automation/node_modules/appium-selendroid-driver/selendroid/download exists
info Selendroid Downloading Selendroid standalone server version 0.17.0 from http://repo1.maven.org/maven2/io/selendroid/selendroid-standalone/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> /Users/automation/node_modules/appium-selendroid-driver/selendroid/download/selendroid-server-7cf7163ac47f1c46eff95b62f78b58c1dabdec534acc6632da3784739f6e9d82.jar
Selendroid setup files did not yet exist, waiting...

summary:

with 1.6.0 it fails with:
l Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip..
connection refused

with 1.6.1 beta
Downloading https://chromedriver.storage.googleapis.com/“2.21”/chromedriver_mac64.zip
chrome drivers 2.25 was successfull but fails with selendroiderror

**Comment by gopi09m** [comment]
Can you let me know if there is a way to skip install of chromedriver?

**Comment by SharadRao23** [comment]
Im also facing the same issue but with appium 1.6.1-beta version.

appium1.6.0 is installed correctly on my mac with chromedriver version 2.21
Mac OSx 10.12.1

Appium1.6.1-beta installation fails. The chromedriver version here is 2.25. Is this the issue?
Also, this only happens on Mac OSx 10.12.1 not on 10.11.6

npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@2.9.4 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.25' for platform 'mac' and architecture '64'
info Chromedriver Install Opening temp file to write chromedriver_mac64 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_mac64.zip...
RequestError: Error: self signed certificate in certificate chain
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
- readable-stream@2.0.6 node_modules/appium/node_modules/bl/node_modules/readable-stream
- bl@1.1.2 node_modules/appium/node_modules/bl
- connected-domain@1.0.0 node_modules/appium/node_modules/connected-domain
- pkginfo@0.3.1 node_modules/appium/node_modules/pkginfo
- table-parser@0.1.1 node_modules/appium/node_modules/table-parser
- ps-node@0.0.5 node_modules/appium/node_modules/ps-node
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.1-beta"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.4 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.4 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/administrator/npm-debug.log
npm ERR! code 1

**Comment by imurchie** [comment]
There was recently a change to use https instead of http. @jlipps is this related to that?

**Comment by jlipps** [comment]
It probably is related to that. Dunno why people's company proxies don't allow SSL traffic. @imurchie maybe we should add a `--insecure-downloads` npm flag that chromedriver is sensitive to?

**Comment by imurchie** [comment]
Could do. We could also add a flag to _not_ download CD at all. That would cause problems if the user subsequently tried to use CD, though.

**Comment by jlipps** [comment]
We already have a solution for this that I forgot about; you can override the chromedriver CDN url with whatever you want, including using `http` instead of `https`:

```
npm install -g appium --chromedriver-cdnurl=http://chromedriver.storage.googleapis.com
```

**Comment by gopi09m** [comment]
I fixed it by taking my machine out of VPN network and got it installed.

**Comment by liuxinhu** [comment]
Hi @jlipps , I still have Problem using your command. 

It tries http:// instead of https://, but I still get ETIMEOUT error.

**Comment by SouWilliams** [comment]
Sorry guys, i still met this issue .  Hope can get some help @jlipps @imurchie 
[2017-05-22T15_42_24_818Z-debug.txt](https://github.com/appium/appium/files/1019409/2017-05-22T15_42_24_818Z-debug.txt)

**Comment by maesiva** [comment]
Thanks @imurchie @jlipps 

> jlipps commented on 14 Nov 2016
> We already have a solution for this that I forgot about; you can override the chromedriver CDN url with whatever you want, including using http instead of https:
> 
> npm install -g appium --chromedriver-cdnurl=http://chromedriver.storage.googleapis.com

googleapis http address didn't work. But, I could download the file via browser @ https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip

So, started a local http server using https://www.npmjs.com/package/http-server and copied the zip to appropriate folder and run the command:
> npm install -g appium --chromedriver-cdnurl=http://127.0.0.1:8080

@SouWilliams .. Dirty, but works like a charm!

**Comment by dilpreetbadwal** [comment]
Having the same issue 

info Chromedriver Install Installing Chromedriver version '2.28' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.28/chromedriver_win32.zip...
RequestError: Error: connect ETIMEDOUT 216.58.192.240:443
    at new RequestError (C:\Users\Dilpreet Badwal\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\errors.js:11:15)
    at Request.RP$callback [as _callback] (C:\Users\Dilpreet Badwal\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise\lib\rp.js:60:32)
    at self.callback (C:\Users\Dilpreet Badwal\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (C:\Users\Dilpreet Badwal\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
C:\Users\Dilpreet Badwal\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.x (node_modules\appium\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.11.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.11.2 install script 'node install-npm.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Dilpreet Badwal\npm-debug.log
npm ERR! code 1

**Comment by dilpreetbadwal** [comment]
And I am able to install appium-doctor, which means I have correct proxy settings and running the appium-doctor command gives the following message:
C:\Users\Dilpreet Badwal>appium-doctor
info AppiumDoctor Appium Doctor v.1.4.2
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.exe
info AppiumDoctor  ✔ Node version is 6.11.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\Dilpreet Badwal\AppData\Local\Android\Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_121
info AppiumDoctor  ✔ adb exists at: C:\Users\Dilpreet Badwal\AppData\Local\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor  ✔ android exists at: C:\Users\Dilpreet Badwal\AppData\Local\Android\Sdk\tools\android.bat
info AppiumDoctor  ✔ emulator exists at: C:\Users\Dilpreet Badwal\AppData\Local\Android\Sdk\tools\emulator.exe
info AppiumDoctor  ✔ Bin directory of %JAVA_HOME% is set
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor

**Comment by bhavikviks** [comment]
@maesiva please guide where should be the chrome zip pasted while starting the http-server, an example would be appreciated. Please help, not at able to install appium just because of appium-chromedriver.

**Comment by maesiva** [comment]
start the http-server  and run the command:
npm install -g appium --chromedriver-cdnurl=http://127.0.0.1:8080

In logs, it will show you, where exactly its looking for the chrome driver zip. I remember copying it to ./public/2.28

. is the folder, from where you are starting the http-server.

Please share your logs after running the command, if you need further info.

**Comment by dilpreetbadwal** [comment]
Thanks it worked

**Comment by bhavikviks** [comment]
@maesiva tried the same still getting error..Please find the attache debug log file...any help would be really really appreciated. Thank you in advance.
[logs.docx](https://github.com/appium/appium/files/1126782/logs.docx)

**Comment by maesiva** [comment]
@bhavikviks I see that you're on Windows..
May I know what steps you're following ?

**Comment by gigeos** [comment]
@maesiva I can get the zip whith the browser but no idea what to do with that.
I tried `npm install -g appium --chromedriver-cdnurl=http://chromedriver.storage.googleapis.com` but not work too it logged
```
Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
```
Not to be sure what I should do exactly with your http-server solution
And I tried other npm install -g package to test and it works

**Comment by Bhuvanavd** [comment]
@maesiva ,
Have started local http-server through npm, How do i place the chromedriver in ./2.30/ folder.
Appreciate ur help.
