### ISSUE TITLE
fullReset cause installation failed Appium 1.6.0 

### ISSUE THREAD

**Issue by pengboZheng** [appium/appium#7215]
## The problem
Couldn't install app when fullReset flag is true

## Environment

* Appium version (or git revision) that exhibits the issue: v1.5.3 and v1.6.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version (unless using Appium.app|exe): 7.1.0
* Mobile platform/version under test: iOS 8.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Both

## Details

When fullReset flag is true and only for iOS 8.4:
1. If the App is already installed on device, with fullReset flag is true. it will work fine.
2. If the App has not installed yet on device, with fullReset flag is true, it will be failed to install the app see the log (https://gist.github.com/pengboZheng/fd1d14dc88a46365bb7af1c949439c23)

**Comment by imurchie** [comment]
Can you manually run the command

```
ideviceinstaller -u 2028ce4616022ecb544289feed26add0fc653c1c -U com.myownapp.myownapp
```

**Comment by pengboZheng** [comment]
@imurchie After I did 
`ideviceinstaller -u 2028ce4616022ecb544289feed26add0fc653c1c -U com.myownapp.myownapp`
> Uninstalling 'com.myownapp.myownapp'
>  - RemovingApplication (50%)
>  - GeneratingApplicationMap (90%)
>  - Error occurred: APIInternalError

**Comment by imurchie** [comment]
Is there anything in the device logs to indicate what failed? `ideviceinstaller` is having a hard time.

**Comment by pengboZheng** [comment]
@imurchie There is no device logs.
From "Console":

> 2016-11-10 4:31:52.557 PM com.apple.usbmuxd[79]: HandleUSBMuxDictionary client 0x7fef3b804170-libusbmuxd/org.libimobiledevice.usbmuxd using library usbmuxd built for freedom, running usbmuxd-374.70

**Comment by imurchie** [comment]
I'm not sure what the problem is, then.

**Comment by pengboZheng** [comment]
@imurchie 
When the app is installed on device I run `ideviceinstaller -u 2028ce4616022ecb544289feed26add0fc653c1c -U com.myownapp.myownapp`

> Uninstalling 'com.printeron.printeron'
 - RemovingApplication (50%)
 - GeneratingApplicationMap (90%)
 - Complete

**Comment by pengboZheng** [comment]
Based on the gist log

> [debug] [iOS] Full reset requested. Will try to uninstall the app 'com.myownapp.myownapp'.

the message on above should not even appear, because the app is NOT installed on device yet.

**Comment by mykola-mokhnach** [comment]
@imurchie Probably, it is necessary to ignore uninstallation error in Appium code in case the app with given bundle id is not installed.

@pengboZheng Is this problem reproducible in 1.6.0?

**Comment by pengboZheng** [comment]
@mykola-mokhnach yes, it can be reproducible in both 1.5.3 and 1.6.0

**Comment by pengboZheng** [comment]
I assume something wrong with `this.realDevice.isInstalled(this.opts.bundleId)`

**Comment by imurchie** [comment]
It must be, yes.

What happens when you run `ideviceinstaller -l`?

**Comment by pengboZheng** [comment]
@imurchie it works fine when I use `ideviceinstaller -l`
I think https://github.com/appium/appium-ios-driver/pull/139/files#r61813235 might the issue cause my problem

**Comment by pengboZheng** [comment]
When the app is installed after id do `ideviceinstaller -l`:

> com.myownapp.myownapp - MyOwnApp 1.1.0

When the app is NOT installed after id do `ideviceinstaller -l`, there is NO "com.myownapp.myownapp" in the list.

**Comment by imurchie** [comment]
Does it change if you specify your application using the `app` desired capability (instead of `ipa`, which doesn't exist).

**Comment by pengboZheng** [comment]
@imurchie When I change the desired capability to `capabilities.setCapability("ipa", "/Users/username/Desktop/MyOwnApp.app");` which it does not exist. Please see the log https://gist.github.com/pengboZheng/12cdd6dd636fc7c8d9e1808fc935e991

> [debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with udid 2028ce4616022ecb544289feed26add0fc653c1c
[debug] [iOS] App is not installed. Will try to install.
[debug] [iOS] Installing ipa found at /Users/username/Desktop/myownapp.app
[debug] [iOS] Nothing found on device, going ahead and installing.
[debug] [iOS] App installed.

Actually, it didn't install the app at all. It will run the loop: 

>[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.) : Failed to launch process with bundle identifier 'com.myownapp.myownapp'
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup

**Comment by imurchie** [comment]
Instruments error 253 usually means the app is not built for automating. Is this a development build?

**Comment by pengboZheng** [comment]
@imurchie Yes, this is a development build. But the error message only appear when I change the file extension from `ipa` to `app`. After I change to `app`, because there is no file with extension `app`. When I have the correct file extension name, which means it can find the file, it will be able to install on deice

**Comment by imurchie** [comment]
The `app`/`ipa` issue I was referring to is the capability. The capability name is `app`.

**Comment by pengboZheng** [comment]
Both
`capabilities.setCapability("app", "/Users/username/Desktop/MyOwnApp.ipa");`
And
`capabilities.setCapability("ipa", "/Users/username/Desktop/MyOwnApp.ipa");`
will get same error when the flag "fullReset" is true.
Because it was trying to remove the app which it has not installed yet.

**Comment by imurchie** [comment]
try updating by re-installing 1.6.1-beta. I've fixed the issue I think.

```
npm uninstall -g appium
npm install -g appium@beta
```

**Comment by pengboZheng** [comment]
@imurchie Still doesn't work with iOS 8
Please see the log: https://gist.github.com/pengboZheng/b2529e1fa953a78e91f1b28dc32c08e2
If I change to iOS 9:
It will work(https://gist.github.com/pengboZheng/9b91c7d4607fec7af3297e58fe865d89)

**Comment by imurchie** [comment]
Shoot. I missed something.

Can you try one more time (re-installing, then running)? My apologies.

**Comment by pengboZheng** [comment]
@imurchie Thanks man, it works like a charm. Fully tested on both iOS 8 and iOS 9, all working fine!
Going to head to iOS 10 soon.

**Comment by imurchie** [comment]
Lovely. Sorry for it taking a while.

**Comment by MadebyBala** [comment]
Encountered internal error running command: Error: Could not install app Command 'ios-deploy --id b058eb7b26be646077438c5a418e6ad9b6b1d3a8 --uninstall --bundle /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-cpqmrrtinuhkzhdwctytraxmoaio/Build/Products/Debug-iphoneos/IntegrationApp.app' exited with code 253
    at IOSDeploy.install$ (../../lib/ios-deploy.js:39:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[HTTP] <-- POST /wd/hub/session 500 6147 ms - 408 


i am getting this error
