### ISSUE TITLE
Error: Sdk ‘10’ was not in list of simctl sdks 

### ISSUE THREAD

**Issue by vaninagarajan** [appium/appium#7237]
Hi,

I am trying to run iOS 10 automated scripts in simulator iPhone 5s version 10.While running code getting below error in the appium 1.6 beta and also in the eclipse console.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Sdk '10' was not in list of simctl sdks (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 986 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'Sanchas-MacBook-Pro-2.local', ip: '192.168.0.19', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver

In terminal,

Last login: Tue Nov 15 04:20:27 on ttys000
Sanchas-MacBook-Pro-2:~ sancha$ appium &
[1] 8641
Sanchas-MacBook-Pro-2:~ sancha$ [Appium] Welcome to Appium v1.6.0-beta1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"appiumVersion":null,"platformVersion":"10","automationName":"XCUITest","bundleId":"com.tradestone.bamboorose","browserName":"","deviceOrientation":"portrait","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","platformName":"iOS","deviceName":"iPhone 5s","appPath":"/Users/sancha/Library/Developer/Xcode/DerivedData/Bamboorose-aqiykccgduwxmkclcvjvnztracaz/Build/Products/Debug-iphonesimulator/Bamboorose.app"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"appiumVersion":null,"platformVersion":"10","automationName":"XCUITest","bundleId":"com.tradestone.bamboorose","browserName":"","deviceOrientation":"portrait","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-dri...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium] appiumVersion: null
[Appium] platformVersion: '10'
[Appium] automationName: 'XCUITest'
[Appium] bundleId: 'com.tradestone.bamboorose'
[Appium] browserName: ''
[Appium] deviceOrientation: 'portrait'
[Appium] xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig'
[Appium] platformName: 'iOS'
[Appium] deviceName: 'iPhone 5s'
[Appium] appPath: '/Users/sancha/Library/Developer/Xcode/DerivedData/Bamboorose-aqiykccgduwxmkclcvjvnztracaz/Build/Products/Debug-iphonesimulator/Bamboorose.app'
[debug] [XCUITest] XCUITestDriver version: 2.0.29
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion, deviceOrientation, appPath.
[BaseDriver] Session created with session id: 14372f23-ba82-4b56-9a65-1fdb42de54c1
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[XCUITest] Error: Sdk '10' was not in list of simctl sdks
at getDevices$ (lib/simctl.js:179:13)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as next
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)
[Error: Sdk '10' was not in list of simctl sdks]
[debug] [XCUITest] Running iOS simulator reset flow
[MJSONWP] Encountered internal error running command: Error: Sdk '10' was not in list of simctl sdks
at getDevices$ (lib/simctl.js:179:13)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke as _invoke
at GeneratorFunctionPrototype.prototype.(anonymous function) as next
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)
[HTTP] <-- POST /wd/hub/session 500 236 ms - 176

**Comment by mykola-mokhnach** [comment]
What is the output of 

```
xcrun simctl list
```

?

**Comment by imurchie** [comment]
Use `10.0`.

**Comment by vikramvi** [comment]
Issue is still reproducible with appium version 1.6.3  @mykola-mokhnach @imurchie 

[caps]
automationName = "XCUITest"
platformName = "iOS"
app = "/Users/.../test.app"
deviceName = "iPhone SE"
platformVersion = "9.3"

`xcrun simctl list

== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 9.3 (9.3 - 13E233) (com.apple.CoreSimulator.SimRuntime.iOS-9-3)
iOS 10.0 (10.0 - 14A345) (com.apple.CoreSimulator.SimRuntime.iOS-10-0)
tvOS 10.0 (10.0 - 14T328) (com.apple.CoreSimulator.SimRuntime.tvOS-10-0)
watchOS 3.0 (3.0 - 14S326) (com.apple.CoreSimulator.SimRuntime.watchOS-3-0)
== Devices ==
-- iOS 9.3 --
    iPhone 4s (4E636B25-5E20-4408-879F-067E3584EB99) (Shutdown)
    iPhone 5 (636A0156-893C-4A9B-86EF-A3F008131474) (Booted)
    iPhone 5s (1B11EBA6-DBAD-4C21-BB3C-82B90303E15B) (Shutdown)
    iPhone 6 (0A9C00DA-77AB-4837-ADD2-CB20655982E2) (Shutdown)
    iPhone 6 Plus (306FF8DD-09E1-4BBA-B15D-6D1CF32DD5C3) (Shutdown)
    iPhone 6s (17F971A3-1E1D-4147-8D61-16B8EB8C34FB) (Shutdown)
    iPhone 6s Plus (549F2D8F-A64A-4B16-99A1-F8C8D3C8C488) (Shutdown)
    appiumTest-b6752848-fe1e-4c5d-80e2-7c7aeaf8d823 (F04B7A03-63AB-49FB-BC73-8552A2EB7810) (Shutdown)
    iPhone SE 9.3 (A9EDF7F8-D0EA-43D4-96A5-57890573323D) (Shutdown)
    iPad 2 (D4DDDD44-6C35-4D65-B1EA-0BC2D7E6D4D5) (Shutdown)
    iPad Retina (DDDC0FCA-E7B0-449F-B272-79ECAF74BF99) (Shutdown)
    iPad Air (14FD1A69-010D-4DBA-8B3A-895490624674) (Shutdown)
    iPad Air 2 (BDBF5DD8-249A-4639-9367-F0A4CB86BCA9) (Shutdown)
    iPad Pro (2E929003-3685-4CC8-BD1E-D3369D25EE62) (Shutdown)
-- iOS 10.0 --
    iPhone 5 (5BE8E7FB-5E35-47DA-94F5-6A2161622719) (Shutdown)
    iPhone 5s (755BEDDD-8163-411A-AA25-A65A47A8D0EB) (Shutdown)
    iPhone 6 (1CE37F89-C0F9-4B94-90CD-A8986A050471) (Shutdown)
    iPhone 6 Plus (7FC12F1E-4A0E-4439-86BC-954C4FE95D13) (Shutdown)
    iPhone 6s (6FD2D72B-402D-4D13-B3ED-FD554ED449EB) (Shutdown)
    iPhone 6s Plus (E6506C87-2EFA-47C4-8A85-A19EF7BD7551) (Shutdown)
    iPhone 7 (4D99370B-3649-44CB-A50E-CA9585166BE5) (Shutdown)
    iPhone 7 Plus (CB00C17E-4D0A-4668-BD94-23CBCB2EE6B7) (Shutdown)
    iPhone SE (194B39BF-0277-416E-9758-8516DCED1BEA) (Shutdown)
    iPad Retina (BC83F480-DAF1-4426-A47D-03CDF3753AA8) (Shutdown)
    iPad Air (D1850226-3CD3-488B-A659-738A79AA7076) (Shutdown)
    iPad Air 2 (C7E7B44A-31EF-4FC9-B359-29C93919C2A2) (Shutdown)
    iPad Pro (9.7 inch) (9B93F5F2-5996-4D49-B031-FBE2BD761364) (Shutdown)
    iPad Pro (12.9 inch) (AE0CAB4D-F016-4323-9016-76DF460B3334) (Shutdown)
-- tvOS 10.0 --
    Apple TV 1080p (9FF48326-6FA3-4973-A467-C836FA54A870) (Shutdown)
-- watchOS 3.0 --
    Apple Watch - 38mm (4E31ADD9-9049-4A26-9672-70DA45FA075D) (Shutdown)
    Apple Watch - 42mm (6FC6C2B7-A1CA-4CEC-A6B4-EE013ABB7E96) (Shutdown)
    Apple Watch Series 2 - 38mm (3B1C7E1B-40F2-477F-9A19-CE6603E3A3E4) (Shutdown)
    Apple Watch Series 2 - 42mm (B8035FF2-E578-4DC9-AB14-4FE6F337F29E) (Shutdown)
== Device Pairs ==
B4360588-0FFF-4096-BC9A-1BFF4155B4CF (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (3B1C7E1B-40F2-477F-9A19-CE6603E3A3E4) (Shutdown)
    Phone: iPhone 7 (4D99370B-3649-44CB-A50E-CA9585166BE5) (Shutdown)
51168624-B2D6-4F6E-B12C-9F5BFCBE3591 (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (B8035FF2-E578-4DC9-AB14-4FE6F337F29E) (Shutdown)
    Phone: iPhone 7 Plus (CB00C17E-4D0A-4668-BD94-23CBCB2EE6B7) (Shutdown)`

**Comment by imurchie** [comment]
@Krunaltthakkar13 I don't understand your question. The list has an iOS version you don't have?

**Comment by Krunaltthakkar13** [comment]
@imurchie I am using iOS 10.2 but in that getting same error

**Comment by imurchie** [comment]
@Krunaltthakkar13 Can you post, as a link to a [gist](https://gist.github.com) the Appium server logs?

**Comment by Krunaltthakkar13** [comment]
AppleMacBook$ appium
[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 79 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/user/Documents/ProjectAppium.app","automationName":"Appium","deviceName":"iPhone SE"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/user/Documents/ProjectAppium.app","automationName":"Appium","deviceName":"iPhone SE"},null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/user/Documents/ProjectAppium.app'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'iPhone SE'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: bbf9b403-657a-402b-b2b0-c3b93b39287d
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC'
[XCUITest] Determining device to run tests on: udid: '4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC', real device: false
[BaseDriver] Using local app '/Users/user/Documents/ProjectAppium.app'
[debug] [XCUITest] Checking whether app '/Users/user/Documents/ProjectAppium.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/user/Documents/ProjectAppium.app': 'isteer.ProjectAppium'
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/user/Library/Logs/CoreSimulator/4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC
[iOSSim] Simulator log at '/Users/user/Library/Logs/CoreSimulator/4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC/system.log'
[iOSSim] Tailing simulator logs until we encounter the string "com.apple.springboard"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Simulator startup timed out. Continuing anyway.
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 70513ms
[debug] [XCUITest] Installing app '/Users/user/Documents/ProjectAppium.app' on device
[HTTP] <-- POST /wd/hub/session - - ms - - 
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
^C[Appium] Received SIGINT - shutting down
[XCUITest] Simulator log exited with code 'null'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGINT'

**Comment by Krunaltthakkar13** [comment]
@imurchie logs of appium server

AppleMacBook$ appium
[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 79 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/user/Documents/ProjectAppium.app","automationName":"Appium","deviceName":"iPhone SE"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","platformVersion":"10.2","newCommandTimeout":"7200","app":"/Users/user/Documents/ProjectAppium.app","automationName":"Appium","deviceName":"iPhone SE"},null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/user/Documents/ProjectAppium.app'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'iPhone SE'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: bbf9b403-657a-402b-b2b0-c3b93b39287d
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC'
[XCUITest] Determining device to run tests on: udid: '4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC', real device: false
[BaseDriver] Using local app '/Users/user/Documents/ProjectAppium.app'
[debug] [XCUITest] Checking whether app '/Users/user/Documents/ProjectAppium.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/user/Documents/ProjectAppium.app': 'isteer.ProjectAppium'
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/user/Library/Logs/CoreSimulator/4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC
[iOSSim] Simulator log at '/Users/user/Library/Logs/CoreSimulator/4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC/system.log'
[iOSSim] Tailing simulator logs until we encounter the string "com.apple.springboard"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Simulator startup timed out. Continuing anyway.
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 70513ms
[debug] [XCUITest] Installing app '/Users/user/Documents/ProjectAppium.app' on device
[HTTP] <-- POST /wd/hub/session - - ms - - 
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=4D1E1870-279C-4BFB-8F8A-CE6A300E0ABC -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
^C[Appium] Received SIGINT - shutting down
[XCUITest] Simulator log exited with code 'null'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGINT'

**Comment by swathi-b** [comment]
Hello Everyone,

I am setting up appium,v1.6.5-beta with real device,Iphone 6s

I am receiving this error "Error: Sdk ‘10’ was not in list of simctl sdks".My device name exist in "xcrun simctl list".I attached appium server logs and code

[Code.txt](https://github.com/appium/appium/files/1006720/Code.txt)
[AppiumLog.txt](https://github.com/appium/appium/files/1006721/AppiumLog.txt)


Can anyone of you please help me with it.

**Comment by imurchie** [comment]
@swathi-b You need to specify the UDID of the device in the `udid` desired capability, or else the system thinks you are trying to run a simulator, and simulators do not have patch versions (so a simulator for iOS 10.1.1 is not found).

**Comment by swathi-b** [comment]
Thanks a lot @imurchie for the quick reply.It is solved now :) Thanks again!

**Comment by Edvinas2033** [comment]
I have same error, not sure what to do next, can't find answer..

"[BaseDriver] The following capabilities were provided, but are not recognized by appium: UDID."
"[XCUITest] Error: Sdk '10.3.2' was not in list of simctl sdks"
"[MJSONWP] Encountered internal error running command: Error: Sdk '10.3.2' was not in list of simctl sdks"
Getting 500

[Appium] app: ''***"
[Appium] appName: ''****"
[Appium] automationName: 'XCUITest'
[Appium] bundleId: '********'
[Appium] deviceName: 'iPhone 7'
[Appium] platformName: 'iOS'
[Appium] platformVersion: '10.3.2'
[Appium] showIOSLog: true

Can someone help me with this?

**Comment by imurchie** [comment]
Just use 10.3

**Comment by adurrani87** [comment]
I am getting the same error as @swathi-b got. But I dont see my device in the simctl list. I have it connected and it  is the list in Xcode. Can someone please advise on what I need to do?
@imurchie ?

**Comment by imurchie** [comment]
What does the device look like in Xcode? Does it require you to authorize it or something?

**Comment by adurrani87** [comment]
@imurchie  No there isnt anything to authorize. It is paired up.

**Comment by GowriSethu** [comment]
@imurchie: I'm also facing the same issue as @adurrani87 mentioned above. 

My iPhone 7(version 10.3.1) is connected to the Mac machine.
Connected real device listed under the "   instruments -s devices   " , but the device is not displayed under the "xcrun simctl list"
Can someone please advise on what is the actual issue ?

**Comment by imurchie** [comment]
@adurrani87 Can you provide the full Appium server logs, as a link to a [gist](https://gist.github.com)?

**Comment by adurrani87** [comment]
[https://gist.github.com/adurrani87/786a4705296125b75fea84fcdd30c86c.js]

**Comment by imurchie** [comment]
Ok. I don't see where you are trying to get the device. If you want to test on a real device you need to specify the device through the `udid` desired capability.

**Comment by adurrani87** [comment]
@imurchie 
I have done that. 
[Appium ServerLog](https://gist.github.com/adurrani87/dd90f5642c59fe33f431f0b3e6221fbe.js)

**Comment by imurchie** [comment]
There is no `udid` specified there.

**Comment by adurrani87** [comment]
@imurchie  I have specified the UDID desired capability. But I am not sure why Appium is not picking it up. Any suggestions?

**Comment by imurchie** [comment]
I have no idea. The server is not receiving a `udid` desired capability.

**Comment by Vismi1** [comment]
Hi Sir,

I am setting up appium,v1.6.5-beta with real device,Iphone 5C.
I got this error "An unknown server-side error occurred while processing the command. Original error: Sdk '10.0.2' was not in list of simctl sdks" when i start session.

I attached screenshot with this.
![screen shot 2017-07-10 at 4 55 56 pm](https://user-images.githubusercontent.com/30045137/28016196-fc5ba35c-6590-11e7-9bc8-0fa4e92cf785.png)
![screen shot 2017-07-10 at 4 55 16 pm](https://user-images.githubusercontent.com/30045137/28016198-fe73d182-6590-11e7-9c9a-09bfb71c2705.png)

**Comment by GowriSethu** [comment]
@Vismi1 : Can you pls check with the udid of the device is correct ?  & one more thing app capability should be selected with filepath parameter

**Comment by Vismi1** [comment]
@GowriSethu app udid is correct. 
   What you mean Filepath parameter?

**Comment by GowriSethu** [comment]
In desired capability "app" should be selected with filepath parameter not as text, Real device is connected with MAC ? device is listed in XCode devices list ?

**Comment by imurchie** [comment]
Generally  speaking the system does not like getting the patch number. So though the _actual_ `platformVersion` is "10.0.2", Apple's tools only register "10.0".

**Comment by Vismi1** [comment]
@imurchie ,@gowrisethu,  thanks all. Issue is fixed

**Comment by hqfking** [comment]
I came across the same issue for the Simulator.  After read the thread, it does not provide a solution to the Simulator use case.  

I tried to put '10.3' as the platformVersion, but still see the same error.

**Comment by Amar-Incture** [comment]
Hi All,

I am also facing the same problem and am not able to resolve it. I am attaching the screenshot of the capabilities that I have defined. I have not given the path of the ipa but other than that everything is correct?
<img width="916" alt="screen shot 2017-09-12 at 3 07 11 pm" src="https://user-images.githubusercontent.com/24287937/30319096-9cc4b06e-97cc-11e7-9cf9-86b98feda789.png">

**Comment by wengyangjie** [comment]
hi
[Appium]   platformName: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: 27f51017-8db7-46dc-a7d2-0e8dda154411
[debug] [XCUITest] Xcode version set to '8.3.3' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1505697798088 (09:23:18 GMT+0800 (CST))
[XCUITest] Error: Sdk '10.3.1' was not in list of simctl sdks
    at getDevices$ (../../lib/simctl.js:230:13)

[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   platformVersion: '10.3.1'
[Appium]   deviceName: 'iPhone SE'

use: iMac 10.12.6(16G29)
appium-v: 1.6.5

how can I do ?

**Comment by anton6** [comment]
I am using xcode_8.3.3 and also seeing same error. I think xcode_8.3.3 comes with iOS 10.3.1 pre-installed not 10.3.

`[XCUITest] Error: '10.3.1' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 10.3`

Is there really no way to fix this error apart from using iOS 10.3? Because xcode_8.3.3 does not give me the option to download and install iOS 10.3 in the component manager.

<img width="753" alt="screen shot 2017-11-30 at 14 31 40" src="https://user-images.githubusercontent.com/16119505/33435905-53537c2e-d5db-11e7-8020-e72c897800f2.png">

**Comment by mykola-mokhnach** [comment]
The only thing that matters here is how the version is shown in `xcrun simctl list` output. If you are not happy the about way Xcode displays it then please report an issue to Apple.

**Comment by anton6** [comment]
Yes I understand what the issue is, just wondering if that Appium check has to be so strict.

It works if Xcode8.3 is installed because it comes with iOS 10.3, not 10.3.1 that causes the check to fail

**Comment by fatmeiliazova** [comment]
Hi Everyone,

I am using iPhone 8 with iOS v 11.3.1 and getting this error:

[14:18:13] I/launcher - Running 1 instances of WebDriver
[14:18:13] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[14:18:14] E/launcher - An unknown server-side error occurred while processing the command. Original error: '11.3.1' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 9.0, 11.3, 9.1, 8.4
[14:18:14] E/launcher - WebDriverError: An unknown server-side error occurred while processing the command. Original error: '11.3.1' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 9.0, 11.3, 9.1, 8.4
    at Object.checkLegacyResponse (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at createDriver (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/selenium-webdriver/index.js:635:14)
    at Hosted.getNewDriver (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/built/driverProviders/driverProvider.js:53:33)
    at Runner.createBrowser (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/built/runner.js:195:43)
    at q.then.then (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/built/runner.js:339:29)
    at _fulfilled (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/q/q.js:796:13)
    at /Users/amna/.nvm/versions/node/v8.6.0/lib/node_modules/protractor/node_modules/q/q.js:556:49
[14:18:14] E/launcher - Process exited with error code 199


And capabilities in conf.js file is 
capabilities: {
    'browserName': 'safari',
    'appium-version': '1.8.0',
    'platformName': 'iOS',
    'platformVersion': '11.3.1',
    'deviceName': "iPhone (2)"
}


How can I download required simctl SDK for 11.3.1?

**Comment by GowriSethu** [comment]
@fatmeiliazova : In your mac you don't have the '11.3.1' platform version, you can download the platform version from XCode 

Open the Xcode in your mac machine & their open the 'window --> Devices and Simulators' option

Where you can see the download option for iOS platform version

**Comment by kanu1713** [comment]
I am trying to install app in ios simulators using Appium-desktop(1.9.0). But I am facing the same issue. I have all the devices added when I run "xcrun simctl list" still appium says SDK not available please help.


ub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m3 ms - 57[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"desiredCapabilities":{"app":"/Users/AA1234/Documents/Now.app","automationName":"XCUITest","deviceName":"iPad (5th generation)","platformName":"iOS","platformVersion":"12.2","xcodeOrgId":" Automation","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true}}[39m
[debug] [35m[MJSONWP][39m Calling AppiumDriver.createSession() with args: [{"app":"/Users/AA1234/Documents/Now.app","automationName":"XCUITest","deviceName":"iPad (5th generation)","platformName":"iOS","platformVersion":"12.2","xcodeOrgId":"Automation","xcodeSigningId":"iPhone Developer","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1553828212490 (22:56:52 GMT-0400 (EDT))
[info] [35m[Appium][39m Creating new XCUITestDriver (v2.104.0) session
[info] [35m[Appium][39m Capabilities:
[info] [35m[Appium][39m   app: /Users/AA1234/Documents/Now.app
[info] [35m[Appium][39m   automationName: XCUITest
[info] [35m[Appium][39m   deviceName: iPad (5th generation)
[info] [35m[Appium][39m   platformName: iOS
[info] [35m[Appium][39m   platformVersion: 12.2
[info] [35m[Appium][39m   xcodeOrgId: Automation
[info] [35m[Appium][39m   xcodeSigningId: iPhone Developer
[info] [35m[Appium][39m   newCommandTimeout: 0
[info] [35m[Appium][39m   connectHardwareKeyboard: true
[debug] [35m[BaseDriver][39m Creating session with MJSONWP desired capabilities: {"app":"/Users/AA1234/Doc...
[info] [35m[BaseDriver][39m Session created with session id: 3fdca8a0-4cff-4fb2-8ee4-3ba5fb632c9f
[debug] [35m[XCUITest][39m Current user: 'aa1234'[error] [35m[XCUITest][39m Erro**r: '12.2' does not exist in the list of simctl SDKs. No Simulator SDK versions are available on your system. Please install some via Xcode preferences.**
[error] [35m[XCUITest][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:551:13
[error] [35m[XCUITest][39m     at Generator.next (<anonymous>)
[error] [35m[XCUITest][39m     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[error] [35m[XCUITest][39m     at _next (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[error] [35m[XCUITest][39m     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:75:22)
[error] [35m[XCUITest][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:92:30
[error] [35m[XCUITest][39m     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/_microtask.js:18:9)
[error] [35m[XCUITest][39m     at process._tickCallback (internal/process/next_tick.js:61:11)
[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1553828212789 (22:56:52 GMT-0400 (EDT))
[debug] [35m[MJSONWP][39m Encountered internal error running command: Error: '12.2' does not exist in the list of simctl SDKs. No Simulator SDK versions are available on your system. Please install some via Xcode preferences.
[debug] [35m[MJSONWP][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/node-simctl/lib/simctl.js:551:13
[debug] [35m[MJSONWP][39m     at Generator.next (<anonymous>)
[debug] [35m[MJSONWP][39m     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[debug] [35m[MJSONWP][39m     at _next (/Applications/Appium.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
[debug] [35m[MJSONWP][39m     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:75:22)
[debug] [35m[MJSONWP][39m     at /Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/es6.promise.js:92:30
[debug] [35m[MJSONWP][39m     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/core-js/modules/_microtask.js:18:9)
[debug] [35m[MJSONWP][39m     at process._tickCallback (internal/process/next_tick.js:61:11)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m303 ms - 285[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[HTTP][39m No route found. Setting content type to 'text/plain'
[info] [35m[HTTP][39m [37m<-- DELETE /wd/hub/session [39m[33m404[39m [90m1 ms - 57[39m
[info] [35m[HTTP][39m [90m[39m

-----------------------------------------------

If i keep udid, says unknow device or simulator .  facing this issue in both Appium(1.9.1), Appium-desktop(1.9.0).  Please help me.

My XCUITest is not detecting my simulator SDKs as per my understanding.

Thanks

**Comment by KazuCocoa** [comment]
Please update to the latest, which has 1.12.1 server, if you have installed Xcode 10.2.
The Xcode version has breaking change in the simctl format

**Comment by kanu1713** [comment]
Thank you. I tried just now it is working

**Comment by sumanthvakacharla** [comment]
Worked for me after updating Appium to 1.12.1 in CI. Cheers and Appreciation for @KazuCocoa
