### ISSUE TITLE
Unable to change Slider value

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7435]
@shivakrishnach31 commented on [Thu Nov 03 2016](https://github.com/appium/appium-xcuitest-driver/issues/278)

Hi @imurchie & @jlipps ,

I am unable to change slider values using `sendKeys("1")` in iOS devices using Appium 1.6.0 and Xcode 8. It was working fine in Xcode 7.3 but not working now.
Below is the code I used:
`driver.findElementByClassName("XCUIElementTypeSlider").sendKeys("1");`

Appium log:
```
> Laxmi-iOSs-iMac:~ Shiva$ [Appium] Welcome to Appium v1.6.0
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723
> [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Shiva/Downloads/S*********.ipa","sendKeyStrategy":"setValue","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3","automationName":"XCUITest","browserName":"","platformName":"iOS","udid":"*********","deviceName":"Shiva’s iPhone"}}
> [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Shiva/Downl...
> [Appium] Creating new XCUITestDriver session
> [Appium] Capabilities:
> [Appium]   app: '/Users/Shiva/Downloads/*************.ipa'
> [Appium]   sendKeyStrategy: 'setValue'
> [Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
> [Appium]   platformVersion: '9.3'
> [Appium]   automationName: 'XCUITest'
> [Appium]   browserName: ''
> [Appium]   platformName: 'iOS'
> [Appium]   udid: '*********************'
> [Appium]   deviceName: 'Shiva’s iPhone'
> [debug] [XCUITest] XCUITestDriver version: 2.0.26
> [BaseDriver] Session created with session id: 004a9542-1e71-416c-bb75-2d6e41c2693c
> [debug] [XCUITest] Xcode version set to '8.0'
> [debug] [XCUITest] iOS SDK Version set to '10.0'
> [debug] [XCUITest] Available devices: ******************
> [debug] [XCUITest] Creating iDevice object with did **************
> [XCUITest] Determining device to run tests on: udid: '39e1f150b412544633088c913f117be93a846b67', real device: true
> [BaseDriver] Using local app '/Users/Shiva/Downloads/***************.ipa'
> [debug] [BaseDriver] Copying local zip to tmp dir
> [debug] [BaseDriver] Unzipping /var/folders/p_/y4z5csh55y3_gg0rht_dj91w0000gp/T/2016103-22617-1a7k1rn.bj9j05dn29/appium-app.zip
> [debug] [BaseDriver] Testing zip archive: /var/folders/p_/y4z5csh55y3_gg0rht_dj91w0000gp/T/2016103-22617-1a7k1rn.bj9j05dn29/appium-app.zip
> [BaseDriver] Unzipped local app to '/var/folders/p_/y4z5csh55y3_gg0rht_dj91w0000gp/T/2016103-22617-1a7k1rn.bj9j05dn29/Payload/******.app'
> [debug] [XCUITest] Checking whether app is actually present
> [debug] [ios-app-utils] Getting bundle ID from app
> [debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
> [debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
> [XCUITest] Setting up real device
> [debug] [XCUITest] Stdout from app isInstalled check: [....] Waiting for iOS device to be connected
> [....] Using iPhone 6 Plus 'Shiva’s iPhone' (*************).
> true
> 
> [debug] [XCUITest] App is installed.
> [debug] [XCUITest] Full reset not requested. No need to install.
> [XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
> [XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
> [XCUITest] Launching WebDriverAgent on the device
> [debug] [XCUITest] Carthage found: /usr/local/bin/carthage
> [debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=39e1f150b412544633088c913f117be93a846b67' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Waiting for WebDriverAgent to start on device
> [debug] [XCUITest] Log file for xcodebuild test: /Users/Shiva/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/5B1C1C82-0A17-4468-BC02-B0D5D02F1A87/Session-WebDriverAgentRunner-2016-11-03_161903-RaFDOq.log
> [XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.1.224:8100'
> [XCUITest] WebDriverAgent started at url 'http://192.168.1.224:8100'
> [debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
> [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bu...
> [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"2774...
> [Appium] New XCUITestDriver session created successfully, session 004a9542-1e71-416c-bb75-2d6e41c2693c added to master session list
> [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,...
> [HTTP] <-- POST /wd/hub/session 200 32944 ms - 582 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element {"using":"accessibility id","value":"OK"}
> [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","OK","0...
> [debug] [XCUITest] Executing command 'findElement'
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/element] with body: {"using":"accessibility id"...
> [JSONWP Proxy] Got response with status 200: {"value":{"using":"access...


> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element 500 933 ms - 164 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/elements {"using":"class name","value":"UIAAlert"}
> [MJSONWP] Calling AppiumDriver.findElements() with args: ["class name","UIAAlert","0...
> [debug] [XCUITest] Executing command 'findElements'
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
> [XCUITest] Rewrote incoming selector from 'UIAAlert' to 'XCUIElementTypeAlert' to match XCUI type. You should consider updating your tests to use the new selectors directly
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/elements] with body: {"using":"class name","value..
> [JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"27...
> [MJSONWP] Responding to client with driver.findElements() result: []
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/elements 200 923 ms - 74 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/elements {"using":"accessibility id","value":"Get Started"}
> [MJSONWP] Calling AppiumDriver.findElements() with args: ["accessibility id","Get St...
> [debug] [XCUITest] Executing command 'findElements'
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/elements] with body: {"using":"accessibility id"...
> [JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"27...
> [MJSONWP] Responding to client with driver.findElements() result: []
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/elements 200 970 ms - 74 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element {"using":"accessibility id","value":"24/48 kHz"}
> [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","24/48 ...
> [debug] [XCUITest] Executing command 'findElement'
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/element] with body: {"using":"accessibility id"...
> [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"552E08...
> [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"552E0835-0539-4...
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element 200 1180 ms - 177 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element/552E0835-0539-4FE1-92BD-F9D4FC4D4792/click {"id":"552E0835-0539-4FE1-92BD-F9D4FC4D4792"}
> [MJSONWP] Calling AppiumDriver.click() with args: ["552E0835-0539-4FE1-92BD-F...
> [debug] [XCUITest] Executing command 'click'
> [JSONWP Proxy] Proxying [POST /uiaElement/552E0835-0539-4FE1-92BD-F9D4FC4D4792/scroll] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/uiaElement/552E0835-0539-4FE1-92BD-F9D4FC4D4792/scroll] with body: {"toVisible":true}
> [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"27...
> [JSONWP Proxy] Proxying [POST /element/552E0835-0539-4FE1-92BD-F9D4FC4D4792/click] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/element/552E0835-0539-4FE1-92BD-F9D4FC4D4792/click] with body: {}
> [JSONWP Proxy] Got response with status 200: {"status":0,"id":"552E0835-...
> [MJSONWP] Responding to client with driver.click() result: ""
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element/552E0835-0539-4FE1-92BD-F9D4FC4D4792/click 200 2847 ms - 74 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element {"using":"accessibility id","value":"16/44.1 kHz"}
> [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","16/44....
> [debug] [XCUITest] Executing command 'findElement'
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/element] with body: {"using":"accessibility id"...
> [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"140854...
> [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"1408544D-95AD-4...
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element 200 1291 ms - 179 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element/1408544D-95AD-40CF-BC9F-B3B0C6B721EF/click {"id":"1408544D-95AD-40CF-BC9F-B3B0C6B721EF"}
> [MJSONWP] Calling AppiumDriver.click() with args: ["1408544D-95AD-40CF-BC9F-B...
> [debug] [XCUITest] Executing command 'click'
> [JSONWP Proxy] Proxying [POST /uiaElement/1408544D-95AD-40CF-BC9F-B3B0C6B721EF/scroll] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/uiaElement/1408544D-95AD-40CF-BC9F-B3B0C6B721EF/scroll] with body: {"toVisible":true}
> [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"27...
> [JSONWP Proxy] Proxying [POST /element/1408544D-95AD-40CF-BC9F-B3B0C6B721EF/click] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/element/1408544D-95AD-40CF-BC9F-B3B0C6B721EF/click] with body: {}
> (node:22617) Warning: Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit
> [JSONWP Proxy] Got response with status 200: {"status":0,"id":"1408544D-...
> [MJSONWP] Responding to client with driver.click() result: ""
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element/1408544D-95AD-40CF-BC9F-B3B0C6B721EF/click 200 2939 ms - 74 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element {"using":"class name","value":"XCUIElementTypeSlider"}
> [MJSONWP] Calling AppiumDriver.findElement() with args: ["class name","XCUIElementT...
> [debug] [XCUITest] Executing command 'findElement'
> [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/element] with body: {"using":"class name","value..
> [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"E3F5F1...
> [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"E3F5F1FA-0650-4...
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element 200 1573 ms - 166 
> [HTTP] --> POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element/E3F5F1FA-0650-49B5-BAD0-BE2CC85DF0E9/value {"id":"E3F5F1FA-0650-49B5-BAD0-BE2CC85DF0E9","value":["1"]}
> [MJSONWP] Calling AppiumDriver.setValue() with args: [["1"],"E3F5F1FA-0650-49B5-...
> [debug] [XCUITest] Executing command 'setValue'
> [JSONWP Proxy] Proxying [POST /element/E3F5F1FA-0650-49B5-BAD0-BE2CC85DF0E9/value] to [POST http://localhost:8100/session/27740E6E-BA8E-4FAE-A1F8-53C02873A0E5/element/E3F5F1FA-0650-49B5-BAD0-BE2CC85DF0E9/value] with body: {"value":["1"]}
> [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com....
> [HTTP] <-- POST /wd/hub/session/004a9542-1e71-416c-bb75-2d6e41c2693c/element/E3F5F1FA-0650-49B5-BAD0-BE2CC85DF0E9/value 500 7110 ms - 304 
> [debug] [iProxy] recv failed: Resource temporarily unavailable
> [debug] [iProxy] recv failed: Operation not permitted..
```

---

@imurchie commented on [Fri Nov 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/278#issuecomment-258535823)

It seems the upstream project does not correctly handle the slider setting.

Unfortunately, the Apple-provided method for doing this does not currently work. :(

---

@tomachi commented on [Thu Nov 24 2016](https://github.com/appium/appium-xcuitest-driver/issues/278#issuecomment-262722862)

We also have this issue. 
Is there a solution in the near future?

---

@Siddh010 commented on [Thu Dec 01 2016](https://github.com/appium/appium-xcuitest-driver/issues/278#issuecomment-264124765)

We are also facing same issue . Is there any workaround.. 

---

@jlipps commented on [Thu Dec 01 2016](https://github.com/appium/appium-xcuitest-driver/issues/278#issuecomment-264347125)

Wait for appium 1.6.2 which will be published today or tomorrow

**Comment by jarmy** [comment]
I picked up Appium 1.6.2 and still cannot control a XCUIElementTypeSlider: `[MJSONWP] Responding to client with driver.setValue() result: null`

As you can see through the server output, the value remains 83% after using setValue(1.0)

`
2016-12-09 16:54:59:902 - [HTTP] --> POST /wd/hub/session 2016-12-09 18:10:51:572 - [Appium] Welcome to Appium v1.6.2 (REV 696e4dea3fb82038e80bf881813e403ceaee0003)
2016-12-09 18:10:51:574 - [Appium] Non-default server args:
2016-12-09 18:10:51:575 - [Appium]   sessionOverride: true
2016-12-09 18:10:51:575 - [Appium]   loglevel: 'debug:info'
2016-12-09 18:10:51:576 - [Appium]   logTimestamp: true
2016-12-09 18:10:51:577 - [Appium]   defaultCapabilities: { newCommandTimeout: 5000 }
2016-12-09 18:10:51:578 - [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
2016-12-09 18:10:51:578 - [Appium]   newCommandTimeout: 5000
2016-12-09 18:10:51:651 - [Appium] Appium REST http interface listener started on 0.0.0.0:4723
2016-12-09 18:12:49:989 - [HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"/Users/jarmy/src/pandora/git/mobile-test/builds/Pandora.app","preventWDAAttachments":false,"noReset":false,"appiumVersion":"1.6.2","deviceName":"iPhone 6","launchTimeout":90000,"fullReset":true,"showXcodeLog":false,"screenshotWaitTimeout":45,"newCommandTimeout":12000,"platformVersion":"10.0","automationName":"XCUITest","platformName":"iOS"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"/Users/jarmy/src/pandora/git/mobile-test/builds/Pandora.app","preventWDAAttachments":false,"noReset":false,"appiumVersion":"1.6.2","deviceName":"iPhone 6","launchTimeout":90000,"fullReset":true,"showXcodeLog":false,"screenshotWaitTimeout":45,"newCommandTimeout":12000,"platformVersion":"10.0","automationName":"XCUITest","platformName":"iOS"},"requiredCapabilities":{}}
2016-12-09 18:12:49:992 - [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/jarmy/src/pandora/git/mobile-test/builds/Pandora.app","preventWDAAttachments":false,"noReset":false,"appiumVersion":"1.6.2","deviceName":"iPhone 6","launchTimeout":90000,"fullReset":true,"showXcodeLog":false,"screenshotWaitTimeout":45,"newCommandTimeout":12000,"platformVersion":"10.0","automationName":"XCUITest","platformName":"iOS"},{},{"desiredCapabilities":{"app":"/Users/jarmy/src/pandora/git/mobile-test/builds/Pandora.app","preventWDAAttachments":false,"noReset":false,"appiumVersion":"1.6.2","deviceName":"iPhone 6","launchTimeout":90000,"fullReset":true,"showXcodeLog":false,"screenshotWaitTimeout":45,"newCommandTimeout":12000,"platformVersion":"10.0","automationName":"XCUITest","platformName":"iOS"},"requiredCapabilities":{}},null,null]
2016-12-09 18:12:49:996 - [Appium] Creating new XCUITestDriver session
2016-12-09 18:12:49:996 - [Appium] Capabilities:
2016-12-09 18:12:49:997 - [Appium]   app: '/Users/jarmy/src/pandora/git/mobile-test/builds/Pandora.app'
2016-12-09 18:12:49:998 - [Appium]   preventWDAAttachments: false
2016-12-09 18:12:49:998 - [Appium]   noReset: false
2016-12-09 18:12:49:998 - [Appium]   appiumVersion: '1.6.2'
2016-12-09 18:12:49:999 - [Appium]   deviceName: 'iPhone 6'
2016-12-09 18:12:49:999 - [Appium]   launchTimeout: 90000
2016-12-09 18:12:49:999 - [Appium]   fullReset: true
2016-12-09 18:12:49:999 - [Appium]   showXcodeLog: false
2016-12-09 18:12:49:999 - [Appium]   screenshotWaitTimeout: 45
2016-12-09 18:12:50:000 - [Appium]   newCommandTimeout: 12000
2016-12-09 18:12:50:000 - [Appium]   platformVersion: '10.0'
2016-12-09 18:12:50:000 - [Appium]   automationName: 'XCUITest'
2016-12-09 18:12:50:000 - [Appium]   platformName: 'iOS'
2016-12-09 18:12:50:002 - [debug] [XCUITest] XCUITestDriver version: 2.0.37
2016-12-09 18:12:50:008 - [BaseDriver] The following capabilities were provided, but are not recognized by appium: preventWDAAttachments, appiumVersion.
2016-12-09 18:12:50:041 - [BaseDriver] Session created with session id: 9ba35bca-2bbe-4c58-bc85-c29d79f449d3
2016-12-09 18:12:50:103 - [debug] [XCUITest] Xcode version set to '8.1'
2016-12-09 18:12:50:116 - [debug] [XCUITest] iOS SDK Version set to '10.1'
`

`
016-12-09 18:15:14:051 - [HTTP] --> POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element {"using":"class name","value":"XCUIElementTypeSlider"}
2016-12-09 18:15:14:051 - [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["class name","XCUIElementTypeSlider","9ba35bca-2bbe-4c58-bc85-c29d79f449d3"]
2016-12-09 18:15:14:051 - [debug] [XCUITest] Executing command 'findElement'
2016-12-09 18:15:14:054 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
2016-12-09 18:15:14:054 - [debug] [BaseDriver] Waiting up to 100 ms for condition
2016-12-09 18:15:14:055 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element] with body: {"using":"class name","value":"XCUIElementTypeSlider"}
2016-12-09 18:15:14:355 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"45BB232A-4957-4FCF-AA52-58FA4EC98A73","type":"XCUIElementTypeSlider","label":null},"sessionId":"719E5856-368C-4E67-851B-FC62975AD2DC","status":0}
2016-12-09 18:15:14:361 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"45BB232A-4957-4FCF-AA52-58FA4EC98A73","type":"XCUIElementTypeSlider","label":null}
2016-12-09 18:15:14:363 - [HTTP] <-- POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element 200 311 ms - 166 
2016-12-09 18:15:14:377 - [HTTP] --> GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed {}
2016-12-09 18:15:14:378 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2016-12-09 18:15:14:378 - [debug] [XCUITest] Executing command 'proxyReqRes'
2016-12-09 18:15:14:380 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed] with body: {}
2016-12-09 18:15:14:506 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
2016-12-09 18:15:14:507 - [JSONWP Proxy] Replacing sessionId 719E5856-368C-4E67-851B-FC62975AD2DC with 9ba35bca-2bbe-4c58-bc85-c29d79f449d3
2016-12-09 18:15:14:507 - [HTTP] <-- GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed 200 130 ms - 76 
2016-12-09 18:15:14:518 - [HTTP] --> GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed {}
2016-12-09 18:15:14:518 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2016-12-09 18:15:14:518 - [debug] [XCUITest] Executing command 'proxyReqRes'
2016-12-09 18:15:14:520 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed] with body: {}
2016-12-09 18:15:14:652 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
2016-12-09 18:15:14:652 - [JSONWP Proxy] Replacing sessionId 719E5856-368C-4E67-851B-FC62975AD2DC with 9ba35bca-2bbe-4c58-bc85-c29d79f449d3
2016-12-09 18:15:14:653 - [HTTP] <-- GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/displayed 200 135 ms - 76 
2016-12-09 18:15:14:663 - [HTTP] --> GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/attribute/value {}
2016-12-09 18:15:14:664 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2016-12-09 18:15:14:664 - [debug] [XCUITest] Executing command 'proxyReqRes'
2016-12-09 18:15:14:667 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/attribute/value] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/attribute/value] with body: {}
2016-12-09 18:15:14:792 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"83%\",\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
`

First response with 83%:
`
2016-12-09 18:15:14:793 - [JSONWP Proxy] Replacing sessionId 719E5856-368C-4E67-851B-FC62975AD2DC with 9ba35bca-2bbe-4c58-bc85-c29d79f449d3
2016-12-09 18:15:14:793 - [HTTP] <-- GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/45BB232A-4957-4FCF-AA52-58FA4EC98A73/attribute/value 200 130 ms - 77 
2016-12-09 18:15:31:286 - [HTTP] --> POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element {"using":"class name","value":"XCUIElementTypeSlider"}
2016-12-09 18:15:31:290 - [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["class name","XCUIElementTypeSlider","9ba35bca-2bbe-4c58-bc85-c29d79f449d3"]
2016-12-09 18:15:31:291 - [debug] [XCUITest] Executing command 'findElement'
2016-12-09 18:15:31:292 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
2016-12-09 18:15:31:293 - [debug] [BaseDriver] Waiting up to 100 ms for condition
2016-12-09 18:15:31:293 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element] with body: {"using":"class name","value":"XCUIElementTypeSlider"}
2016-12-09 18:15:31:563 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"EBE47A96-9631-4371-A91F-BAE51F052F0F","type":"XCUIElementTypeSlider","label":null},"sessionId":"719E5856-368C-4E67-851B-FC62975AD2DC","status":0}
2016-12-09 18:15:31:564 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"EBE47A96-9631-4371-A91F-BAE51F052F0F","type":"XCUIElementTypeSlider","label":null}
2016-12-09 18:15:31:565 - [HTTP] <-- POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element 200 278 ms - 166 
2016-12-09 18:15:31:577 - [HTTP] --> GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/EBE47A96-9631-4371-A91F-BAE51F052F0F/displayed {}
2016-12-09 18:15:31:578 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2016-12-09 18:15:31:578 - [debug] [XCUITest] Executing command 'proxyReqRes'
2016-12-09 18:15:31:581 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/EBE47A96-9631-4371-A91F-BAE51F052F0F/displayed] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/EBE47A96-9631-4371-A91F-BAE51F052F0F/displayed] with body: {}
2016-12-09 18:15:31:703 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
2016-12-09 18:15:31:703 - [JSONWP Proxy] Replacing sessionId 719E5856-368C-4E67-851B-FC62975AD2DC with 9ba35bca-2bbe-4c58-bc85-c29d79f449d3
2016-12-09 18:15:31:704 - [HTTP] <-- GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/EBE47A96-9631-4371-A91F-BAE51F052F0F/displayed 200 126 ms - 76 
`

Set XCUIElementTypeSlider to 1.0
`
2016-12-09 18:15:31:714 - [HTTP] --> POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element {"using":"class name","value":"XCUIElementTypeSlider"}
2016-12-09 18:15:31:714 - [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["class name","XCUIElementTypeSlider","9ba35bca-2bbe-4c58-bc85-c29d79f449d3"]
2016-12-09 18:15:31:715 - [debug] [XCUITest] Executing command 'findElement'
2016-12-09 18:15:31:717 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
2016-12-09 18:15:31:718 - [debug] [BaseDriver] Waiting up to 100 ms for condition
2016-12-09 18:15:31:718 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element] with body: {"using":"class name","value":"XCUIElementTypeSlider"}
2016-12-09 18:15:31:975 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"F730360F-569A-4D79-80A9-6FF067C894C2","type":"XCUIElementTypeSlider","label":null},"sessionId":"719E5856-368C-4E67-851B-FC62975AD2DC","status":0}
2016-12-09 18:15:31:976 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"F730360F-569A-4D79-80A9-6FF067C894C2","type":"XCUIElementTypeSlider","label":null}
2016-12-09 18:15:31:976 - [HTTP] <-- POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element 200 262 ms - 166 
2016-12-09 18:15:31:990 - [HTTP] --> POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/F730360F-569A-4D79-80A9-6FF067C894C2/value {"id":"F730360F-569A-4D79-80A9-6FF067C894C2","value":["1.0"]}
2016-12-09 18:15:31:990 - [debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["1.0"],"F730360F-569A-4D79-80A9-6FF067C894C2","9ba35bca-2bbe-4c58-bc85-c29d79f449d3"]
2016-12-09 18:15:31:991 - [debug] [XCUITest] Executing command 'setValue'
2016-12-09 18:15:31:994 - [debug] [JSONWP Proxy] Proxying [GET /element/F730360F-569A-4D79-80A9-6FF067C894C2/attribute/type] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/F730360F-569A-4D79-80A9-6FF067C894C2/attribute/type] with no body
2016-12-09 18:15:32:119 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeSlider\",\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
2016-12-09 18:15:32:120 - [debug] [JSONWP Proxy] Proxying [POST /element/F730360F-569A-4D79-80A9-6FF067C894C2/value] to [POST http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/F730360F-569A-4D79-80A9-6FF067C894C2/value] with body: {"value":["1",".","0"]}
2016-12-09 18:15:33:005 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"719E5856-368C-4E67-851B-FC62975AD2DC","status":0}
2016-12-09 18:15:33:005 - [debug] [MJSONWP] Responding to client with driver.setValue() result: null
2016-12-09 18:15:33:006 - [HTTP] <-- POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/F730360F-569A-4D79-80A9-6FF067C894C2/value 200 1016 ms - 76 
2016-12-09 18:16:06:776 - [HTTP] --> POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element {"using":"class name","value":"XCUIElementTypeSlider"}
`

Second response with 83%
`
2016-12-09 18:16:06:777 - [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["class name","XCUIElementTypeSlider","9ba35bca-2bbe-4c58-bc85-c29d79f449d3"]
2016-12-09 18:16:06:777 - [debug] [XCUITest] Executing command 'findElement'
2016-12-09 18:16:06:780 - [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
2016-12-09 18:16:06:780 - [debug] [BaseDriver] Waiting up to 100 ms for condition
2016-12-09 18:16:06:782 - [debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element] with body: {"using":"class name","value":"XCUIElementTypeSlider"}
2016-12-09 18:16:07:057 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"43907CA6-078D-475F-893F-B00A1E64E251","type":"XCUIElementTypeSlider","label":null},"sessionId":"719E5856-368C-4E67-851B-FC62975AD2DC","status":0}
2016-12-09 18:16:07:058 - [debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"43907CA6-078D-475F-893F-B00A1E64E251","type":"XCUIElementTypeSlider","label":null}
2016-12-09 18:16:07:059 - [HTTP] <-- POST /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element 200 282 ms - 166 
2016-12-09 18:16:07:072 - [HTTP] --> GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed {}
2016-12-09 18:16:07:072 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2016-12-09 18:16:07:073 - [debug] [XCUITest] Executing command 'proxyReqRes'
2016-12-09 18:16:07:078 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed] with body: {}
2016-12-09 18:16:07:210 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
2016-12-09 18:16:07:210 - [JSONWP Proxy] Replacing sessionId 719E5856-368C-4E67-851B-FC62975AD2DC with 9ba35bca-2bbe-4c58-bc85-c29d79f449d3
2016-12-09 18:16:07:212 - [HTTP] <-- GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed 200 139 ms - 76 
2016-12-09 18:16:07:223 - [HTTP] --> GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed {}
2016-12-09 18:16:07:223 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2016-12-09 18:16:07:224 - [debug] [XCUITest] Executing command 'proxyReqRes'
2016-12-09 18:16:07:228 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed] with body: {}
2016-12-09 18:16:07:386 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
2016-12-09 18:16:07:386 - [JSONWP Proxy] Replacing sessionId 719E5856-368C-4E67-851B-FC62975AD2DC with 9ba35bca-2bbe-4c58-bc85-c29d79f449d3
2016-12-09 18:16:07:387 - [HTTP] <-- GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/displayed 200 164 ms - 76 
2016-12-09 18:16:07:398 - [HTTP] --> GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/attribute/value {}
2016-12-09 18:16:07:398 - [MJSONWP] Driver proxy active, passing request on via HTTP proxy
2016-12-09 18:16:07:399 - [debug] [XCUITest] Executing command 'proxyReqRes'
2016-12-09 18:16:07:403 - [debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/9ba35bca-2bbe-4c58-bc85-c29d79f449d3/element/43907CA6-078D-475F-893F-B00A1E64E251/attribute/value] to [GET http://localhost:8100/session/719E5856-368C-4E67-851B-FC62975AD2DC/element/43907CA6-078D-475F-893F-B00A1E64E251/attribute/value] with body: {}
2016-12-09 18:16:07:529 - [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"83%\",\n  \"sessionId\" : \"719E5856-368C-4E67-851B-FC62975AD2DC\",\n  \"status\" : 0\n}"
`

**Comment by jlipps** [comment]
@marekcirkos wasn't this fixed in WDA? do you remember which commit hash it was fixed at? does WDA also handle the case where "1.0" is sent as an array `["1", ".", "0"]`?

**Comment by marekcirkos** [comment]
@jlipps  It should join it if you send an array https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L153

Hash: https://github.com/facebook/WebDriverAgent/commit/d82dd9192e7224d9cacd7faa10fffc8902a68496

**Comment by tomachi** [comment]
Have the same issue with 1.6.2.
Still doesn't recognize slider sendKeys("1.0")

**Comment by jlipps** [comment]
@marekcirkos is slider value setting not working in WDA a known issue?

**Comment by Siddh010** [comment]
Work fine for me now after upgrade to1.6.3 appium .  Thank you

**Comment by marekcirkos** [comment]
@jlipps Not that I know of.

**Comment by dpgraham** [comment]
This issue was resolved in WebDriverAgent https://github.com/facebook/WebDriverAgent/commit/d5694557113d6f875457472c7bb0501e21155ec5.

Appium 1.6.3 should have the latest webdriveragent with this fix in it. I'm going to confirm right now and then close this ticket.

**Comment by dpgraham** [comment]
Closing this issue but we're still having some issues with 'sliders' that need to be resolved

See https://github.com/appium/appium/issues/7626

**Comment by suganeby** [comment]
@dpgraham
I am using Appium 1.6.3 but still i am having the issue in setting value to the slider.

**Comment by ssimakurthy** [comment]
@dpgraham.. Is there any fix on sliders.. I am using v1.6.6-beta.2. and not able to slide the slider

**Comment by vikramvi** [comment]
@ssimakurthy please refer to 7626 for details

**Comment by sravanimadineni** [comment]
WebElement size=driver.findElement(By.xpath("/XCUIElementTypeSlider"));
		size.sendKeys("1%");
here 1% is equal to 100% (it move to the end)
when u keep it to 0.1 then equal to 10%
