### ISSUE TITLE
setOrientation (landscape/ portrait) throws error " Error response status: 777"

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7442]
@khanhdodang commented on [Fri Nov 25 2016](https://github.com/appium/appium-xcuitest-driver/issues/313)

As [documentation](https://github.com/admc/wd/blob/master/doc/api.md), we can use setOrientation with two values `landscape` and `portrait` to rotate on devices.

1. I use two commands below and run pass with Xcode 7 & Appium 1.5.3.
```
.setOrientation('landscape')
.setOrientation('portrait')
```

2. It doesn't work with the Xcode version 8.1 & Appium 1.6.0. It throws errors:
```
     Uncaught Error: [setOrientation("landscape")] Error response status: 777
      at exports.newError (node_modules/wd/lib/utils.js:139:13)
      at node_modules/wd/lib/callbacks.js:33:23
      at node_modules/wd/lib/webdriver.js:174:5
      at Request._callback (node_modules/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

---

@jlipps commented on [Mon Nov 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/313#issuecomment-263434914)

@khanhdodang you'll need to attach a gist of your full server logs for us to diagnose this.

**Comment by hoverduck** [comment]
I'm having the same problem.  Here is a gist of my server logs - https://gist.github.com/hoverduck/fb5752f7d9b31ca0bb95c822a8518061

The issue happens (at least for me) when I attempt to rotate the device on an app that doesn't have a corresponding view set up.  In this case, my login screen doesn't support a landscape orientation on iPhone, but once you're logged in you can rotate no problem.  So I can work around this by delaying my `setOrientation` call until I'm logged in.

**Comment by imurchie** [comment]
Please upgrade to the latest version (1.6.3 as of now). Much has been fixed.

**Comment by hoverduck** [comment]
@imurchie I've updated to 1.6.3 and still have the same problem.  Let me know if updated logs would be helpful.

**Comment by jlipps** [comment]
@hoverduck can you attach new 1.6.3 logs, though? it should have extra debug information which might make it more clear what's going on

**Comment by hoverduck** [comment]
Sure thing - https://gist.github.com/hoverduck/1664f76e2c48c49fa0607f63ae8c4245

**Comment by jlipps** [comment]
@hoverduck it's as I suspected. Look at this line:

> 2016-12-14 21:18:49:113 - info: [debug] [JSONWP Proxy] Got response with status 200: {"value":"Unable To Rotate Device","sessionId":"94BAC213-6713-4B7D-9F48-82236AC57468","status":777}

This is the response from WebDriverAgent to the orientation command. (Note that it is a status 200 response. According to the protocol, this should be a 500, cc @marekcirkos). In any case, this is the underlying automation technology saying it couldn't perform the rotation. You'll want to open an issue at https://github.com/facebook/WebDriverAgent instead.

The reason it worked in Xcode 7 / appium 1.5.3 is that we were using a completely different automation technology, which Apple removed in Xcode 8. So a lot of things have changed. See https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md for more information.

**Comment by hoverduck** [comment]
Aha!  Thanks for taking a look.
