### ISSUE TITLE
click the same element twice or more, throw a uiautomator exception

### ISSUE THREAD

**Issue by sravanmedarapu** [appium/appium#7517]
@wenshi11019 commented on [Thu Dec 01 2016](https://github.com/appium/appium-uiautomator2-server/issues/40)

when I click the same element twice or more, use two of the same click on the statements, or use the for statement, it will throw a exception.

sometimes before i click the element, use `Thread.sleep(1000)`,it can run success, but sometime  it still throw the same exception

appium version:1.6.1
appium-uiautomator2-server version: 0.0.6

` org.openqa.selenium.StaleElementReferenceException: android.support.test.uiautomator.StaleObjectException
	at android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)
	at android.support.test.uiautomator.UiObject2.getVisibleBounds(UiObject2.java:210)
	at android.support.test.uiautomator.UiObject2.getVisibleCenter(UiObject2.java:251)
	at android.support.test.uiautomator.UiObject2.click(UiObject2.java:343)
	at io.appium.uiautomator2.model.UiObject2Element.click(UiObject2Element.java:42)
	at io.appium.uiautomator2.handler.Click.safeHandle(Click.java:39)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:818)`

---

@sravanmedarapu commented on [Thu Dec 01 2016](https://github.com/appium/appium-uiautomator2-server/issues/40#issuecomment-264074911)

Have you tried by setting implicit wait ?

---

@wenshi11019 commented on [Thu Dec 01 2016](https://github.com/appium/appium-uiautomator2-server/issues/40#issuecomment-264094336)

@sravanmedarapu it doesn't work, and thorw the same exception. But use the Thread.sleep() can work.

---

@sravanmedarapu commented on [Thu Dec 01 2016](https://github.com/appium/appium-uiautomator2-server/issues/40#issuecomment-264098140)

@wenshi11019 is the element in scrollable view ?

---

@wenshi11019 commented on [Thu Dec 01 2016](https://github.com/appium/appium-uiautomator2-server/issues/40#issuecomment-264151400)

@sravanmedarapu yeah, I click the contacts elements twice, or click back button twice.

---

@sravanmedarapu commented on [Thu Dec 01 2016](https://github.com/appium/appium-uiautomator2-server/issues/40#issuecomment-264160194)

Unlike Google UiAutomator, UiAutomator2 throws `StaleObjectException` when the underlying view is changed.

Please refer this: https://github.com/appium/appium-uiautomator2-server/wiki#behavioral-changes-with-respect-to-existing-appium-android-driverbootstrap

However this is something we should look into and find optimal solution.

As a work around, you can try to re find the element when the underlying view is changed.

---

@wenshi11019 commented on [Thu Dec 01 2016](https://github.com/appium/appium-uiautomator2-server/issues/40#issuecomment-264169654)

Thanks, I try this way.

**Comment by mykola-mokhnach** [comment]
_StaleElementReferenceException_ means that an element whose internal id is cached in your client code does not exist in the tree anymore and/or is replaced with an element with another internal id. For example:

```java
WebElement el = driver.findElement(locator);
el.click();
// The actual state, of the element stored in el variable might be already changed
el.click();
```

in order to avoid this exception you need to change your client code:

```java
WebElement el = driver.findElement(locator);
el.click();
el = driver.findElement(locator);
// We 'refreshed' the internal id of the cached element, so there should be no exceptions anymore
el.click();
```

**Comment by pisarenco92** [comment]
I encounter that exception often.  If the test is executed 5 times - once StaleObjectException exception is thrown.

[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",5000,"46690bfb-d144-453b-b085-58fe7cb2f6d6"]
[debug] [BaseDriver] Set implicit wait to 5000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/46690bfb-d144-453b-b085-58fe7cb2f6d6/timeouts 200 3 ms - 76 
[HTTP] --> POST /wd/hub/session/46690bfb-d144-453b-b085-58fe7cb2f6d6/elements {"using":"id","value":"imageViewRemoveFromWishList"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["id","imageViewRemoveFromWishList","46690bfb-d144-453b-b085-58fe7cb2f6d6"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8200/wd/hub/session/fb3b51b4-0bff-4de6-a7ab-0cb7af01f443/elements] with body: {"strategy":"id","selector":"imageViewRemoveFromWishList","context":"","multiple":true}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"fb3b51b4-0bff-4de6-a7ab-0cb7af01f443","status":0,"value":[{"ELEMENT":"0a71b321-1203-4045-a898-50b051310b98"}]}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"0a71b321-1203-4045-a898-50b051310b98"}]
[HTTP] <-- POST /wd/hub/session/46690bfb-d144-453b-b085-58fe7cb2f6d6/elements 200 46 ms - 124 
[HTTP] --> POST /wd/hub/session/46690bfb-d144-453b-b085-58fe7cb2f6d6/timeouts {"type":"implicit","ms":5000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",5000,"46690bfb-d144-453b-b085-58fe7cb2f6d6"]
[debug] [BaseDriver] Set implicit wait to 5000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/46690bfb-d144-453b-b085-58fe7cb2f6d6/timeouts 200 2 ms - 76 
[HTTP] --> GET /wd/hub/session/46690bfb-d144-453b-b085-58fe7cb2f6d6/element/0a71b321-1203-4045-a898-50b051310b98/displayed {}
[debug] [MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["0a71b321-1203-4045-a898-50b051310b98","46690bfb-d144-453b-b085-58fe7cb2f6d6"]
[debug] [JSONWP Proxy] Proxying [GET /element/0a71b321-1203-4045-a898-50b051310b98/attribute/displayed] to [GET http://localhost:8200/wd/hub/session/fb3b51b4-0bff-4de6-a7ab-0cb7af01f443/element/0a71b321-1203-4045-a898-50b051310b98/attribute/displayed] with body: {}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"sessionId":"fb3b51b4-0bff-4de6-a7ab-0cb7af01f443","status":10,"value":"android.support.test.uiautomator.StaleObjectException\n\tat android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)\n\tat android.support.test.uiautomator.UiObject2.hashCode(UiObject2.java:105)\n\tat java.lang.Object.toString(Object.java:355)\n\tat java.util.Formatter.transform(Formatter.java:1421)\n\tat java.util.Formatter.doFormat(Formatter.java:1081)\n\tat java.util.Formatter.format(Formatter.java:1042)\n\tat java.util.Formatter.format(Formatter.java:1011)\n\tat java.lang.String.format(String.java:1554)\n\tat java.lang.String.format(String.java:1528)\n\tat io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:91)\n\tat io.appium.uiautomator2.model.UiObject2Element.getBoolAttribute(UiObject2Element.java:113)\n\tat io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:40)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\n\tat java.lang.Thread.run(Thread.java:818)\n"}} ProxyRequestError: Could not proxy command to remote server. Original error: 500 - "{\"sessionId\":\"fb3b51b4-0bff-4de6-a7ab-0cb7af01f443\",\"status\":10,\"value\":\"android.support.test.uiautomator.StaleObjectException\\n\\tat android.support.test.uiautomator.UiObject2.getAccessibilityNodeInfo(UiObject2.java:629)\\n\\tat android.support.test.uiautomator.UiObject2.hashCode(UiObject2.java:105)\\n\\tat java.lang.Object.toString(Object.java:355)\\n\\tat java.util.Formatter.transform(Formatter.java:1421)\\n\\tat java.util.Formatter.doFormat(Formatter.java:1081)\\n\\tat java.util.Formatter.format(Formatter.java:1042)\\n\\tat java.util.Formatter.format(Formatter.java:1011)\\n\\tat java.lang.String.format(String.java:1554)\\n\\tat java.lang.String.format(String.java:1528)\\n\\tat io.appium.uiautomator2.utils.ReflectionUtils.invoke(ReflectionUtils.java:91)\\n\\tat io.appium.uiautomator2.model.UiObject2Element.getBoolAttribute(UiObject2Element.java:113)\\n\\tat io.appium.uiautomator2.handler.GetElementAttribute.safeHandle(GetElementAttribute.java:40)\\n\\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201)\\n\\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192)\\n\\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)\\n\\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)\\n\\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\\n\\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\\n\\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\\n\\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)\\n\\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)\\n\\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)\\n\\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)\\n\\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)\\n\\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)\\n\\tat java.lang.Thread.run(Thread.java:818)\\n\"}"
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- GET /wd/hub/session/46690bfb-d144-453b-b085-58fe7cb2f6d6/element/0a71b321-1203-4045-a898-50b051310b98/displayed 500 706 ms - 3940

**Comment by Mikulasi** [comment]
i'm interesting in which version of Appium it is going to be fixed? For now there are lots of efforts to maintain tests because of StaleObjectException

**Comment by Mikulasi** [comment]
the way described by @mykola-mokhnach is not acceptable and from developers point of view this is a crutch

**Comment by mykola-mokhnach** [comment]
@Mikulasi Appium is open-source. Everybody is welcome to submit a patch.

**Comment by Corji** [comment]
Facing this issue as well. I had to move to uiautmator2 because my test stopped running with Android 7.0 and uiautomator. Are there any News?

**Comment by jlipps** [comment]
@sravanmedarapu what do you think, should we have a mode for the server that re-finds an element using a cached locator strategy if we run into a stale element exception?

**Comment by mekxtari** [comment]
I've also came across to this issue. I started refactoring my old automation scripts to work with uiautomator2 driver. Reason for this was to support android 7 devices. Unfortunately StaleElementReferenceException causes massive headache. I thought that removing couple of scripts from executing could do the trick. It seems that this happens it bit randomly in different part of our automation script. I'm afraid i have to go back to use the old driver because i have no clue how to create a workaround for this.

**Comment by fdPoornima** [comment]
Hi, Is there any update on this? As @mekxtari  mentioned, I had also moved to uiautomator2 driver for Android7, and am facing this stale element exception too often. I cannot move back to the old driver because some pages are not recognized. Would appreciate any information in this

**Comment by vmatragun** [comment]
@jlipps and @mykola-mokhnach, can you please provide details on if this issue is put on priority and when should we expect a fix for it? 
I am assuming that lots of people are being impacted as I am, a bit of clarity would be very helpful.

Thank you,
Vladimir.

**Comment by mykola-mokhnach** [comment]
I'd say it is an expected behaviour. Just don't cache your element instance before doing the second click, but invoke findElement once again

**Comment by easydiegochaves** [comment]
Hi Guys,

In my case, this problem also happens the first time you use a findElement. In most cases, when you try to click on an element whose id or classname, for example, exists on the previous screen. As a workaround, I'm having to insert some Sleeps in the code, before findElement.

**Comment by vmatragun** [comment]
@mykola-mokhnach thanks for reaction!
Taking in account that we are using Geb combined with Appium and uiautomator, the issue started to be observed when moving from uiautomator to uiautomator2. Explicitly I am not caching and I have doubds that Geb does, the element is being looked for upon its access.

To be true my expectation was that the transition would be more seamless in terms of expected behaviour and it is more related to the driver or Appium side of things... actually the issue is faced only after moving to uiautomator2, never occurred before 

Assuming all above can you please say if we should expect any reaction from Appium community?

PS: Also I think @sravanmedarapu suggestion on re-finding an element using a cached locator strategy if stale element exception is faced would be a solution.

**Comment by mykola-mokhnach** [comment]
> Also I think @sravanmedarapu suggestion on re-finding an element using a cached locator strategy if stale element exception is faced would be a solution.

My suggestion is the same. Try to cancel caching for that particular element

**Comment by sher04lock** [comment]
What about filtering a collection, e.g. checkboxes, to pick only one with specific text?
There is no locators for _text_ attribute, so you have to find all elements by some other locators, and then filter them up by calling `.text()` on each.

Example in JS:
```
.elementsById("android:id/text1")
    .then(filter(element => element.text().then(text => text.indexOf("word") > -1)))
    .first().click()
```

You could use XPath locator with `[@text='  ']` here, but what if you want to filter more than one element and then do something with reduced collection?

**Comment by igalep** [comment]
The big issue is the apppium's server crash...

once the StaleObjectException was thrown  , the server crashes and you cannot continue your execution.

**Comment by VenkateshPS** [comment]
is there any solution or workaround  to this yet ?

**Comment by igalep** [comment]
I was trying to avoid the element caching but the suggested solution is the way how we work with PageObjects , the element is the Page's property which is being initialised on the page's creation.

By changing it to "driver.findElement" we are breaking the concept ....

I was wonder if there a ways to "refresh" the initialised page object ? 

so by doing that we are refreshing all the cached elements

**Comment by reiversolutions** [comment]
I've recently updated to using UIAutomator2 and I am having the same issue as @igalep. This completely breaks how I've written the page object pattern in the past. 

Are people suggesting we no longer set our `AndroidElement` when the page is instantiated and instead hold `By` locators to be used when needed?

**Comment by knpanzar** [comment]
Same problem as @igalep and @reiversolutions . Any other suggestions for us with PageObjects and UA2?

**Comment by Kignuf** [comment]
In most of my code the elements are not cached, but in one place some are, thus I had this issue as well. Though I implemented a "refresh" element mechanism so that when I catch this exception, I refresh my cached element and then proceed with my click or whatever request I initially intended to do.
ps: using webdriverio

**Comment by Gocoollnath** [comment]
Even with no caching, the issue arises during first click itself.
new WebDriverWait(driver,50).ignoring(StaleElementReferenceException.class).until(ExpectedConditions.elementToBeClickable(By.xpath("(//android.widget.ImageView)[3]")));
MobileElement Complete_btn=driver.findElementByXPath("(//android.widget.ImageView)[3]");
Complete_btn.click();

error thrown is:

stacktrace=StaleElementReferenceError: android.support.test.uiautomator.StaleObjectException

Is "ignoring(StaleElementReferenceException.class) " deprecated?

**Comment by Quilmont** [comment]
This is a major issue present. Version 1.7.2 and below seem to be experiencing this issue. Especially on Android 7....Anyone over come this? Kinda goes against the whole framework technique if we are having to find an locate the same UI object over and over again.

**Comment by cristiannaziru** [comment]
Hello, 

I have this issue on my project as well. I have an waitForElem method that waits for the element and retries to find it for a period of time. However, it didn't fix my problem everytime. After discussing with a colleague, he suggested I use a try/catch on the tap method as well, and if it throws a StaleObjectException I re-do the try line into the catch syntax. I'll let you know if this fixes this issue. 

However, it's a bit weird that back when I used the 'appium' webdriver server, nothing like this was happening, and when using 'uiautomator2' this happens. The latter is less stable than the old one.

**Comment by hansjoergkeser** [comment]
Am also struggling with this in many ways (waitFor-methods among other). E.g in tests I try to get a value from a webelement and i only pass the selector until finally the findElement() is executed. In java:

    protected String getContentDescFromElement(By selector) {
        return findElement(selector).getAttribute("contentDescription");
    }

This often leads to 
org.openqa.selenium.StaleElementReferenceException: android.support.test.uiautomator.StaleObjectException

The element is definitely there, the selector is correct, sometimes the statement can be excecuted, sometimes not. It is impossible to handle all my findElement methods with try catch with retry over retry attempt in the catch block..

**Comment by MioOgbeni** [comment]
Now I'm facing with same error after switching to UiAutomator2. It's occurs mainly on time elements. Is there some way how avoid this error in PageObject?

**Comment by cristiannaziru** [comment]
Hello again,

I managed to find an workaround. I created a stopwatch timer and I look for my element over and over again until I find that it isEnabled(). Since I'm using this method, I didn't encounter the issue at all.  It looks like this:

```
async function waitForElem(driver,  elName, timeout = 5000) {
  let timer = new Stopwatch();
  timer.start();
  let passedTime = timer.elapsed();
  while (passedTime < timeout) {
    try {
          if (await driver.elementByAccessibilityId(elName).isEnabled()) {
            passedTime = timeout;
            return true;
      }catch(err){
           console.log(err);
      }
      timer.stop();
   }
```

**Comment by auto-mator** [comment]
please fix these issues...

**Comment by magicpds** [comment]
Waitting ……

**Comment by Madh93** [comment]
I think the best way to manage this problem to implement PageObject model is to use `#findElements` when element is called instead of refresh all elements defined in `#initPage` or equivalent method.

AboutPage:

```python
from app.pages.base import BasePageObject

class AboutPage(BasePageObject):

    """AboutPage Elements"""

    def back_button(self):
        return self._find_element(self.locators.ABOUT_BACK_BUTTON)

    def app_version(self):
        return self._find_element(self.locators.ABOUT_APP_VERSION)
```
BasePage:

```python
class BasePageObject(object):

    def __init__(self, driver):
        self.driver = driver
        if self.is_android():
            from app.locators.android import AndroidLocators as Locators
        else:
            from app.locators.ios import IOSLocators as Locators
        self.locators = Locators

    def is_android(self):
        return self.driver.capabilities['platformName'].upper() == 'ANDROID'

    def is_ios(self):
        return self.driver.capabilities['platformName'].upper() == 'IOS'

    """BasePage Private Methods"""

    def _find_element(self, locator):
        try:
            return self.driver.find_element(*locator)
        except NoSuchElementException:
            logging.warning(f"Required element {locator} in {self} was not found.")
            return None
```
Example:

```python
about = AboutPage(driver)
about.app_version().text # => '1.0.0'
```
Elements are not cached but, but it faster than refresh all elements before selecting one.

**Comment by mykola-mokhnach** [comment]
It seems like this problem has been already fixed

**Comment by swat-droid** [comment]
No The issue is still there.

**Comment by Srinija90** [comment]
This still happens when clicking the same element twice.

I tried finding the element each time before clicking it but no luck.

```
val el = driver.findElement(By.xpath(<my_locator>)) as MobileElement
el.click() // THIS WORKS

val el2 = driver.findElement(By.xpath(<my_locator>)) as MobileElement
WebDriverWait(driver,1000).until(ExpectedConditions.visibilityOf(el2)) // THIS FAILS
el2.click()
```
