### ISSUE TITLE
ENOENT: no such file or directory, scandir '/Users/vikram-anna/Library/Android/sdk/platform-tools/build-tools' (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#7686]
## The problem

While trying to run script on appiun native app getting below error ( appium is registered as node on a selenium grid ) 

(An unknown server-side error occurred while processing the command. Original error: ENOENT: no such file or directory, scandir '/Users/vikram-anna/Library/Android/sdk/platform-tools/build-tools' (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac 10.11.6
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Registered appium node with below code

AppiumDriverLocalService driverLocalService1 = AppiumDriverLocalService
                        .buildService(new AppiumServiceBuilder()
                        	.withAppiumJS(new File("/usr/local/lib/node_modules/appium/build/lib/main.js"))
				.usingDriverExecutable(new File("/usr/local/bin/node"))
                                .usingPort(4723)
                                .withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER,"4724")
                                .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
                                .withArgument(GeneralServerFlag.LOG_LEVEL, "debug")
                                .withArgument(GeneralServerFlag.CONFIGURATION_FILE, nodeConfigFilePath)
                        .withCapabilities(new DesiredCapabilities(ImmutableMap.of(MobileCapabilityType.UDID, "000007CF003ACABB"))));
                driverLocalService1.start();

env variable setup

export ANDROID_HOME=/Users/vikram-anna/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

## Link to Appium logs

FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class io.appium.java_client.AppiumDriver: Could not instantiate new WebDriver instance of type class io.appium.java_client.AppiumDriver (An unknown server-side error occurred while processing the command. Original error: ENOENT: no such file or directory, scandir '/Users/vikram-anna/Library/Android/sdk/platform-tools/build-tools' (WARNING: The server did not provide any stacktrace information)

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by vikramvi** [comment]
updated .bash_profile as below

export ANDROID_HOME=/Users/vikram-anna/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/build-tools/$(ls $ANDROID_HOME/build-tools | sort | tail -1):$PATH

but still same error, not sure why appium is going to wrong directory 

'/Users/vikram-anna/Library/Android/sdk/platform-tools/build-tools'

**Comment by vikramvi** [comment]
This is not an appium bug but mistake on my side

1. Eclipse Run Configuration ANDROID_HOME was set to /Users/vikram-anna/Library/Android/sdk/platform_tools changed to /Users/vikram-anna/Library/Android/sdk

2. Also updated .bash_profile per

https://gist.github.com/patrickhammond/4ddbe49a67e5eb1b9c03

**Comment by parveensahu** [comment]
Thanks, I am facing the same problem. Solved now.

**Comment by sanjaysk** [comment]
Hi 
I am facing the same problems on Windows 7 machine pls help

**Comment by RohailQayyum** [comment]
Hi, Vikramvi
    After adopting the same steps(change the path), still the problem is still there. 
now what can I do. If you've any solution then please reply fast.

**Comment by vikramvi** [comment]
@sanjaysk @RohailQayyum Solution is clearly mentioned in my comment dated 12th Jan, please re-read it.

**Comment by RohailQayyum** [comment]
Ireally don't know how to handle this situation, can you please ellaborate more that at where the solution is present


---- On Tue, 21 Nov 2017 05:02:08 -0800 Vikram Ingleshwar &lt;notifications@github.com&gt; wrote ----




@sanjaysk @RohailQayyum Solution is clearly mentioned in my comment dated 12th Jan, please re-read it.

**Comment by AnandSrikumar** [comment]
I'm running from Command prompt! Still same error
