### ISSUE TITLE
Coordinate conversion incorrect on iOS for Safari with multiple tabs open

### ISSUE THREAD

**Issue by mikesalvia** [appium/appium#7851]
## The problem

Coordinate conversion is incorrect on iOS when more than one tab is open.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: iOS 9.3, iOS 10.2
* Real device or emulator/simulator: iPad Air Simulator and iPhone 7
* Appium CLI or Appium.app|exe: CLI

## Details

Working on iOS in Safari doing a web test. When I launch test Safari opens and pages is opened correctly. There is however a tabbed labelled 'Favorites' (NOTE: 'Favorites' not displayed it URL visit is performed manually). After doing some debugging (added click detector on HTML page) it appears that the converted coordinates are actually off by the height of the tab bar.

If 'Favorites' tab was not displayed then there really wouldn't be an issue as the click would be in the correct position however there could be other issues for any test working with multiple tabs in iOS.

**Comment by mykola-mokhnach** [comment]
Which API is used to calculate coordinates? Can you provide the code?
It would be also good to know whether this is portrait or landscape mode and have a screenshot(s). Without this information it's literally impossible to fix anything.

**Comment by mikesalvia** [comment]
Writing in Ruby using Capybara with Site Prism and connecting to an Appium::Capybara::Driver, I am working in portrait mode automating Safari.

Version of Appium-related Gems
```
appium_capybara (1.3.0)
appium_lib (9.2.0)
```

- When using `driver.browser.touch.single_tap(native).perform` (where native is element) when doing so I was noticing that IF another tab was open the click would be pretty far off and even miss the element completely
 - Setting noReset = false and fullReset=true, which resolved the multiple tab issue 'Favorites' (from previous sessions) and seemed to make touch closer to the element
- Still was missing the mark on smaller elements by about same amount of pixels as the iOS system bar
 - Took screenshots and determined height of Safari browser bar including iOS system bar it was 128 Retina pixels or 64 pixels

Then put together this `Appium::TouchAction.new.tap(:x => native.location.x + (native.size.width / 2), :y => native.location.y + (native.size.height / 2) + 64, :count => 1).perform`, this ends up clicking the exact center of the element, still does not resolve issue when having multiple tabs but will create a exact center click on elements tested in iOS 9.3 and 10.2 (using Simulators).

I can provide screenshots of the click points per function with Safari in various states.

**Comment by jlipps** [comment]
@mikesalvia why are you using native tap methods to tap on web elements? and if this is something you want to do consistently, did you try just setting the `nativeWebTap` capability to `true`?

**Comment by mikesalvia** [comment]
@jlipps Sorry for the delay on this... We don't necessarily want to use the `Appium::TouchAction` BUT when using the built in click with `nativeWebTap` set to `true` the taps do not actually occur at the center of the element we want to select.

When experimenting I created a sample page that would draw a dot on click or tap events and log the information about interactions.

Using `click` method in Capybara with `nativeWebTap` would consistently be off on the Y axis, X axis has no problem when using `click`.
When using `Appium::TouchAction` we remove 64 pixels for the Safari browser bar which perhaps is what is causing the unwanted Y axis off set.

If desired I can make my example page and provide a sample test to demo this behavior. I will attach screenshots to this issue showing the same element click using both methods.

@jlipps Also big fan of all the stuff you have done for the community, Selenium, and Appium, have followed you for a while so I want to actually say, "Hello!"

**Comment by dpgraham** [comment]
@mikesalvia Sorry for the delay on this, is this still an issue for you?

**Comment by imurchie** [comment]
This is still an issue. Coordinate conversion in Safari in general is messed up when anything has been done to the page.

**Comment by mikesalvia** [comment]
@dpgraham Yes this still does happen for me. @imurchie Thank you for validating it. Would you like screenshots or anymore details on this?

**Comment by dpgraham** [comment]
A screenshot might be helpful actually, thanks.

**Comment by jlipps** [comment]
Sounds like it might be as easy as taking the nav bar into account. I know that changes in iOS versions have sometimes changed whether this is included in the automation libraries.

**Comment by imurchie** [comment]
I investigated this on my long flight home on Friday. I have a fix that I'm experimenting with, but I need to figure out automated testing, and make sure it is not too brittle.

**Comment by jlipps** [comment]
Great, I moved this into the current milestone

**Comment by imurchie** [comment]
`appium-ios-driver` is updated to allow for the change, now working on `appium-xcuitest-driver`

**Comment by mikesalvia** [comment]
@imurchie AWESOME! 👍 Sorry for the delay on screenshots would you still need them? Or would you like help writing tests for the functionality?

**Comment by mikesalvia** [comment]
@imurchie  to @jlipps point I have been using an additional 64 pixel offset on y coordinate to account for the nav bar not only the tabs, will this also be part of the fix?

**Comment by imurchie** [comment]
Can you try upgrading Appium so that you have `appium-xcuitest-driver@2.43.1`, and then run your test? In my tests this now works.

**Comment by mikesalvia** [comment]
I will take a look at this!! 👍

**Comment by jlipps** [comment]
closing this since in our experimentation the problem is resolved. let us know if you run into issues @mikesalvia

**Comment by mikesalvia** [comment]
@jlipps & @imurchie we are much closer but I still see a discrepency but now only down to ~10px I have attached screenshots...
![custom appium_touch function](https://user-images.githubusercontent.com/6209204/29297669-8667a234-8130-11e7-84a2-87e505a85a72.png)
![native click method in ruby](https://user-images.githubusercontent.com/6209204/29297668-866743b6-8130-11e7-8e5b-0c3057a89122.png)

Essentially it looks like there a need for more of a offset on the y-axis I would expect a click in the center of the black box to produce an identical x and y.

**Comment by mikesalvia** [comment]
@jlipps @imurchie BUMP! Since I can't re-open issues I wanted to make sure you guys saw this again! :-)

**Comment by imurchie** [comment]
Can you provide the server logs for the click?

**Comment by mikesalvia** [comment]
Yes I can!

**Comment by mikesalvia** [comment]
@imurchie Just a heads up in the middle of a pretty large release cycle I will get this to you as soon as I possible can. Sorry for the delay.

**Comment by imurchie** [comment]
Ok. I'll take a look at it when you are ready.

**Comment by vsadineni1** [comment]
We are also hitting this in some of our ios Safari tests.

I see the below error in the appium logs:
2017-09-03 00:34:19:674 - [debug] [XCUITest] Converted web coords {"x":511.875,"y":310} into real coords {"x":512,"y":null}

**Comment by jlipps** [comment]
@vsadineni1 can you please provide a full set of logs?

**Comment by vsadineni1** [comment]
@jlipps Here are the logs for 2 instances where the test failed. Can you guys please prioritize this issue? Currently we have a bunch of tests failing on this.

**Link To Appium Server Logs - Case 1 -** https://gist.github.com/anonymous/0e60d27b7ed4db00e83868588befb7c7

2017-09-21 14:54:50:378 - [debug] [XCUITest] Converted web coords {"x":921.1875,"y":644.5} into real coords {"x":921,"y":null}
2017-09-21 14:54:50:380 - [debug] [JSONWP Proxy] Proxying [POST /wda/tap/nil] to [POST http://localhost:8100/session/DD2777BF-624E-4C83-99A5-97DACA7ADB33/wda/tap/nil] with body: {"x":921,"y":null}
------
**Link to appium server logs - Case 2 -** https://gist.github.com/anonymous/d4827eaff21d9030098fcdbe26d10642

2017-09-21 05:55:28:024 - [debug] [XCUITest] Converted web coords {"x":921.1875,"y":644.5} into real coords {"x":921,"y":null}
2017-09-21 05:55:28:026 - [debug] [JSONWP Proxy] Proxying [POST /wda/tap/nil] to [POST http://localhost:8100/session/2B70CC8B-F8B4-4819-BF77-DFA67FCD3B1D/wda/tap/nil] with body: {"x":921,"y":null}

**Comment by mikesalvia** [comment]
@vsadineni1 This looks like another issue. I NEVER get null for my coordinates. It may be somewhat related but not the same. @jlipps @imurchie still working on those logs. I should have some time this week to get this to you, we have been working on a major release and honestly have just kept forgetting to close this loop.

**Comment by imurchie** [comment]
There have been changes recently. We have tests that pass with tabs, app banner, scrolling, etc., and things seem to work well. Once you are ready, upgrade to Appium 1.7.1 and try again. Thanks.

**Comment by vsadineni1** [comment]
@imurchie - Just want to clarify. Are you saying that the null coordinates issue is fixed in Appium 1.7.1?

**Comment by imurchie** [comment]
@vsadineni1 No. I am unable to reproduce that. There is additional logging to try to help track it down and eventually fix it. If you run across the error in 1.7.1, please post the logs so I can see.

**Comment by DylanLacey** [comment]
Additional logging for the null co-ordinate problem, under 1.7.1 - [selenium-server.txt](https://github.com/appium/appium/files/1374089/selenium-server.txt)

**Comment by vsadineni1** [comment]
Thank you @DylanLacey for sharing the logs.
@imurchie @jlipps  - can you please look into the logs ?

**Comment by vsadineni1** [comment]
@imurchie @jlipps Any update on this one please? There are a bunch of tests failing with this error on our side. So your attention on this is highly appreciated.

**Comment by imurchie** [comment]
The null-coordinate issue has been fixed in the latest code. It is available in 1.7.2-beta and will be in 1.7.2 when it is released.

**Comment by mikesalvia** [comment]
@imurchie Thanks much for the follow up we are finally out of our major release mode I will look at this today or tomorrow for sure.

**Comment by imurchie** [comment]
Open a new issue with the pertinent data if this persists.
