### ISSUE TITLE
UiAutomator2: Remove app does not work with version 1.6.3

### ISSUE THREAD

**Issue by ferenchorvath** [appium/appium#7903]
## The problem

The removeApp does not work with the version below:

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Windows 7 Enterprise SP1
* Node.js version (unless using Appium.app|exe): 6.9.5
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: Real device: Nexus 5X
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
```
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 4
04 - undefined
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:342:13)
    at tryCatch (D:\Users\l027926\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (D:\Users\l027926\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator
\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (D:\Users\l027926\AppData\Roaming\npm\node_modules\appium\node_modules\bab
el-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (D:\Users\l027926\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:1
36:37)

```

**Comment by imurchie** [comment]
Please provide the full Appium server logs as a link to a [gist](https://gist.github.com). This is not enough information to proceed in helping at all.

**Comment by mhomb** [comment]
Sorry, we can't create a gist, because our proxy denies access. I've attached the logs. We are running our tests through a selenium hub (v3.0.1) and use the java client (v5.0.0-BETA3).

[appium-uninstall.txt](https://github.com/appium/appium/files/790688/appium-uninstall.txt)

**Comment by imurchie** [comment]
@sravanmedarapu Any thoughts on this?

**Comment by mhomb** [comment]
This is also reproducible when using an emulator with Android 6.0.1 and 7.1.1.

**Comment by sravanmedarapu** [comment]
@mhomb, using latest appium-uiautomator2-driver **v0.2.10** should fix this issue.

**Comment by mhomb** [comment]
Using v0.2.10 I can't even initialize the AppiumDriver. Logs of Appium server and the exception from the Java client are attached.
[appium-init.txt](https://github.com/appium/appium/files/793009/appium-init.txt)
[appium-java-exception.txt](https://github.com/appium/appium/files/793011/appium-java-exception.txt)

**Comment by mhomb** [comment]
I also updated appium-uiautomator2-server manually to v.0.1.2 but I still get the same error (this.adb.getScreenSize is not a function).

**Comment by sravanmedarapu** [comment]
Can you please try by updating appium-adb to v2.11.1 ?

**Comment by mhomb** [comment]
Thank you very much, that helped! Uninstalling now works as expected and this issue can be closed.

So for anyone else having the same issue, updating appium-uiautomator2-driver, appium-uiautomator2-server AND appium-adb to the latest version fixes it.

**Comment by amalsgit** [comment]
I am getting the same error with UiAutomator2 with 1.6.3 appium. I have the latest version of appium-uiautomator2-driver, appium-uiautomator2-server AND appium-adb.  Should i do something to force appium to make use of appium-adb? or does appium use it by default?
