### ISSUE TITLE
Error sending 'language' capability to Android test

### ISSUE THREAD

**Issue by SantiCF** [appium/appium#8016]
## The problem

I get an error while trying to create an AndroidDriver and specifying the language (or locale) in the capabilities. (if I remove that capability, the test runs fine)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3/1.6.4beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe): 7.7.1
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/SantiCF/65594cfe8ae51e349f8c1755684e49e9

## Code To Reproduce Issue [ Good To Have ]

See gist

**Comment by dpgraham** [comment]
I think this is the same issue as https://github.com/appium/appium/issues/6894

@imurchie @jlipps Did we ever make progress on that issue?

**Comment by SantiCF** [comment]
Hi there... I went through the android driver code and in the capabilities, 'language' is not there... maybe that is causing the issue? If 'language' will not be supported by Android, maybe it's best to move that capability in the caps.md file to 'iOS only'.

**Comment by jlipps** [comment]
The `must be root` issue has been fixed in master with the addition of running `adb root` and `adb unroot` for certain commands.

**Comment by amias-channer** [comment]
this is still a problem with Appium 1.6.4 via the ruby libs , I noticed it when I accidentally upgraded one of my test phones to android 7. It wouldn't start and gave this error. fixed it by removing locale and language keys from caps. This is a big limitation !  happy to provide more info to help get this fixed.

**Comment by imurchie** [comment]
Android 7 real devices do not allow you to restart the adb daemon as root, so rebooting the phone is not possible through the command line. Setting the language and locale for such devices will not work.

**Comment by amias-channer** [comment]
so I will need to have a phone set for each language or locale before I run the test and cannot switch automatically ?

**Comment by imurchie** [comment]
Unfortunately. It _is_ possible to automate the restart yourself (using the UI). This is too variable for Appium to generalize, but if you only have one or a few devices it should be entirely possible to do it.

**Comment by ItsPavan** [comment]
Please find the error encountered:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\PKumar\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n shah.darsahan.myclient/shah.darsahan.myclient.LoginActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=shah.darsahan.myclient/.LoginActivity } from null (pid=32620, uid=2000) not exported from uid 10107

Appium : 1.7.1
Android 7.1.1

@amias-channer in one of the earlier comments you've said that you removed language and locale,can you please let me know in which file you removed them.
@imurchie please do help me out if you know solution to this
