### ISSUE TITLE
[Android] Cann't change network connection

### ISSUE THREAD

**Issue by crazyk2** [appium/appium#8267]
## The problem

When I change  connection settings to `AIRPLANE`
`        getDriver().setConnection(AIRPLANE);
`
I have this logs
[gist- ok result](https://gist.github.com/crazyk2/417c188d15a3d30cbc08497347569b19)

When I change  connection settings to `ALL` or `NONE` or `WIFI`
`        getDriver().setConnection(NONE);`

I have this logs
[gist - fail result](https://gist.github.com/crazyk2/fed976f7210a70c5134f9b463e8d7938#file-gistfile1-txt-L15)

I found commit when smd add this code `this.isEmulator`
[cmt](https://github.com/appium/appium-android-driver/commit/ec317fa22a0e2abb396051b78e73124f45dc90ea#diff-c8f3acfe335b2165899f7681c6972c83)

But I cann't fix because I don't know JS.
 I suggest `isEmulator()`  from `lib/driver.js`  didn't import.

## Environment

* java client 5.0.0-BETA7
* Appium server version: 1.6.4
* Node.js version: 7.5.0
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: HTC Desire 820G dual sim

**Comment by crazyk2** [comment]
@mykola-mokhnach Please, see above

**Comment by mykola-mokhnach** [comment]
Thanks for the report. Expect the fix to merged soon into 1.6.5-beta

**Comment by crazyk2** [comment]
```
private DesiredCapabilities initCap(Device device) {
        DesiredCapabilities capabilities = new DesiredCapabilities();

        Path appPath = Paths.get(config.getPathToAndroidApp());
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.ANDROID_UIAUTOMATOR2);
        capabilities.setCapability(MobileCapabilityType.APP, appPath);
        capabilities.setCapability("unicodeKeyboard", "true");
        capabilities.setCapability("resetKeyboard", "true");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "120");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");       // Ignored for Android, though required
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, device.getVersion());       // Ignored for Android, though required
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, ((AndroidDevice) device).getModel());       // Ignored for Android, though required
        capabilities.setCapability(MobileCapabilityType.UDID, device.getUdid());       // Ignored for Android, though required
        capabilities.setCapability(MobileCapabilityType.NO_RESET, "true");
        capabilities.setCapability("appWaitActivity", ".activity.MainActivity,.activity.WelcomeActivity,.activity.EulaActivity,.activity.AuthorizationActivity");
        return capabilities;
    }
```

**Comment by mykola-mokhnach** [comment]
The fix is merged

**Comment by mayureshshirodkar** [comment]
this.isEmulator seems to be fixed. but using getDriver().setConnection(NONE); still throws this error.
org.apache.commons.lang.NotImplementedException: Setting Network Connection to: NONE :is not implemented. 
Logs: https://gist.github.com/986dcd0d3d09771a10564fcc8443cf5b.git

Wifi is not turned off, but it can be turned ON.

Device/OS: Moto G4,6.0.1

**Comment by nairouz12** [comment]
in which version is this issue fixed? I'm facing the same problem in appium 1.6.4

**Comment by vjmaiky** [comment]
mykola-mokhnach commented on Apr 17
Thanks for the report. Expect the fix to merged soon into 1.6.5-beta

**Comment by nairouz12** [comment]
indeed. I've it working now with 1.6.4
thanks!

**Comment by srahul91** [comment]
Hi Guys,
I am also facing the same issue, **WiFi is not getting ON** by using driver.setConnection(Connection.WIFI) function.

**Environment:**
java client 5.0.0-BETA5
Appium server version: 1.6.5Beta
Mobile platform/version under test: Android 5.1.1
Real device: Galaxy Note Edge
Appium is running on: Windows7

**Please get the appium logs below:**
https://pastebin.com/RMkZC6Ay
