### ISSUE TITLE
adb: stop: must be root; can't launch tests on Android 7.0, part 2

### ISSUE THREAD

**Issue by willosser** [appium/appium#8327]
## The problem

When using Appium 1.6.3 and 1.6.4 to test Android N devices, I have the same failure messages as reported in https://github.com/appium/appium/issues/6894

## Environment

Problem shows up in Appium version 1.6.3
MacOS 10.10.5
Node v7.6.0
Device: Samsung GS7, Android 7.0. 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/willosser/fe7bbfb39534e1845b5895ae3564e5cf

## Code To Reproduce Issue [ Good To Have ]

Starting up driver instance is enough to cause this issue.

**Comment by mykola-mokhnach** [comment]
This has been fixed recently. Please try Appium 1.6.5-beta

**Comment by willosser** [comment]
I just tested with Appium 1.6.5-beta and still experience the problem

* a80f39a9 (HEAD) Update version and changelog for 1.6.5 beta (#8237)

Note that i saw the changes put in to fix #6894 in the code

**Comment by imurchie** [comment]
This is a different issue. Seems something catastrophic happens. Unfortunately I don't have an Android 7 real device to test this stuff on. It works on emulators :(. 

Can you trying running your test with `adbd` already running as root?

**Comment by willosser** [comment]
I just tried that, but I'm getting the same result

ps auxww |grep adb
root           94507   0.1  0.0  2461668   3608   ??  Ss   12:49PM   0:01.64 adb -P 5037 fork-server server --reply-fd

2017-04-26 19:49:59:430 - [debug] [ADB] Getting connected devices...
2017-04-26 19:49:59:444 - [debug] [ADB] 1 device(s) connected
2017-04-26 19:49:59:444 - [debug] [ADB] Running '/usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb' with args: ["-P",5037,"-s","1b9a7a0d","shell","stop"]
2017-04-26 19:49:59:509 - [debug] [ADB] Running '/usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb' with args: ["-P",5037,"-s","1b9a7a0d","shell","stop"]
2017-04-26 19:49:59:569 - [debug] [ADB] Device requires adb to be running as root in order to reboot. Restarting daemon
2017-04-26 19:49:59:585 - [debug] [ADB] Getting connected devices...
2017-04-26 19:49:59:596 - [debug] [ADB] 1 device(s) connected
2017-04-26 19:49:59:597 - [debug] [ADB] Running '/usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb' with args: ["-P",5037,"-s","1b9a7a0d","shell","stop"]
2017-04-26 19:49:59:666 - [debug] [ADB] Running '/usr/local/Cellar/android-sdk/24.4.1_1/platform-tools/adb' with args: ["-P",5037,"-s","1b9a7a0d","shell","stop"]
2017-04-26 19:49:59:741 - [debug] [AndroidDriver] Shutting down Android driver

This this on both a Samsung GS7 and a Pixel device

**Comment by oscheller1** [comment]
Tested with an Android 7.0 Nexus 9 real device. Manually running `adb -P 5037 -s <device_name> shell stop` also returns `stop: must be root`. So this might be a 7.0 real device specific problem. Any suggestions on how to proceed from this?

**Comment by appiumnovice** [comment]
I have the same problem with Android 7.1.2 Nexus 5x (Appium 1.6.5-beta).
The applied workaround was to delete capabilities "locale" and "language".
At this moment, the app is correctly installed but I encounter this error:
"java.lang.NullPointerException: null value in entry: language=null".

I can run tests on Android Studio Simulator 7 with these two capabilities.

**Comment by imurchie** [comment]
Real devices above API level 23 do not allow `adbd` to be run as root, unfortunately. This means that the device cannot be rebooted through `adb`, and so the language and locale cannot be set using Appium. In effect, the `language` and `locale` desired capabilities _will_ cause the startup to fail (unless the language and locale on the device happen to be the same as those passed in).

**Comment by appiumnovice** [comment]
So, in this case, is it possible not to force to set these two capabilities to avoid these error messages :
"java.lang.NullPointerException: null value in entry: language=null" and "java.lang.NullPointerException: null value in entry: locale=null"

**Comment by appiumnovice** [comment]
I'm really sorry, I removed these capabilities form the parameters passed to my test, and I forgot to remove the setting of capabilities inside the test (there are set to "null").
Without these capabilities, tests run perfectly on Android 7 device with UIAutomator2.
Thank you for your help.

**Comment by dpgraham** [comment]
@willosser Is this still a problem?

**Comment by willosser** [comment]
We can work around the problem by setting the language and locale capabilities to nil.

**Comment by ItsPavan** [comment]
Please find my script below ,the script is in python,even though i've not set language and locale capabilities in my script i'm getting the error.
I'm running on 7.0 and 7.1.1 emulators
Appium  server version : 1.7.1

Script:
from appium import webdriver
import time

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '7.0'
desired_caps['deviceName'] = 'emulator-5554'
desired_caps['appPackage'] = 'shah.darsahan.myclient'
desired_caps['appActivity'] = 'shah.darsahan.myclient.LoginActivity'
# desired_caps['appWaitActivity'] = '.ui.activity.LoginActivity,.ui.activity.WorkspaceActivity'
desired_caps['app'] = 'C:\\Users\\PKumar\\Downloads\\Mentorbot .apk'
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
time.sleep(5)
driver.find_element_by_id("shah.darsahan.myclient:id/name_txt").send_keys("Pavan")
driver.find_element_by_id("shah.darsahan.myclient:id/num_txt").send_keys("7760564567")
driver.find_element_by_id("shah.darsahan.myclient:id/email_txt").send_keys("pavankumar.bh@planktonsolutions.com")
driver.find_element_by_id("shah.darsahan.myclient:id/proceed_btn").click()
driver.quit()

Error:
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\PKumar\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s emulator-5554 shell am start -W -n shah.darsahan.myclient/shah.darsahan.myclient.LoginActivity -S' exited with code 1'; Stderr: 'java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=shah.darsahan.myclient/.LoginActivity } from null (pid=5185, uid=2000) not exported from uid 10084
        at android.os.Parcel.readException(Parcel.java:1683)
        at android.os.Parcel.readException(Parcel.java:1636)
        at android.app.ActivityManagerProxy.startActivityAndWait(ActivityManagerNative.java:3178)
        at com.android.commands.am.Am.runStart(Am.java:630)
        at com.android.commands.am.Am.onRun(Am.java:388)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:121)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)'; Code: '1'

**Comment by imurchie** [comment]
@ItsPavan You do not have permission to start the activity you are trying to start (`shah.darsahan.myclient/shah.darsahan.myclient.LoginActivity`). You need to either start a different activity or fix your app so that activity can start.

**Comment by ItsPavan** [comment]
@imurchie thanks for the reply.
As I'm a manual tester exploring automation now I'm not sure how to really change permissions ,also do not have access to development code to fix the app.
You also mentioned that I need to start different activity,can you please let me know how can I find a different activity which will launch the app?

**Comment by imurchie** [comment]
I would first try removing the `appPackage` and `appActivity` desired capabilities and let the system figure out the defaults.
