### ISSUE TITLE
Cannot launch an android activity properly

### ISSUE THREAD

**Issue by luisromanwp** [appium/appium#8359]
## The problem

I'm trying to use the startActivity with com.android.settings/.Settings$NotificationAppListActivity as driver.startActivity("com.android.settings", ".Settings$NotificationAppListActivity") but only opens the Settings main screen instead of the App Notifications Screen

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5 BETA
* Desktop OS/version used to run Appium: Mac OS Sierra
* Mobile platform/version under test: Android 7.1
* Real device or emulator/simulator: Nexus 5 Emulator

## Link to Appium logs

https://gist.github.com/luisromanwp/e514773805b462a3a6fcd7ef3dc79f98

## Code To Reproduce Issue [ Good To Have ]

driver.startActivity("com.android.settings", ".Settings$NotificationAppListActivity")

**Comment by mykola-mokhnach** [comment]
I think this issue has been resolved very [recently](https://github.com/appium/appium-adb/pull/222). Please try to reinstall your beta to get the most recent updates.

**Comment by luisromanwp** [comment]
I just updated the Appium and is still happening the same, is the driver.startActivity("com.android.settings", ".Settings$NotificationAppListActivity") wrong?

**Comment by mykola-mokhnach** [comment]
You can check it manually to make sure the name is correct or not. Just start it from the UI and then check the list of activities using adb.

**Comment by luisromanwp** [comment]
Yes, the name is the activity name that Android Studio gives me that name and if I execute like this "adb shell am start -n 'com.android.settings/.Settings\$NotificationAppListActivity'" in the terminal works correctly

**Comment by mykola-mokhnach** [comment]
@imurchie It's very strange, but somehow I don't see this commit https://github.com/appium/appium-adb/pull/222 in appium-adb's master branch %).

**Comment by mykola-mokhnach** [comment]
Make sure the appium-adb component is at version 2.17.4 or later

**Comment by luisromanwp** [comment]
appium-adb is 2.19.0, and not working

**Comment by mykola-mokhnach** [comment]
@vikki Can you please assist?

**Comment by vikki** [comment]
Hey @mykola-mokhnach - I don't have the right set up to reproduce the issue but I think I know what the problem is.

It looks like a similar issue to the one I fixed with the previous PR, but it's in a different place - this one's in startApp, rather than on the waitActivity. The PR I sent escaped the dollar sign in the wait activity, but what's happening here is that when we start the activity, we send an un-escaped string to exec, so basically adb cuts off the inner class/after the $, and only starts the outer class.

When I try to launch that activity from the command line I need to escape it like this for it to launch the notifications screen:

`adb shell am start -n 'com.android.settings/.Settings\$NotificationAppListActivity'`

which is I think what we need to do here too. I can't do a PR today but I will take a look tomorrow if no-one gets there before me :) HTH!

**Comment by mykola-mokhnach** [comment]
Thanks a lot for your help @vikki . We are looking forward to see the PR.

**Comment by luisromanwp** [comment]
Thank you so much @mykola-mokhnach and @vikki for your help!!!
