### ISSUE TITLE
setValue not working on text field in iOS Simulator

### ISSUE THREAD

**Issue by mwyld** [appium/appium#8407]
## The problem

When trying to do a setValue in a text field it doesn't work for iOS simulator. The logs return the following: 

`Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]`

Running selenium standalone 3.4.0

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): unsure
* Desktop OS/version used to run Appium: MAC Sierra 10.12.4
* Node.js version (unless using Appium.app|exe): 6.10.0
* Mobile platform/version under test: 10.1
* Real device or emulator/simulator: iOS simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

`Logging in with a invalid username and password I enter myUsername@doesNotExist.com in the username text box:

Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]

running Safari

Error: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]
    at Object.exports.inputText (test/e2e/features/step_definitions/base.js:64:11)
    at World.<anonymous> (test/e2e/features/step_definitions/base.step.js:54:10)
    at Promise.F (node_modules/core-js/library/modules/_export.js:35:28)
    at elementIdValue("5005", "myUsername@doesNotExist.com") - setValue.js:46:80
`

**Comment by mykola-mokhnach** [comment]
Downgrade Selenium to workaround the problem. @imurchie Did we implement the support of new setValue protocol in 1.6.5 beta?

**Comment by mwyld** [comment]
Okay I'll give it a go, any suggested version? SetValue works okay on a real android device

**Comment by mykola-mokhnach** [comment]
Use the one bundled with the recent java-client BETA (3.3.1)

**Comment by GeeChao** [comment]
Also have the same issue with the latest selenium-standalone with both 3.4.0 and 3.3.1, using webdriverIO version 4.8.0 and appium version 1.6.5-beta

**Comment by mykola-mokhnach** [comment]
The fix has been recently merged to the master branch of base driver, but it's not tagged yet. @imurchie can you please add a new version tag there, so the change is available in beta?

**Comment by mykola-mokhnach** [comment]
The fix is merged to master and is available in beta

**Comment by akifhazarvi** [comment]
Hi Guys
I still see the same issue using conceptjs. Running a test on IOS 10.2 Iphone 6
Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value","text"]
Appium 1.6.5
codeceptjs: 1.0.3
webdriverio: 4.8.0

**Comment by GeeChao** [comment]
@akifhazarvi it's a bug with wdio 4.8.0 check out 4.7.1
