### ISSUE TITLE
Selendroid:  Cannot read property 'platform' of null. Missing null handler in android-manifest.js

### ISSUE THREAD

**Issue by stefankahn** [appium/appium#8773]
## The problem

platform can be null on line 124 of [android-manifest.js](https://github.com/appium/appium-adb/blob/master/lib/tools/android-manifest.js), when getAndroidPlatformAndPath() returns a valid null.

This not caught in the check on line 125 and will attempt to compile the manifest when no platform versions are installed.

Root cause was no android platforms installed.
Installing atleast 1 android platform from the list at the top of [helper.js.](https://github.com/appium/appium-adb/blob/master/lib/helpers.js) resolves it.
_sdkmanager "platforms;android-25"_

Why is the capability automationName: Appium not impacted by the missing android platforms?

## Environment
It is important to note this approach works with capability automationName: Appium without an issue. 
A mac without any android sdk or platforms installed.
Andoird sdk installed via brew.
_brew cask install android-sdk_
platform-tools installed via sdkmanager
_sdkmanager "platform-tools"_

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra
* Mobile platform/version under test:
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium cli

## Details
When running tests using Selendroid (automationName: Selendroid), null exception on property 'platform'.

## Link to Appium logs
 [Short Log](https://gist.github.com/stefankahn/dc2451e1d0798459b891f720e461f9a2)

## Code To Reproduce Issue [ Good To Have ]
A basic android appium test using capability automationName: Selendroid will work.

**Comment by mykola-mokhnach** [comment]
It's how the code looks in master now. And I see the value of _platform_ is verified there. Are you sure your Appium sources are up to date? 

```
manifestMethods.compileManifest = async function (manifest, manifestPackage, targetPackage) {
  log.debug(`Compiling manifest ${manifest}`);
  let {platform, platformPath} = await getAndroidPlatformAndPath();
  if (!platform) {
    return new Error("Required platform doesn't exist (API level >= 17)");
  }
  log.debug('Compiling manifest.');
....
```

**Comment by stefankahn** [comment]
Hi, yes i can reproduce this on 1.6.5 and 1.6.6-beta.
platform can be null, See the return from getAndroidPlatformAndPath() in helper.js

  let platforms = path.resolve(androidHome, 'platforms');
  for (let platform of _.clone(androidPlatforms).reverse()) {
    let platformPath = path.resolve(platforms, platform);
    if (await fs.exists(platformPath)) {
      return {platform, platformPath};
    }
  }
  return null;
}

**Comment by mykola-mokhnach** [comment]
so the problem lies in `return null` ? Then replacing it with `return {null, null}` should solve the problem

**Comment by mykola-mokhnach** [comment]
@stefankahn Would you like to create a PR?

**Comment by stefankahn** [comment]
That would still show the same error in the appium console. Wouldnt it be better to add a null check?
  if (platform == null) {
    return new Error("No Android platforms found");
  }

**Comment by mykola-mokhnach** [comment]
Where exactly do you want to add it?

**Comment by stefankahn** [comment]
here. 
manifestMethods.compileManifest = async function (manifest, manifestPackage, targetPackage) {
  log.debug(`Compiling manifest ${manifest}`);
  let {platform, platformPath} = await getAndroidPlatformAndPath();
  if (!platform) {
    return new Error("Required platform doesn't exist (API level >= 17)");
  }
  if (platform == null) {
    return new Error("No Android platforms found");
 }
  log.debug('Compiling manifest.');
....

**Comment by mykola-mokhnach** [comment]
it won't help. `!platform` already does the thing

**Comment by mykola-mokhnach** [comment]
try to fix parameters desctruction like described above. Then execute `gulp transpile` to transpile your changes (it will ask you to add some more helper modules to do it)

**Comment by stefankahn** [comment]
Okay. i'll give a try when im back in the morning.

**Comment by stefankahn** [comment]
How did you get on?

**Comment by jlipps** [comment]
@mykola-mokhnach did we determine whether we have fixed the error message in this case?

**Comment by mykola-mokhnach** [comment]
@jlipps The fix for this issue has been merged a while ago. it is only necessary to install beta to have it available locally:

```bash
npm uninstall -g appium
npm i -g appium@beta
```

**Comment by jlipps** [comment]
great, closing this then.
