### ISSUE TITLE
[debug] [XCUITest] Connection to WDA timed out

### ISSUE THREAD

**Issue by sasasa42** [appium/appium#9418]
## The problem

I was running my automation on the app as usual. I do not know what happened since a month, I am facing this issue where in after the automation script execution is done, at last after pausing for some time, this statement gets printed in the end "[debug] [XCUITest] Connection to WDA timed out" and again waits for a few seconds and finally closes. This is the behaviour when run locally on my system. But on bamboo CI, the issue is even worse, after the "[debug] [XCUITest] Connection to WDA timed out"  gets printed, the CI waits for some reason and after 20 minutes, seeing no response, the Hung Build Killer(HBK) task gets called and the plan gets completed after a long time. Ideally, the scripts should not take more than 2 minutes. Totally, because of this issue, it takes around 30 minutes to complete.

## Details are in Appium logs Attached
[WDA_Connection.txt](https://github.com/appium/appium/files/1371264/WDA_Connection.txt)

**Comment by mykola-mokhnach** [comment]
"Connection to WDA timed out" error means that WebDriverAgent server stopped responding to Appium requests. This might happen due to different reasons - try to find out when this usually happens. Device logs investigation might help as well.

**Comment by sintoanto** [comment]
@mykola-mokhnach I am not sure on how to investigate through the device logs. Could you please provide me the path on where to search for?

**Comment by mykola-mokhnach** [comment]
Something like this: https://support.kaspersky.com/12419

**Comment by sintoanto** [comment]
@mykola-mokhnach btw, this issue is not specific to one Device alone but for all the iOS devices.

**Comment by mykola-mokhnach** [comment]
You issue might be a duplicate of https://github.com/facebook/WebDriverAgent/issues/730

**Comment by sintoanto** [comment]
No @mykola-mokhnach . This is not related to the above mentioned issue. This issue happens irrespective of the Appium able to find or not able to find the elements. The test passes, but in the end, the timeout message appears and waits for some time more and then ends it. I updated to Appium v1.7.2-beta. But still facing the same problem again and again.

**Comment by sintoanto** [comment]
@imurchie - Any idea on how to resolve this issue? This is really a pain to fix. No resolution yet. I tried almost all the steps from the similar or referenced issues. Nothing eventually worked.

**Comment by sasasa42** [comment]
Is there any updates on this issue yet. No resolutions found so far

**Comment by saikrishna321** [comment]
@sasasa42 Please try with latest appium version, if issue exists pls raise a new issue

**Comment by eduardofinotti** [comment]
I have the same problem!!!

**Comment by eduardofinotti** [comment]
@arronhai @sasasa42 Work for me.
I fixed this problem adding this configurations in my codecept.json:

```
      "restart": "true",
      "useNewWDA": true,
      "wdaLaunchTimeout": "999999999",
      "wdaConnectionTimeout": "999999999",
```

**Comment by sasasa42** [comment]
> @sasasa42 Excuse me, have you solved this problem? i have the same problem now , i tried a lot of solutions and they didn't work

Yes. I managed to resolve this long back by doing similar to what @eduardofinotti suggested. Just the values were different.

**Comment by ritesh2689** [comment]
Although every thing works fine for me but i still see this issue in my appium logs even after setting "wdaLaunchTimeout": "999999999",
      "wdaConnectionTimeout": "999999999",

Appium version is 1.12.0
The issue is irrespective of the ios version under test.

**Comment by eduardofinotti** [comment]
@ritesh2689 Try set too:

`
"restart": "true",
"useNewWDA": true,
`

**Comment by ritesh2689** [comment]
@eduardofinotti Cool thanks....I will get back with an update.

**Comment by ritesh2689** [comment]
> @ritesh2689 Try set too:
> 
> `"restart": "true", "useNewWDA": true,`

"true" as String or Boolean?

**Comment by ritesh2689** [comment]
@eduardofinotti 
I still see the same issue.

2019-05-03 11:25:17:750 - [debug] [XCUITest] Connection to WDA timed out
2019-05-03 11:25:17:750 - [debug] [iProxy] recv failed: Operation not permitted

Appium Version - 1.12.0
iOS version - iPhone 6s - 12.1 , iPhone 6 - 11.4 (Real Device)
macOS version - 10.14.4
Appium Java Client - 6.1.0
Xcode version - 10.2.1
node version - 10.15.3
npm version - 6.9.0

capabilities.setCapability("wdaLocalPort", wdaLocalPort);
capabilities.setCapability(MobileCapabilityType.UDID, UDID);
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,deviceName);
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,platformVersion);
capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
capabilities.setCapability("useNewWDA", true);
capabilities.setCapability("wdaLaunchTimeout", "999999999");
capabilities.setCapability("wdaConnectionTimeout", "999999999");
capabilities.setCapability("restart", true);
capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION,testData.get("appium.appiumVersion"));
capabilities.setCapability("startIWDP", true);
capabilities.setCapability("webkitResponseTimeout", 70000);
capabilities.setCapability("autoWebView", true);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,testData.get("ios.automationName"));
capabilities.setCapability("xcodeOrgId", testData.get("appium.xcodeOrgId"));
capabilities.setCapability("xcodeSigningId",testData.get("appium.xcodeSigningId"));
capabilities.setCapability("waitForQuiescence", false);
capabilities.setCapability("bundleId", jsonObjectUtil.getObject("bundleId"));
capabilities.setCapability("showXcodeLog", testData.get("appium.showXcodeLog"));
capabilities.setCapability("newCommandTimeout",testData.get("appium.newCommandTimeout"));
capabilities.setCapability("clearSystemFiles",testData.get("appium.clearSystemFiles"));
