### ISSUE TITLE
Error trying to access shadowRoot elements on iOS

### ISSUE THREAD

**Issue by dyhopper1** [appium/appium#9733]
## The problem
Can't access elements under a shadowRoot on iOS real device.
We have an automation suite that runs on our Chrome app, and our Mac and Windows Electron apps using Selenium Webdriver.  I'm hoping to use much of the same code on our Hybrid iOS app via Appium.
We use Polymer and thus have to access elements under shadowRoots.
On other platforms, we are doing this via
shadowElement = $driver.execute_script('return document.querySelector("blah_blah").shadowRoot')
el = shadowElement.find_element(:css => "#id_of_my_element")

This is not working in Appium.  I'm getting a "Recursive object cannot be transferred" error.

## Environment

Appium 1.7.1 (using Appium desktop app 1.2.7)
Mac OS 10.13
Xcode 9.1
iOS 11.1.2 on real iPad Air

## Details
I believe I have the capabilities set up correctly, as I can switch to the web context and access the elements above the shadowRoot elements.  
When running the sample code below I get the error: "[MJSONWP] Encountered internal error running command: Error: Error while executing atom: Recursive object cannot be transferred (status: 13)"

## Link to Appium logs

https://gist.github.com/dyhopper1/0df126924abfd093ae02c80fc71a5fc4

## Code To Reproduce Issue [ Good To Have ]
(Sample ruby code)

`capabilities =
  {
  "bundleId"=> "com.vernier.spectralanalysis",
  "udid" => "1905da18d1c56349efb55ab04xxxxxxxxxxxxxxx",
  "platformName" => "iOS",
  "deviceName" => "iPad Air",
  "platformVersion" => "11.1",
  "xcodeOrgId" => "xxxxxxxxxx",
  "xcodeSigningId" => "iPhone Developer",
  "startIWDP" => true
  }

$driver = Appium::Driver.new({:caps => capabilities}, false).start_driver
sleep 4
webview = $driver.available_contexts.last
$driver.set_context(webview) #works

el = $driver.execute_script('return document.querySelector("vst-sa-app")')
p el  # just to prove the element was retrieved successfully. no problem.

#the following line results in error
shadowEl = $driver.execute_script('return document.querySelector("vst-sa-app").shadowRoot')

`

**Comment by dyhopper1** [comment]
I'm still stuck on this.  If anyone has any advice on what else I could try to get more information, please let me know.

**Comment by ringles-icfi** [comment]
I'm having the same problem. The same script works well on Safari Desktop but would raise "Recursive object cannot be transferred" error on Safari iOS

**Comment by dyhopper** [comment]
@ringles-icfi or anyone else.  Did you ever come up with a good workaround for this issue?

**Comment by jordanaustin** [comment]
@mykola-mokhnach do you know why this is marked as third party? If so, who's issue do you think this is? I'd love to help find a solution to this issue.

**Comment by mykola-mokhnach** [comment]
> do you know why this is marked as third party? If so, who's issue do you think this is?

I think the problem has to do with javascript processing inside mobile safari. Appium is just acting as a proxy between your client code and the js engine. 

We'd appreciate it if you could help to find a proper solution.

**Comment by jordanaustin** [comment]
@mykola-mokhnach the interesting thing is that running these same commands on the device with remote debugging through Safari's developer tools doesn't throw this error.

**Comment by imurchie** [comment]
Can you try to add `.host` to the end, so, for instance,
```js
document.querySelector("dropdown").shadowRoot
```
would become
```js
document.querySelector("dropdown").shadowRoot.host
```

**Comment by jordanaustin** [comment]
@imurchie thanks for your reply! You're thinking along the same lines as me, I tried this previously and again just now. The problem with using `.host` is that this just gives you the host element again, so 

    document.querySelector("dropdown").shadowRoot.host 

Will just return you the `dropdown` as if you just used

    document.querySelector("dropdown")

So using find_element at that point will just result in not being able to locate the element, because you're not in the shadowRoot

**Comment by imurchie** [comment]
Hmm. That makes sense. 

The problem is in the Selenium "atoms", which is how Appium injects JavaScript into the page context. When I remove the check that throw the error, the element available is like the following:
```js
{ mode: 'open',
  host: { ELEMENT: ':wdc:1531325564675' },
  innerHTML: '\n      <style>\n        p {\n          color: red;\n        }\n      </style>\n\n      <p>Element with Shadow DOM</p>',
  activeElement: null,
  elementFromPoint: 'function elementFromPoint() {\n    [native code]\n}',
  elementsFromPoint: 'function elementsFromPoint() {\n    [native code]\n}',
  children:
   [ { ELEMENT: ':wdc:1531325564676' },
     { ELEMENT: ':wdc:1531325564677' } ],
  firstElementChild: { ELEMENT: ':wdc:1531325564676' },
  lastElementChild: { ELEMENT: ':wdc:1531325564677' },
  childElementCount: 2,
  getElementById: 'function getElementById() {\n    [native code]\n}',
  prepend: 'function prepend() {\n    [native code]\n}',
  append: 'function append() {\n    [native code]\n}',
  querySelector: 'function querySelector() {\n    [native code]\n}',
  querySelectorAll: 'function querySelectorAll() {\n    [native code]\n}',
  nodeType: 11,
  nodeName: '#document-fragment',
  baseURI: 'http://localhost:4994/test/shadow',
  isConnected: true,
  ownerDocument: { ELEMENT: ':wdc:1531325564678' },
  parentNode: null,
  parentElement: null,
  childNodes:
   [ [ null, null, null, null, null, null, null ],
     { ELEMENT: ':wdc:1531325564676' },
     [ null, null, null, null, null, null, null, null ],
     { ELEMENT: ':wdc:1531325564677' } ],
  firstChild: [ null, null, null, null, null, null, null ],
  lastChild: { ELEMENT: ':wdc:1531325564677' },
  previousSibling: null,
  nextSibling: null,
  nodeValue: null,
  textContent: '\n      \n        p {\n          color: red;\n        }\n      \n\n      Element with Shadow DOM',
  getRootNode: 'function getRootNode() {\n    [native code]\n}',
  hasChildNodes: 'function hasChildNodes() {\n    [native code]\n}',
  normalize: 'function normalize() {\n    [native code]\n}',
  cloneNode: 'function cloneNode() {\n    [native code]\n}',
  isEqualNode: 'function isEqualNode() {\n    [native code]\n}',
  isSameNode: 'function isSameNode() {\n    [native code]\n}',
  compareDocumentPosition: 'function compareDocumentPosition() {\n    [native code]\n}',
  contains: 'function contains() {\n    [native code]\n}',
  lookupPrefix: 'function lookupPrefix() {\n    [native code]\n}',
  lookupNamespaceURI: 'function lookupNamespaceURI() {\n    [native code]\n}',
  isDefaultNamespace: 'function isDefaultNamespace() {\n    [native code]\n}',
  insertBefore: 'function insertBefore() {\n    [native code]\n}',
  appendChild: 'function appendChild() {\n    [native code]\n}',
  replaceChild: 'function replaceChild() {\n    [native code]\n}',
  removeChild: 'function removeChild() {\n    [native code]\n}',
  ELEMENT_NODE: 1,
  ATTRIBUTE_NODE: 2,
  TEXT_NODE: 3,
  CDATA_SECTION_NODE: 4,
  ENTITY_REFERENCE_NODE: 5,
  ENTITY_NODE: 6,
  PROCESSING_INSTRUCTION_NODE: 7,
  COMMENT_NODE: 8,
  DOCUMENT_NODE: 9,
  DOCUMENT_TYPE_NODE: 10,
  DOCUMENT_FRAGMENT_NODE: 11,
  NOTATION_NODE: 12,
  DOCUMENT_POSITION_DISCONNECTED: 1,
  DOCUMENT_POSITION_PRECEDING: 2,
  DOCUMENT_POSITION_FOLLOWING: 4,
  DOCUMENT_POSITION_CONTAINS: 8,
  DOCUMENT_POSITION_CONTAINED_BY: 16,
  DOCUMENT_POSITION_IMPLEMENTATION_SPECIFIC: 32,
  addEventListener: 'function addEventListener() {\n    [native code]\n}',
  removeEventListener: 'function removeEventListener() {\n    [native code]\n}',
  dispatchEvent: 'function dispatchEvent() {\n    [native code]\n}' }
```

Perhaps it is possible to develop queries based on available properties or functions?

**Comment by jordanaustin** [comment]
@imurchie this is very interesting! Could you point me to where that check is at? I'm digging into Selenium for the first time, so any direction would be great!

**Comment by imurchie** [comment]
The check itself is happening here: https://github.com/SeleniumHQ/selenium/blob/master/javascript/atoms/inject.js#L123-L126

**Comment by dominikg** [comment]
Selenium atoms seem to have more issues with shadow-dom. e.g. https://github.com/SeleniumHQ/selenium/issues/6399

I stumbled accross that when i wrote a custom By implementation that uses javascript to find elements inside a shadowroot. This custom By works in chromedriver but fails when run via Appium (i guess chromedriver does not use these atoms because why not....)

**Comment by caseycantwell** [comment]
Has anyone found a work around to this?  We haven't been able to find a way to execute selenium scripts on appium and IOS, where shadow doms are used.  Our work around to lack of shadow dom support works fine on Chrome / Android with appium.

**Comment by mykola-mokhnach** [comment]
Linking https://appiumpro.com/editions/44

**Comment by alfonso-presa** [comment]
Any news on this issue? Interacting with the elements via JS is not ideal as elements are not interacted as the user would do so it may give false positives when executing tests (element is interactuable with JS and not by the user).

**Comment by imurchie** [comment]
This has been fixed in version 1.16.0

**Comment by dyhopper** [comment]
We were excited to see this get fixed, but I just tried the exact steps from the original ticket and this issue is still happening with Appium 1.16.0.  Maybe there is a different way I should be accessing the shadowRoot elements?
My environment now:
Appium 1.16.0
Mac OS 10.14.6
Xcode 11.3
iOS 12.4.1 on real iPad Pro

**Comment by imurchie** [comment]
Can someone provide an app in which this is a problem?

**Comment by dyhopper** [comment]
Sorry for the delay.  Yes, this is easily reproduced using the sample site at http://shop.polymer-project.org.
 Here is my quick code to demonstrate the issue:
```
require 'appium_lib'

caps =
{
  'browserName' => 'safari',
  'deviceName' => 'iPad',
  'platformVerion' => '12.4',
  "platformName" => "iOS",
  "automationName" => "XCUITest",
  "udid" => "[something]",
  "startIWDP" => true,
  "xcodeOrgId" => "[something]",
  "xcodeSigningId" => "iPhone Developer"
}
appiumlib = {
  "server_url": "http://localhost:4723/wd/hub"
}
$driver = Appium::Driver.new({:caps => caps, :appium_lib => appiumlib}, false).start_driver
$driver.get("http://shop.polymer-project.org")
btn = $driver.execute_script("return document.querySelector('shop-app').shadowRoot.querySelector('shop-home').shadowRoot")
btn.find_element("shop-button")
```

**Comment by dyhopper** [comment]
@imurchie This is still limiting our ability to work with shadowDoms on iOS. Is there any further news on this? Can we re-open this ticket since it really isn't fixed as stated.  Or, should I just create a new ticket?
Thanks!

**Comment by imurchie** [comment]
@dyhopper Sorry, this slipped through my workload. I'll take a look at what is going on with your repro case.

**Comment by imurchie** [comment]
The error I'm seeing is
```
info [11-39-56:104] HTTP --> POST /wd/hub/session/f0f3b175-b645-479d-a113-5dc6d9262cae/execute
info [11-39-56:104] HTTP {"script":"return document.querySelector('shop-app').shadowRoot.querySelector('shop-home').shadowRoot","args":[]}
dbug [11-39-56:105] MJSONWP (f0f3b175) Calling XCUITestDriver.execute() with args: ["return document.querySelector('shop-app').shadowRoot.querySelector('shop-home').shadowRoot",[],"f0f3b175-b645-479d-a113-5dc6d9262cae"]
dbug [11-39-56:105] XCUITest Executing command 'execute'
dbug [11-39-56:105] RemoteDebugger Executing atom 'execute_script'
dbug [11-39-56:111] RemoteDebugger Executing 'execute_script' atom in default context
dbug [11-39-56:111] RemoteDebugger Sending javascript command: '(function(){return function(){var e=this;
dbug [11-39-56:111] RemoteDebugger funct...'
dbug [11-39-56:111] RemoteDebugger Sending '_rpc_forwardSocketData:' message to app 'PID:8435', page '2', target 'page-20' (id: 42): 'Runtime.evaluate'
dbug [11-39-56:607] BaseDriver Waiting up to 0 ms for condition
dbug [11-39-56:608] WD Proxy Matched '/elements' to command name 'findElements'
dbug [11-39-56:609] WD Proxy Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/2A91D5FE-B251-4314-8C42-F7CF3B694A99/elements] with body: {"using":"class name","value":"XCUIElementTypeScrollView"}
dbug [11-39-56:626] WD Proxy Got response with status 200: {"value":[],"sessionId":"2A91D5FE-B251-4314-8C42-F7CF3B694A99"}
dbug [11-39-56:847] RemoteDebugger Received data response from send (id: 42): '{"status":17,"value":{"message":"Recursive object cannot be transferred"}}'
dbug [11-39-56:847] RemoteDebugger Sending to Web Inspector took 736ms
dbug [11-39-56:848] MJSONWP Matched JSONWP error code 17 to JavaScriptError
dbug [11-39-56:857] XCUITest Error received while executing atom: Recursive object cannot be transferred
dbug [11-39-57:132] MJSONWP (f0f3b175) Encountered internal error running command: JavaScriptError: Recursive object cannot be transferred
dbug [11-39-57:132] MJSONWP (f0f3b175)     at errorFromMJSONWPStatusCode (/Users/isaacmurchie/code/appium-xcuitest-driver/node_modules/appium-base-driver/lib/protocol/errors.js:764:12)
dbug [11-39-57:132] MJSONWP (f0f3b175)     at convertResult (/Users/isaacmurchie/code/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/helpers.js:253:11)
dbug [11-39-57:132] MJSONWP (f0f3b175)     at RemoteDebugger.execute (/Users/isaacmurchie/code/appium-xcuitest-driver/node_modules/appium-remote-debugger/lib/remote-debugger.js:753:12)
info [11-39-57:133] HTTP <-- POST /wd/hub/session/f0f3b175-b645-479d-a113-5dc6d9262cae/execute 500 1028 ms - 125
```

**Comment by imurchie** [comment]
The latest beta of Appium (with `appium-remote-debugger@8.7.0`) should not have the "Recursive object cannot be transferred" error. Still working on interacting with Shadow elements, though your mileage may vary on that.

**Comment by sweaver2** [comment]
Just wanted to check in on this situation and see if there has been any movement on interacting with Shadow elements.

**Comment by itaymelamed** [comment]
any update?

**Comment by caseycantwell** [comment]
Any update on this issue?

**Comment by parholmdahl** [comment]
Is there any updates here? I am trying to automate a webpage with lots if shadowRoots, and have no problems in Android. But for IOS it does not work..

**Comment by Ceebox** [comment]
Any luck here? I've tried to fix it myself and find workarounds but the problem seems deeper than my surface-level understanding of Selenium / Appium.

**Comment by mykola-mokhnach** [comment]
Root cause tracked down to appium-remote-debugger's injected atoms. execute_script results are serialized in wrapValue (atoms/src/core/inject.ts), which duck-types DOM elements/documents by nodeType and swaps them for an opaque element reference before serialization. A ShadowRoot's nodeType is DOCUMENT_FRAGMENT_NODE, so it wasn't recognized and fell through to plain-object serialization instead — and since shadowRoot.host.shadowRoot === shadowRoot, that recursed forever, producing the "Recursive object cannot be transferred" error.

[Fix](https://github.com/appium/appium-remote-debugger/pull/530): wrapValue now also recognizes a DOCUMENT_FRAGMENT_NODE with a host property (i.e. a ShadowRoot) and hands it an element-cache reference the same way it already does for elements, so a returned shadow root round-trips correctly and can be used for locators against it afterward.
