### ISSUE TITLE
Failed to change language in appium 1.7.2

### ISSUE THREAD

**Issue by MioOgbeni** [appium/appium#9987]
## The problem

Hello, I'm trying to change the language on my AVD before all tests, but after transitioning from old SDK Tools to Android Studio, I'm getting this error (below). Every time AVD starts, it try to change language, but after this, log throws error (below) and first test fall with error (below), but them AVD running correctly in changed language and other test are Pass.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: And 5.1.1 - 8.0.0 (all of them)
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Link to Appium logs

[https://gist.github.com/MioOgbeni/e8b88c6541c4bb1bacbe1f872725b9e1](https://gist.github.com/MioOgbeni/e8b88c6541c4bb1bacbe1f872725b9e1)

**Comment by mykola-mokhnach** [comment]
Why do you provide both `avd` and `deviceName` capabilities?

**Comment by MioOgbeni** [comment]
Because without one of these capabilities, appium throws error, avd or deviceName can't be blank.

**Comment by imurchie** [comment]
Adb is getting disconnected in the middle of the operation. Locally this fixes it: https://github.com/appium/appium-adb/pull/286

**Comment by funkyvisions** [comment]
Seeing the same thing.

**Comment by imurchie** [comment]
Try with Appium v 1.8.0-beta

**Comment by mykola-mokhnach** [comment]
Fixed in beta

**Comment by hansjoergkeser** [comment]
Hello at all, 

i encounter the same problem. Tried it with Appium v1.8.0-beta3, but still the same error message:
Encountered internal error running command: Error: Failed to set language: de and country: de_DE

Guess the fix is not yet implemented in the beta`?
